examples/2016-10-31/api_swagger_cors/index.js, examples/2016-10-31/api_swagger_cors/swagger.yaml, examples/2016-10-31/api_swagger_cors/template.yaml
=> Adding example to create API endpoint with Swagger file and CORS

CONTRIBUTING.md, README.md
Hi guys,
Just because long lines that span too far across the monitor are hard
to read.
Thanks for review and merge.
=> Wrapping lines

versions/2016-10-31.md
Include policy document example, because it confused me too.
Closes #88.
=> Improve function policy example.

versions/2016-10-31.md
fixing the representation of its spacing
=> re-aligning Tag block for AWS::Serverless::Function

examples/2016-10-31/alexa_skill/template.yaml, examples/2016-10-31/api_backend/template.yaml, examples/2016-10-31/api_swagger_cors/template.yaml, examples/2016-10-31/hello_world/template.yaml, examples/2016-10-31/inline_swagger/template.yaml, examples/2016-10-31/iot_backend/template.yaml, examples/2016-10-31/s3_processor/template.yaml, examples/2016-10-31/schedule/template.yaml, examples/2016-10-31/stream_processor/template.yaml, versions/2016-10-31.md
So I can continue to copy and paste examples.
=> Update nodejs version in examples to 6.10.

examples/2016-10-31/api_swagger_cors/swagger.yaml, examples/2016-10-31/api_swagger_cors/template.yaml
Update to use AWS::Include Transform, instead of using Stage Variables
workaround for runtime linking of Lambda and Region
=> Update to use AWS::Include

docs/policy_templates_data/policy_templates.json
Fixed a typo in the description
=> Fix description for S3CrudPolicy

examples/2016-10-31/encryption_proxy/encryption.py
See: https://github.com/awslabs/serverless-application-model/issues/267
=> Python encryption sample: bugfix in encryption function

docs/globals.rst
Properly format bullet points for UnsupportedProperties
=> Nit: globals.rst bullet points

.coveragerc, .flake8, .github/ISSUE_TEMPLATE.md, .gitignore, .pylintrc, .travis.yml
=> Adding dotfiles for Travis, Flake, Coverage and Pylint

examples/apps/lex-make-appointment/lambda_function.py, examples/apps/lex-order-flowers/lambda_function.py, examples/apps/logicmonitor-send-cloudwatch-events/lambda_function.py, samtranslator/intrinsics/actions.py, samtranslator/intrinsics/resource_refs.py, samtranslator/model/api/api_generator.py, samtranslator/model/eventsources/push.py, samtranslator/model/function_policies.py, samtranslator/model/s3_utils/uri_parser.py, samtranslator/model/sam_resources.py, samtranslator/model/types.py, samtranslator/swagger/swagger.py, samtranslator/translator/logical_id_generator.py, tests/translator/test_api_resource.py, tests/translator/test_translator.py, tests/translator/validator/test_validator.py, tests/translator/yaml_helper.py
* print() is a function in Python 3
* Replace instances of __basestring__ with __six.string_types__
=> Modernize Python 2 code to get ready for Python 3

versions/2016-10-31.md
*Description of changes:* If "Properties" is omitted the table properties set are ignored. Have just added this to the specification example to its clear its required. 
=> Updated Example: AWS::Serverless::SimpleTable to include Properties.

CONTRIBUTING.md, DEVELOPMENT_GUIDE.rst, Makefile
Added validation to the setup target and raise a clear error when pyenv is not found on your system.
Added a check if pyenv could be found on the developers system, if not display a better error describing the problem.
=> Added validation on make setup target

versions/2016-10-31.md
Add table of contents for easier navigation
Added table of contents to the specification for easier navigation
=> Add table of contents to the specification

examples/2016-10-31/policy_templates/all_policy_templates.yaml
No issue was raised, I just noticed this was missing. 
=> added missing RekognitionLabelsPolicy to all_policy_templates.yaml

samtranslator/policy_templates_data/policy_templates.json
*Issue #, if available: N/A
*Description of changes: Right now the RekognitionLabelsPolicy description is identical to that of RekognitionFacesPolicy. This (tiny) PR fixes this by giving RekognitionLabelsPolicy a more apt description.
=> doc(policy-template): fix RekognitionLabelsPolicy description

DESIGN.md
This will add an Overview section to the DESIGN.md file that explains how SAM works and the entry point into the code base. This is useful to help new people in being able to trace through the code base.
=> Update DESIGN.md to include an Overview and entry point for SAM

examples/2016-10-31/schedule/.gitignore, examples/2016-10-31/schedule/README.md
Fixes https://twitter.com/AWSbrett/status/1008038312349581312
Provide a brief overview of what's happening under the covers. Then, include instructions to package and deploy the application using the AWS SAM CLI.
=> Add README to scheduled application example

docs/safe_lambda_deployments.rst
Minor spelling and grammatical edits.
=> Spelling & Grammar

docs/safe_lambda_deployments.rst, examples/2016-10-31/schedule/.gitignore, examples/2016-10-31/schedule/README.md
Merged a doc PR direct to master by mistake. This merges it back into develop so we're not out of sync
=> chore: merge master to develop

HOWTO.md
Just a few minor rewords, plus a link to the sam-local-cli usage guide in the appropriate place.
=> Flow, link to sam-local CLI

examples/2016-10-31/schedule/README.md
Follow-up to PR 482. Linking to the deployment instructions on AWS docs for Lambda-based deployments because those are more descriptive.
=> Updating readme.md for the schedule example as a follow-up to PR 482

examples/2016-10-31/iot_backend/src/index.js
formatted code to avoid confusion in the example source code.
=> code formatted

README.md
Updated reference to SAM Local to AWS SAM CLI and the github link.
=> docs: Update reference for AWS SAM CLI

requirements/dev.txt
Update a testing dependency to fix the TravisCI build.
=> docs: update requirements to fix travis build

tests/translator/validator/test_validator.py
Missed a directory path change in https://github.com/awslabs/serverless-application-model/pull/576
=> ci: update test_validator.py

examples/apps/api-gateway-authorizer-nodejs/index.js, examples/apps/api-gateway-authorizer-python/lambda_function.py
https://github.com/awslabs/serverless-application-model/issues/521
API gateway authorizes insecure authentication token logging
=> API gateway authorizes insecure authentication token logging issue#521

setup.py
*Issue #, if available:* #609
Fixes #609. This will apply from the next release.
Cf https://github.com/aws/aws-xray-sdk-python/pull/101
=> Tell PyPI long_description is Markdown

docs/conf.py
Changes Sphinx theme to ReadtheDocs
=> Changes Sphinx theme to ReadtheDocs

requirements/dev.txt
=> chore: update dev.txt

README.md, tox.ini
Hey, Tom from Codecov here.  I thought it would be useful to add code coverage metrics to this repository. [Codecov](https://codecov.io) is a hosted code coverage provider with awesome features. You can checkout your first reports [here](https://codecov.io/gh/thomasrockhu/serverless-application-model).  I also updated the `README` with a coverage badge.
Codecov ❤️'s open source and will be free forever for OSS
=> Add Codecov coverage reports and add badge

versions/2016-10-31.md
Added how to make specific Functions public in case of global authorizer configured
=> Override Auth NONE

docs/globals.rst
*Issue #661 
Documentation fix
=> Add PermissionsBoundary to the list of supported globals in the docs.

versions/2016-10-31.md
=> Fixed Pseduo Param for Region in Layers sections

samtranslator/model/api/api_generator.py
Fix merge conflicts with the v1.10.0 release and develop.
=> chore: fix merge conflicts with v1.10.0 release

docs/website/requirements.txt, requirements/dev.txt
- Update dev dependency pyyaml to newer version
- Update doc dependencies requests and urllib3 to newer version
=> chore: upgrade dev and doc dependencies

examples/apps/api-gateway-multiple-origin-cors/package-lock.json, examples/apps/api-gateway-multiple-origin-cors/package.json
Update api-gateway-multiple-origin-cors example app dependencies
=> chore: Update api-gateway-multiple-origin-cors example app dependencies

docs/website/requirements.txt, examples/apps/api-gateway-multiple-origin-cors/package-lock.json, examples/apps/api-gateway-multiple-origin-cors/package.json
Merging latest master into release candidate branch.
=> Merge master into 1.10.0 RC

samtranslator/model/__init__.py
=> Fixed a typo

docs/policy_templates.rst
*Description of changes:*  Fixed two spelling mistakes in the documentation.
*Checklist:*
=> Fixed some spelling mistakes

docs/globals.rst
N/A
Small visual update
*Checklist:*
=> docs: update globals.rst

docs/website/requirements.txt
N/A
Update Jinja version
*Checklist:*
=> docs: update website requirements.txt

samtranslator/model/preferences/deployment_preference_collection.py, samtranslator/model/sam_resources.py, samtranslator/policy_templates_data/policy_templates.json, samtranslator/translator/translator.py, tests/translator/input/function_with_custom_codedeploy_deployment_preference.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-cn/function_with_custom_codedeploy_deployment_preference.json, tests/translator/output/aws-us-gov/all_policy_templates.json, tests/translator/output/aws-us-gov/function_with_custom_codedeploy_deployment_preference.json, tests/translator/output/function_with_custom_codedeploy_deployment_preference.json, tests/translator/test_function_resources.py, tests/translator/test_translator.py
N/A
Merging fixes made to the release/v1.12.0 branch back into develop
Tests updated and pass
*Checklist:*
=> chore: merge Release/v1.12.0 into develop

samtranslator/model/api/api_generator.py, tests/translator/input/api_request_model_openapi_3.yaml, tests/translator/output/api_request_model_openapi_3.json, tests/translator/output/aws-cn/api_request_model_openapi_3.json, tests/translator/output/aws-us-gov/api_request_model_openapi_3.json
=> Merge Master into Develop

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
#1063
Updated the policy template as described in the issue, and related tests.
Let me know if there is anything else I need to do!
Ensured that the tests worked, and tested by running `bin/sam-translate.py` on a test template yaml and manually checking the transformed template to ensure that the additional actions were present.
*Checklist:*
=> Feat: Add tag related permissions to S3FullAccess policy

samtranslator/model/api/api_generator.py, tests/translator/output/api_with_openapi_definition_body_no_flag.json, tests/translator/output/aws-cn/api_with_openapi_definition_body_no_flag.json, tests/translator/output/aws-us-gov/api_with_openapi_definition_body_no_flag.json
N/A
Merges a patch for v1.14.0 into the release branch
Tests updated, ran, and passed.
*Checklist:*
=> chore: merge #1093 into release/v1.14.0

versions/2016-10-31.md
There was a improper closing tag for ApiAuth yaml section.
*Checklist:*
=> docs: fix yaml code block for authorizers

examples/2016-10-31/cloudwatch-event-to-msteams/template.yaml, samtranslator/model/events.py, samtranslator/model/eventsources/push.py, samtranslator/validator/sam_schema/schema.json, tests/translator/input/cloudwatchevent.yaml, tests/translator/output/aws-cn/cloudwatchevent.json, tests/translator/output/aws-us-gov/cloudwatchevent.json, tests/translator/output/cloudwatchevent.json, versions/2016-10-31.md
=> feat: changes for eventbusname on cloudwatch event (#1185)

appveyor.yml
=> Add AppVeyor config to move away from Travis

examples/2016-10-31/policy_templates/all_policy_templates.yaml, samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
#1304 
Updated failed tests in develop
make pr
*Checklist:*
=> fix: update failing tests

tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
N/A
Fixes some failing tests
`make pr` runs and passes
*Checklist:*
=> chore: fix failing tests

README.md
#1163 
Found the link while reading the documentation of SAM
Clicked and link and signed myself up for getting a Slack invite.
*Checklist:*
- [N/A] Write/update tests
- [N/A] `make pr` passes
- [Y] Update documentation
- [N/A] Verify transformed template deploys and application functions as expected
- [N/A] Add/update example to `examples/2016-10-31`
=> Fix the SAM Slack Community link

samtranslator/translator/translator.py, tests/translator/output/aws-cn/intrinsic_functions.json, tests/translator/output/aws-us-gov/intrinsic_functions.json, tests/translator/output/intrinsic_functions.json
=> fix: function redploy parameters resolver fix

samtranslator/translator/translator.py
*Checklist:*
- [] Write/update tests
=> fix: add condition for ordered dictionary for redeploy api

samtranslator/model/cognito.py
=> fix: update type of user pool tags

tests/translator/input/http_api_explicit_stage.yaml, tests/translator/output/aws-cn/http_api_explicit_stage.json, tests/translator/output/aws-us-gov/http_api_explicit_stage.json, tests/translator/output/http_api_explicit_stage.json, versions/2016-10-31.md
N/A
Adds support for StageVariables for HttpApis.
Deployed to CFN.
*Checklist:*
=> feat: add support for StageVariables

samtranslator/model/sam_resources.py, tests/translator/input/function_with_alias_and_code_sha256.yaml
=> fix: ref for autopublish code sha

Makefile
N/A
Updates the Makefile to follow similar patterns as AWS Lambda Builders and SAM CLI do.
ran `make init` and `make pr` locally.
*Checklist:*
=> chore: Update makefile to be consistent with related SAM projects

README.md, requirements/base.txt
https://github.com/aws/serverless-application-model/issues/1692
Updated Slack Invite Link
N/A
*Checklist:*
*Examples?*
=> Fix: Updated Slack Invite Link

samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/apigateway.py, samtranslator/model/apigatewayv2.py, samtranslator/model/sam_resources.py, tests/translator/input/api_with_basic_custom_domain.yaml, tests/translator/input/api_with_basic_custom_domain_http.yaml, tests/translator/input/api_with_basic_custom_domain_intrinsics.yaml, tests/translator/input/api_with_basic_custom_domain_intrinsics_http.yaml, tests/translator/input/error_api_mtls_configuration_invalid_field.yaml, tests/translator/input/error_api_mtls_configuration_invalid_type.yaml, tests/translator/input/error_httpapi_mtls_configuration_invalid_field.yaml, tests/translator/input/error_httpapi_mtls_configuration_invalid_type.yaml, tests/translator/output/api_with_basic_custom_domain.json, tests/translator/output/api_with_basic_custom_domain_http.json, tests/translator/output/api_with_basic_custom_domain_intrinsics.json, tests/translator/output/api_with_basic_custom_domain_intrinsics_http.json, tests/translator/output/aws-cn/api_with_basic_custom_domain.json, tests/translator/output/aws-cn/api_with_basic_custom_domain_http.json, tests/translator/output/aws-cn/api_with_basic_custom_domain_intrinsics.json, tests/translator/output/aws-cn/api_with_basic_custom_domain_intrinsics_http.json, tests/translator/output/aws-us-gov/api_with_basic_custom_domain.json, tests/translator/output/aws-us-gov/api_with_basic_custom_domain_http.json, tests/translator/output/aws-us-gov/api_with_basic_custom_domain_intrinsics.json, tests/translator/output/aws-us-gov/api_with_basic_custom_domain_intrinsics_http.json, tests/translator/output/error_api_mtls_configuration_invalid_field.json, tests/translator/output/error_api_mtls_configuration_invalid_type.json, tests/translator/output/error_httpapi_mtls_configuration_invalid_field.json, tests/translator/output/error_httpapi_mtls_configuration_invalid_type.json, tests/translator/test_translator.py
=> feature: Support MTLS auth properties in REST and HTTP API domain names

samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py, tests/translator/input/error_resource_policy_not_dict.yaml, tests/translator/output/error_resource_policy_not_dict.json, tests/translator/test_translator.py
=> Fix: SAM Crashes Invalid swagger models exception

.pylintrc
=> chore: Remove biased language from pylintrc

versions/2016-10-31.md
#1861 
Update documentation related to MSK event source object
*Checklist:*
=> doc: Update doc related to MSK event source object

samtranslator/model/eventsources/pull.py, samtranslator/model/lambda_.py, tests/translator/input/function_with_event_source_mapping.yaml, tests/translator/output/aws-cn/function_with_event_source_mapping.json, tests/translator/output/aws-us-gov/function_with_event_source_mapping.json, tests/translator/output/function_with_event_source_mapping.json, versions/2016-10-31.md
Stream Analytics Support
*Checklist:*
=> feat: Stream Analytics

README.md
#1875
Update README Slack Invite link
*Checklist:*
*Examples?*
=> fix: Update Slack invite link

versions/2016-10-31.md
=> doc: Update doc related to MSK event source object (#1862)

requirements/dev.txt
update pyyaml package to get the latest security update
https://github.com/aws/serverless-application-model/security/dependabot/requirements/dev.txt/PyYAML/open
*Checklist:*
*Examples?*
=> chore: Upgrade PyYaml version to 5.4

samtranslator/model/api/api_generator.py
=> fix: remove explicit logging level set in single module

docs/safe_lambda_deployments.rst
https://github.com/aws/serverless-application-model/issues/2010
Removed in https://github.com/aws/serverless-application-model/pull/1634. Fixing to most recent commit. Better than broken.
*Checklist:*
*Examples?*
=> docs: fix dead link

samtranslator/feature_toggle/feature_toggle.py
=> Update AppConfig boto3 client config to shorten timeout

samtranslator/plugins/application/serverless_app_plugin.py
#2060 
Remove logging of service call response
*Checklist:*
*Examples?*
=> fix: Remove logging of SAR service call response

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Update PR Checklist to include writing intrinsic tests

samtranslator/model/eventsources/push.py, tests/translator/input/error_depends_on_invalid_types.yaml, tests/translator/output/error_depends_on_invalid_types.json
=> fix: Check DependsOn field type.

samtranslator/metrics/metrics.py, tests/metrics/test_metrics.py
*Issue #, if available:* n/a
Add a method to the metrics object to retrieve previously recorded metrics.  This can be used to derive per-request computed metrics.
Existing unit tests for the class pass.  Also added a new unit test for the new method.
*Checklist:*
=> Add method to retrieve previously-recorded metrics

samtranslator/model/eventbridge_utils.py, tests/model/eventsources/test_eventbridge_rule_source.py, tests/model/eventsources/test_schedule_event_source.py, tests/model/stepfunctions/test_eventbridge_rule_source.py, tests/model/stepfunctions/test_schedule_event.py, tests/translator/input/error_function_with_event_bridge_rule_dlq_intrinsic_function.yaml, tests/translator/input/error_function_with_schedue_dlq_intrinsic_function.yaml, tests/translator/input/error_state_machine_with_eb_dlq_generated_intrinsic_function.yaml, tests/translator/input/error_state_machine_with_schedule_dlq_generated_intrinsic_function.yaml, tests/translator/output/error_function_with_event_bridge_rule_dlq_intrinsic_function.json, tests/translator/output/error_function_with_schedue_dlq_intrinsic_function.json, tests/translator/output/error_state_machine_with_eb_dlq_generated_intrinsic_function.json, tests/translator/output/error_state_machine_with_schedule_dlq_generated_intrinsic_function.json
…ule events for lambda function and state machine resources
*Checklist:*
*Examples?*
=> Ensure that QueueLogicalId resolves to a string in case if it exist

.github/workflows/README.md, .github/workflows/pr-labeler.yml
n/a
PR auto labeler
Was also merged into SAM CLI's repo
*Checklist:*
*Examples?*
=> chore: Add auto PR labeler

integration/combination/test_api_with_disable_execute_api_endpoint.py, integration/resources/expected/combination/api_with_disable_execute_api_endpoint.json, integration/resources/templates/combination/api_with_disable_execute_api_endpoint.yaml, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/apigateway.py, samtranslator/model/sam_resources.py, samtranslator/swagger/swagger.py, samtranslator/validator/sam_schema/definitions/api.json
=> feat: adding OwnershipVerificationCertificateArn and DisableExecuteApiEndpoint to APIs. (#93)

samtranslator/model/eventsources/pull.py, samtranslator/model/lambda_.py, tests/translator/input/error_event_filtering.yaml, tests/translator/input/function_with_event_filtering.yaml, tests/translator/input/intrinsic_functions.yaml, tests/translator/output/aws-cn/function_with_event_filtering.json, tests/translator/output/aws-cn/intrinsic_functions.json, tests/translator/output/aws-us-gov/function_with_event_filtering.json, tests/translator/output/aws-us-gov/intrinsic_functions.json, tests/translator/output/error_event_filtering.json, tests/translator/output/function_with_event_filtering.json, tests/translator/output/intrinsic_functions.json, tests/translator/test_translator.py, versions/2016-10-31.md
=> feat: event source filtering

samtranslator/open_api/open_api.py, tests/translator/input/http_api_multiple_authorizers.yaml, tests/translator/output/aws-cn/http_api_multiple_authorizers.json, tests/translator/output/aws-us-gov/http_api_multiple_authorizers.json, tests/translator/output/http_api_multiple_authorizers.json, tests/translator/test_translator.py
=> fix: open api set_path_default_authorizer

samtranslator/open_api/open_api.py, tests/translator/input/http_api_multiple_authorizers.yaml, tests/translator/output/aws-cn/http_api_multiple_authorizers.json, tests/translator/output/aws-us-gov/http_api_multiple_authorizers.json, tests/translator/output/http_api_multiple_authorizers.json, tests/translator/test_translator.py
=> fix: open api set_path_default_authorizer (#2248)

versions/2016-10-31.md
Updated documentation for Domain configuration in API gateway
*Checklist:*
*Examples?*
=> Add security policy

.github/PULL_REQUEST_TEMPLATE.md, tests/model/api/test_http_api_generator.py
=> chore: Add checkbox for intrinsic validation changes

.github/PULL_REQUEST_TEMPLATE.md, tests/model/api/test_http_api_generator.py
=> chore: Update PR template wording

integration/config/region_service_exclusion.yaml, integration/single/test_basic_function.py
Update region ervice exclusion list and add code deploy skip condition for a code deploy test.
=> chore: [Foss] Sync public: Update region service exclusion list

integration/resources/expected/combination/api_with_custom_domains_edge.json, integration/resources/expected/combination/api_with_custom_domains_regional.json, integration/resources/expected/combination/api_with_custom_domains_regional_ownership_verification.json, integration/resources/expected/single/basic_api_with_tags.json
Add back hash verification for resources
=> chore: [Foss] Sync public: Add back hash verification

integration/resources/expected/combination/http_api_with_custom_domains_regional_ownership_verification.json, integration/resources/templates/combination/api_with_custom_domains_regional_ownership_verification.yaml
Update some resources(template, expected json file) for custom domain tests
=> fix: [Foss] Sync public: Update custom domain tests resource

integration/combination/test_api_with_authorizer_apikey.py, integration/combination/test_function_with_self_managed_kafka.py, integration/helpers/base_test.py
Reverts aws/serverless-application-model#2463
=> Revert "chore: Add missing import and add partition into base test for integration test"

.github/workflows/build.yml
=> chore: run tests with GitHub workflow

.pylintrc, integration/helpers/deployer/utils/artifact_exporter.py, requirements/dev.txt, samtranslator/feature_toggle/feature_toggle.py, samtranslator/metrics/method_decorator.py, samtranslator/model/connector_profiles/profile.py, samtranslator/model/preferences/deployment_preference_collection.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/policy_template_processor/processor.py, samtranslator/swagger/swagger.py, samtranslator/validator/validator.py, tests/policy_template_processor/test_processor.py
Pylint version upgraded. Enable more pylint rules and fix them.
All unit tests passed.
=> Upgrade Pylint Version and Fix Pylint Issues

README.md
=> docs: add SAM workshop, minor polish to README

.gitpod.yml, DEVELOPMENT_GUIDE.md
=> chore: add Gitpod config, docs polish

.github/PULL_REQUEST_TEMPLATE.md
=> chore: add development guidelines to checklist

.github/workflows/build.yml
=> ci: Allow build workflow to be triggered manually or by gh-cli

integration/resources/templates/single/state_machine_with_api.yaml
=> fix: correct URL suffix

bin/validate_schema.py, samtranslator/schema/schema.json, samtranslator/schema/schema.py
=> chore: add state machine events schema skeleton

bin/validate_schema.py, samtranslator/schema/schema.json, samtranslator/schema/schema.py
=> chore: add state machine schema types

bin/validate_schema.py, samtranslator/schema/schema.json, samtranslator/schema/schema.py, tests/translator/input/api_with_method_aws_iam_auth.yaml, tests/translator/input/eventbridgerule_with_retry_policy.yaml, tests/translator/input/function_with_disabled_traffic_hook.yaml, tests/translator/output/api_with_method_aws_iam_auth.json, tests/translator/output/aws-cn/api_with_method_aws_iam_auth.json, tests/translator/output/aws-cn/eventbridgerule_with_retry_policy.json, tests/translator/output/aws-cn/function_with_disabled_traffic_hook.json, tests/translator/output/aws-us-gov/api_with_method_aws_iam_auth.json, tests/translator/output/aws-us-gov/eventbridgerule_with_retry_policy.json, tests/translator/output/aws-us-gov/function_with_disabled_traffic_hook.json, tests/translator/output/eventbridgerule_with_retry_policy.json, tests/translator/output/function_with_disabled_traffic_hook.json
=> Add Schema Type to AWS::Serverless::Lambda

bin/validate_schema.py, samtranslator/schema/schema.json, samtranslator/schema/schema.py
https://github.com/aws/serverless-application-model/issues/1133
=> Add detailed type to AWS::Serverless::Api schema

samtranslator/schema/aws_serverless_api.py, samtranslator/schema/aws_serverless_function.py, samtranslator/schema/schema.json, tests/schema/test_validate_schema.py
=> Fix wrong types for schema

samtranslator/schema/schema.json, samtranslator/schema/schema.py
=> chore: add JSON schema version

samtranslator/schema/aws_serverless_api.py, samtranslator/schema/aws_serverless_function.py, samtranslator/schema/aws_serverless_httpapi.py, samtranslator/schema/aws_serverless_statemachine.py, samtranslator/schema/schema.json
- `Policies` consistent for state machine and function.
- Fix `Tracing` docs.
=> chore: schema fix and polish

DEVELOPMENT_GUIDE.md
=> docs: add section about schema changes

.github/workflows/build.yml
=> cr: Run build for all pull requests

.github/workflows/README.md
=> docs: remove outdated workflows readme

requirements/dev.txt, tests/schema/test_validate_schema.py
One fewer things to take care of. We already have code for parsing YAML.
=> chore: remove cfn-flip dep

requirements/base.txt
=> chore: update pydantic

MANIFEST.in
=> chore: Add schema related files to manifest

samtranslator/schema/common.py, tests/schema/test_validate_schema.py
=> fix: Fix schema related tests failed when WD is not project root

tests/translator/input/http_api_with_default_stage_name_and_fail_on_warnings.yaml, tests/translator/output/aws-cn/http_api_with_default_stage_name_and_fail_on_warnings.json, tests/translator/output/aws-us-gov/http_api_with_default_stage_name_and_fail_on_warnings.json, tests/translator/output/http_api_with_default_stage_name_and_fail_on_warnings.json
Adds baseline transform test for #2297 so that it's easier to see what changes after applying the to-be-done fix.
=> chore: add baseline transform test for issue #2297

Makefile
=> chore: disable cfn-lint check

.github/workflows/build.yml
Owners of feature branches might want to know their branch passes checks before a PR.
Syntax: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters
=> chore: run CI on feature branches

samtranslator/model/__init__.py, samtranslator/model/eventsources/scheduler.py, samtranslator/model/lambda_.py, samtranslator/model/sam_resources.py
=> Add typing and remove 'type: ignore' Part One

samtranslator/model/__init__.py, samtranslator/model/lambda_.py, samtranslator/model/s3_utils/uri_parser.py, samtranslator/model/sam_resources.py, samtranslator/translator/translator.py
=> Type Ignore Fixes Part Four

Makefile, samtranslator/policy_templates_data/schema.json
=> chore: Format other files in samtranslator/policy_templates_data

requirements/base.txt
=> chore: Loose pydantic version requirement

requirements/base.txt
=> chore: Loose pydantic version requirement ~1.10 -> ~1.8

Makefile, bin/add_docs_cfn_schema.py, bin/parse_docs.py
Now uses the (minimally altered) title from documentation, which maps nicely to the definition names in the schema.
=> fix(schema): more robust docs mapping

Makefile
Update schemas and split the operations into individual commands, easier for refactors to ensure no change.
```
make schema-all
```
The command names are a little confusing currently; will improve as I work on the update automation.
=> chore: update schema

Makefile
=> chore: use https to pull docs

.github/workflows/schema.yml
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
=> fix: workflow typo

.github/workflows/schema.yml
Ideally should link to the commits it used, but at least it's better than nothing.
https://github.com/hoffa/setup-sam/pull/8
=> ci: add schema update PR body

.github/workflows/schema.yml
Not entirely sure why it happens. See https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-609365407 for potential workarounds. Another is also removing required checks, but that's a no-go. So meanwhile this should help.
https://github.com/hoffa/setup-sam/pull/17
=> ci(schema): add PR checks workaround to description

requirements/dev.txt
=> chore: remove tox and flake8 dependency

.github/workflows/check_interface_compatibility.yml, bin/public_interface.py
I created another PR draft to test it: https://github.com/aws/serverless-application-model/pull/2878#issuecomment-1423485136
The test GH action run: https://github.com/aws/serverless-application-model/actions/runs/4130070494
=> ci: Add GH Action to detect compatibility breaking chages

requirements/dev.txt, ruff.toml, samtranslator/metrics/metrics.py, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/apigateway.py, samtranslator/model/apigatewayv2.py, samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/model/role_utils/role_constructor.py, samtranslator/model/sam_resources.py, samtranslator/model/stepfunctions/generators.py, samtranslator/open_api/open_api.py, samtranslator/plugins/api/implicit_api_plugin.py, samtranslator/plugins/api/implicit_http_api_plugin.py, samtranslator/plugins/api/implicit_rest_api_plugin.py, samtranslator/swagger/swagger.py, samtranslator/translator/transform.py, samtranslator/translator/translator.py, samtranslator/utils/py27hash_fix.py, samtranslator/validator/validator.py
=> chore: Upgrade ruff to 0.0.244

schema_source/schema.py, tests/schema/test_validate_schema.py, tests/translator/input/schema_validation_5.yaml, tests/translator/output/aws-cn/schema_validation_5.json, tests/translator/output/aws-us-gov/schema_validation_5.json, tests/translator/output/schema_validation_5.json
=> chore(schema): add `Connectors` resource attribute to CFN resources

samtranslator/model/sam_resources.py
=> fix: make MemorySize a pass-through

samtranslator/model/stepfunctions/resources.py
another scan following https://github.com/aws/serverless-application-model/pull/2934
=> Chore: another scan of replacing generated properties by GeneratedProperty()

pyproject.toml
=> chore: Replace py36 with py310 in black config

samtranslator/model/events.py, tests/translator/output/aws-cn/event_bridge_rule_super_long_id.json, tests/translator/output/aws-us-gov/event_bridge_rule_super_long_id.json, tests/translator/output/event_bridge_rule_super_long_id.json
=> fix: Remove logical id change for Events Rule

bin/sam-translate.py
=> chore: fix local transform format

.github/workflows/build.yml
=> ci: test on Python 3.11

.cfnlintrc.yaml, integration/combination/test_function_with_sns.py, integration/resources/templates/combination/function_with_sns_intrinsics.yaml, samtranslator/internal/schema_source/aws_serverless_function.py, samtranslator/model/eventsources/push.py, samtranslator/model/sns.py, samtranslator/validator/sam_schema/schema.json, schema_source/sam.schema.json, tests/model/eventsources/test_sns_event_source.py, tests/translator/input/function_with_sns_event_source_all_parameters.yaml, tests/translator/input/sns_existing_sqs.yaml, tests/translator/input/sns_intrinsics.yaml, tests/translator/input/sns_outside_sqs.yaml, tests/translator/input/sns_sqs.yaml, tests/translator/output/aws-cn/function_with_sns_event_source_all_parameters.json, tests/translator/output/aws-cn/sns_existing_sqs.json, tests/translator/output/aws-cn/sns_intrinsics.json, tests/translator/output/aws-cn/sns_outside_sqs.json, tests/translator/output/aws-cn/sns_sqs.json, tests/translator/output/aws-us-gov/function_with_sns_event_source_all_parameters.json, tests/translator/output/aws-us-gov/sns_existing_sqs.json, tests/translator/output/aws-us-gov/sns_intrinsics.json, tests/translator/output/aws-us-gov/sns_outside_sqs.json, tests/translator/output/aws-us-gov/sns_sqs.json, tests/translator/output/function_with_sns_event_source_all_parameters.json, tests/translator/output/sns_existing_sqs.json, tests/translator/output/sns_intrinsics.json, tests/translator/output/sns_outside_sqs.json, tests/translator/output/sns_sqs.json
=> chore: rebase feat-appsync

bin/add_transform_test.py
https://github.com/aws/serverless-application-model/pull/2998#issuecomment-1458996871
=> fix: Fix add transform test

.github/workflows/build.yml, .github/workflows/check_compatibility.yml, .github/workflows/codeql.yml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
Similar to https://github.com/aws/aws-sam-cli/pull/4836
=> ci: Trigger gh actions on merge group

samtranslator/internal/schema_source/aws_serverless_api.py, schema_source/sam.schema.json
=> chore: update schema docs

samtranslator/internal/schema_source/aws_serverless_application.py, samtranslator/internal/schema_source/aws_serverless_layerversion.py, samtranslator/internal/schema_source/aws_serverless_simpletable.py, schema_source/sam.schema.json
Pass-through schema types for LayerVersion, Application, and SimpleTable.
=> chore: more typed schema pass-throughs

samtranslator/internal/schema_source/aws_serverless_api.py, schema_source/sam.schema.json
Another pass typing schema pass-throughs.
=> chore: and more typed schema pass-throughs

DEVELOPMENT_GUIDE.md
=> docs: mention what transform tests are

.github/ISSUE_TEMPLATE/bug_report.md
To ensure we can categorize as necessary once we've investigated the issue.
=> docs: remove automatic type/bug label

integration/combination/test_connectors.py, integration/resources/expected/combination/connector_appsync_api_to_lambda.json, integration/resources/templates/combination/connector_appsync_api_to_lambda.yaml, samtranslator/model/connector/connector.py, samtranslator/model/connector_profiles/profiles.json, tests/translator/input/connector_appsync_api_to_lambda.yaml, tests/translator/output/aws-cn/connector_appsync_api_to_lambda.json, tests/translator/output/aws-us-gov/connector_appsync_api_to_lambda.json, tests/translator/output/connector_appsync_api_to_lambda.json
New Connector to allow easy creation of lambda authoriser
- transformation test
=> AppSync Api -> Lambda connector

DEVELOPMENT_GUIDE.md
I didn't find any place where error transforms were explained, so here it is.
=> docs: clarify success/failure transform tests

integration/ruff.toml, ruff.toml, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/eventsources/push.py, samtranslator/open_api/open_api.py, samtranslator/swagger/swagger.py, tests/ruff.toml
=> chore: Upgrade ruff to 0.0.269

integration/combination/test_graphqlapi_lambda_resolver.py, integration/resources/templates/combination/graphqlapi_lambda_resolver.yaml, integration/resources/templates/combination/graphqlapi_pipeline_resolver.yaml
=> chore: fix GraphQL integ tests

tests/translator/input/function_with_cw_event.yaml, tests/translator/output/aws-cn/function_with_cw_event.json, tests/translator/output/aws-us-gov/function_with_cw_event.json, tests/translator/output/function_with_cw_event.json
=> chore: add test with Function and CloudWatch event

Makefile
Schema automation was failing; `doc_source` was deleted from the default branch: https://github.com/awsdocs/aws-sam-developer-guide
Using explicit `main` until we switch to an alternative source.
```
make schema-all
```
=> chore: use explicit `main` branch for SAM docs

.cfnlintrc.yaml, samtranslator/model/sam_resources.py, tests/schema/test_validate_schema.py, tests/translator/input/function_with_tracing.yaml, tests/translator/output/aws-cn/function_with_tracing.json, tests/translator/output/aws-us-gov/function_with_tracing.json, tests/translator/output/function_with_tracing.json
Add more detailed transform tests covering different scenarios with `Tracing` properties on Function.
all tests passed
=> chore: Add transform tests with Tracing Properties

docs/schema.md
See https://github.com/aws/serverless-application-model/pull/3219
=> docs: update schema diagram

README.md
Might minimize the chance of missing failures (e.g. https://github.com/aws/serverless-application-model/pull/3217).
=> docs: add schema workflow badge

integration/resources/templates/combination/api_with_authorizer_apikey.yaml
Accidentally forgot this change during [this pr](https://github.com/aws/serverless-application-model/pull/3286)
=> fix: fix integ test

integration/combination/test_connectors.py
=> chore: remove pdb in integration test

integration/combination/test_connectors.py
=> chore: Make a function to eventbus connect test non-blocking

integration/resources/templates/combination/api_with_authorizers_min.yaml, integration/resources/templates/combination/connector_bucket_to_function_write.yaml, integration/resources/templates/combination/connector_event_rule_to_eb_default_write.yaml, integration/resources/templates/combination/connector_sfn_to_sqs_write.yaml, integration/resources/templates/combination/function_with_alias_and_event_sources.yaml, integration/resources/templates/combination/function_with_all_event_types.yaml, integration/resources/templates/combination/function_with_cloudwatch_log.yaml
Add deletion policy and update replace policy to tests to make sure resources are deleted when tests failed.
All tests pass.
=> Add UpdateReplacePolicy and DeletionPolicy to Integ Test Resoruces

.github/workflows/close_issue_message.yml
None
We received some customer feedback in the AWS SDKs that our default closed issue message was too impolite. This message is slightly nicer. This PR is merely a suggestion; please discard it if you'd like.
This is a minor change. I only edited text, and did not validate in any other way.
=> chore: a more polite closed issue message

.github/dependabot.yml, CODEOWNERS
=> Chore(owner): Add tooling to codeowner

samtranslator/region_configuration.py, samtranslator/translator/arn_generator.py, tests/translator/test_arn_generator.py, tests/unit/test_region_configuration.py, tests/unit/translator/test_arn_generator.py
Adding new aws partition to our code
https://github.com/aws/serverless-application-model/pull/3564
=> chore: add new partition
