versions/2016-10-31.md
A literal dash '-' in regexp character class must be at beginning or end or escaped to avoid meaning character range.
=> Remove regexp character class ambiguity

versions/2016-10-31.md
Quick fix in the docs that is explained in this Issue: https://github.com/awslabs/serverless-application-model/issues/16
=> Fixed typo as in 'FunctionArn' to 'Arn'

examples/2016-10-31/api_backend/index.js
`data.Item` is not available within the scope of the error handler. I've replaced it with the doc ID being requested instead.
=> fix error handler in GET request handler

examples/2016-10-31/hello_world/template.yaml
Keyword **Ref** is required in templates to refer to values from Parameters or Resources.
=> fix: missing Ref in intrinsic function call

examples/2016-10-31/api_swagger_cors/swagger.yaml
An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: [/Resources/ApiGatewayApi/Properties/DefinitionBody/paths//api/networth/options/responses] map keys must be strings; received numeric [200] instead
=> Fix CORS template to use '200' instead of 200

versions/2016-10-31.md
Hi!
I just spent quite a while trying to understand how I could control the status code of my response when using a `Serverless::Function`.
I have added a sentence to the relevant piece of documentation to more clearly state that the return value from the function is constructed into a response object. This documentation would have saved me a few hours of pain, so hopefully this will help future users with the same question.
This does not appear to be documented clearly in any other location, but if it is, please point me in the right direction.
If you desire for this change to be made in a different format or in a different place, let me know and I will do so.
Thanks!
😺 🌮
=> Elaborate on setting status code when using lambda as API

examples/2016-10-31/lambda_edge/README.md, examples/2016-10-31/lambda_edge/index.js, examples/2016-10-31/lambda_edge/template.yaml
This PR adds a Lambda@Edge sample to ease the deployment task and facilitate further deployments that will automatically update Cloudfront configuration with the latest Lambda Function Version without any manual steps.
It leverages the new [Safe Deployments](https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst) feature to accomplish it.
=> Adds sample template and sample code for Lambda@Edge

docs/safe_lambda_deployments.rst
The IAM role CodeDeployServiceRole is created with this default policy that allows running the hook functions:
```
{
"Action": [
"lambda:InvokeFunction"
],
"Resource": "arn:aws:lambda:*:*:function:CodeDeployHook_*",
"Effect": "Allow"
}
```
Naming the hook functions as per the current docs prefixed just with`CodeDeploy_` would not match the policy so the CodeDeploy Deployment would not be able to run the hook. I tested and, as expected, it works fine when the hook functions are prefixed with `CodeDeployHook_`.
=> Fix docs reference about hooks naming convention

docs/cloudformation_compatibility.rst, docs/faq.rst, docs/index.rst
As suggested by @jfuss here is an initial stab at an FAQ section for the docs.
Currently contains only a couple of questions - how to deal with multiple environments/stages, and how to enable logs in gateway.
Let me know if this useful in its present form or whether the official recommendations are different from what I thought.
=> Add FAQ section to docs

docs/cloudformation_compatibility.rst
docs/cloudformation_compatibility.rst was out of date based on Release 1.4.0. This PR is to update those docs to include the recent changes.
=> Update cloudformation_compatibility based on Release 1.4.0

examples/2016-10-31/implicit_api_settings/template.yaml, versions/2016-10-31.md
*Description of changes:* Small documentation update, pointing out the use of `~1` on `BinaryMediaTypes`.
=> Added note about ~1 on BinaryMediaTypes, punctuation cleanup

README.md
Readme.md said "To creating a serverless application using SAM"
Changed it to "To create a serverless application using SAM"
=> fixing a typo in readme.md

docs/policy_templates_data/policy_templates.json, samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
N/A
* Adding the new AWSSecretsManagerRotationPolicy PolicyTemplate with tests.
* Updated PolicyTemplate Docs to include all new Templates that can be consumed.
=> Add new AWSSecretsManagerRotationPolicy PolicyTemplate with docs update

docs/policy_templates.rst
These links were broken in the documentation at https://awslabs.github.io/serverless-application-model/policy_templates.html
That's because they were relative links that didn't exist within the documentation website.
* OLD (Doesn't exist): https://awslabs.github.io/serverless-application-model/policy_templates_data/policy_templates.json
* NEW: https://github.com/awslabs/serverless-application-model/blob/develop/docs/policy_templates_data/policy_templates.json
There might be a more generic way to do this across all the documentation, but I don't know enough about Sphinx to do it generically.
=> Update links to Policy Templates for documentation

requirements/base.txt, requirements/dev.txt
Requirements file lists transitive dependencies of boto3 and not the own dependencies. This makes pip install fail in several of my machines because older version of these libraries were already installed.
`boto3`: Many users might have this library already available in thier
Python installation from installing the AWS CLI. We use boto3 in
only one place, which is to get the region_name from `boto3.session.Session`
which hasn't changed since 2016. Updating the requirement to depend on
boto3 >=1.5.0 allows us to be compatible with existing installations that
might already have an older version of boto3
`botocore, docutils, futures, jmespath, python-dateutil, s3transfer`: These
packages are not used in the SAM translator but come as a …
=> Removing unnecessary dependencies from requirements file

docs/safe_lambda_deployments.rst
Link is missing the `/src` dir prefix, leading to 404.
=> doc: fix preTrafficHook link at lambda_safe_deployment

docs/cloudformation_compatibility.rst, docs/globals.rst, samtranslator/model/dynamodb.py, samtranslator/model/sam_resources.py, samtranslator/plugins/globals/globals.py, samtranslator/plugins/globals/globals_plugin.py, samtranslator/validator/sam_schema/schema.json, tests/translator/input/globals_for_simpletable.yaml, tests/translator/input/simple_table_ref_parameter_intrinsic.yaml, tests/translator/input/simpletable_with_sse.yaml, tests/translator/output/aws-cn/globals_for_simpletable.json, tests/translator/output/aws-cn/simple_table_ref_parameter_intrinsic.json, tests/translator/output/aws-cn/simpletable_with_sse.json, tests/translator/output/aws-us-gov/globals_for_simpletable.json, tests/translator/output/aws-us-gov/simple_table_ref_parameter_intrinsic.json, tests/translator/output/aws-us-gov/simpletable_with_sse.json, tests/translator/output/error_globals_unsupported_type.json, tests/translator/output/globals_for_simpletable.json, tests/translator/output/simple_table_ref_parameter_intrinsic.json, tests/translator/output/simpletable_with_sse.json, tests/translator/test_translator.py, tests/translator/validator/test_validator.py, versions/2016-10-31.md
Closes #376 
Adding optional [SSE](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html) to `AWS::Serverless::SimpleTable`.  See #376 for more info.
=> Add SSE to SimpleTable

docs/policy_templates_data/policy_templates.json, samtranslator/policy_templates_data/policy_templates.json
*Issue #, if available:* no issue
*Description of changes:* I've created two new policy templates in support of Kinesis Firehose use. For my own use case, I just need the FirehoseWritePolicy, which I am currently constructing manually in my SAM template. As this is my first real contribution to the repo, I am open to any changes you think are appropriate to make it fit.
=> Add FirehoseWritePolicy and FirehoseCrudPolicy

samtranslator/plugins/api/implicit_api_plugin.py, samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py, tests/translator/input/function_with_event_api.yaml, tests/translator/input/function_with_event_api_keyRequired.yaml, tests/translator/output/aws-cn/function_with_event_api.json, tests/translator/output/aws-cn/function_with_event_api_keyRequired.json, tests/translator/output/aws-us-gov/function_with_event_api.json, tests/translator/output/aws-us-gov/function_with_event_api_keyRequired.json, tests/translator/output/function_with_event_api.json, tests/translator/output/function_with_event_api_keyRequired.json, tests/translator/test_translator.py, versions/2016-10-31.md
addresses part of #248
Adds ApiKeyRequired to the API Event Properties. If this approach looks good, it might be useful to also add this at the global level.
=> feat(implicit-api): add support for ApiKeyRequired

samtranslator/model/eventsources/push.py, tests/translator/output/api_with_cors.json, tests/translator/output/aws-cn/api_with_cors.json, tests/translator/output/aws-cn/implicit_api.json, tests/translator/output/aws-cn/implicit_api_with_serverless_rest_api_resource.json, tests/translator/output/aws-us-gov/api_with_cors.json, tests/translator/output/aws-us-gov/implicit_api.json, tests/translator/output/aws-us-gov/implicit_api_with_serverless_rest_api_resource.json, tests/translator/output/implicit_api.json, tests/translator/output/implicit_api_with_serverless_rest_api_resource.json
*Issue #, if available:* #59 
*Description of changes:* Convert the `ANY` method to a wildcard `*` when generating permission ARNs
I did not add test templates because this change is already covered by existing tests.
=> Fix ANY method ARN generation using wildcard

samtranslator/parser/parser.py
Log a warning on invalid schema validation.
=> fix: log a warning on invalid schema validation

samtranslator/model/sam_resources.py, samtranslator/validator/sam_schema/schema.json, tests/model/test_sam_resources.py, tests/translator/input/basic_function.yaml, tests/translator/output/aws-cn/basic_function.json, tests/translator/output/aws-us-gov/basic_function.json, tests/translator/output/basic_function.json, tests/translator/output/error_function_no_codeuri.json, versions/2016-10-31.md
#287 
Adds support for ZipFile lambda definitions
Due to the nature of 'allOf', the schema cannot enforce 'additionalProperties: false' with the current schema approach.
=> add support for InlineCode in AWS::Serverless::Function

examples/2016-10-31/sqs/template.yaml, samtranslator/model/eventsources/pull.py, tests/translator/output/aws-cn/sqs.json, tests/translator/output/aws-us-gov/sqs.json, tests/translator/output/sqs.json
=> fix(event-source): set correct SQS role and fix example template

docs/safe_lambda_deployments.rst
Show example of Cloudwatch alarms in Cloudformation that relate the safe deployments. These are not easy to find online and will help people jumpstart the process of getting this going.
=> updating safe_lambda_deployment.rst to include example Cloudwatch alarms for safe deployment usage

samtranslator/model/eventsources/push.py, tests/translator/input/s3_with_dependsOn.yaml, tests/translator/output/aws-cn/s3_with_dependsOn.json, tests/translator/output/aws-us-gov/s3_with_dependsOn.json, tests/translator/output/s3_with_dependsOn.json, tests/translator/test_translator.py
DependsOn values can be either scalar strings or lists of strings. This
change fixes handling when an S3 bucket in an input template has a
scalar string value for DependsOn.
=> Fix handling scalar DependsOn values of S3 buckets

examples/apps/lambda-canary-python3/template.yaml
This canary doesn't need access to DynamoDB.
Avoid unnecessary dependency on DynamoDB.
=> Remove Dependency on DynamoDB

samtranslator/policy_templates_data/policy_templates.json
Adding the AWSSecretsManagerGetSecretValuePolicy policy to grant secretsmanager:GetSecretValue permissions to a single secret ARN.
=> Adding AWSSecretsManagerGetSecretValuePolicy

bin/sam-translate.py, samtranslator/model/api/api_generator.py, samtranslator/plugins/api/default_definition_body_plugin.py, samtranslator/translator/translator.py, tests/plugins/api/test_default_definition_body_plugin.py, tests/translator/input/api_with_cors_no_definitionbody.yaml, tests/translator/output/api_with_cors_no_definitionbody.json, tests/translator/output/aws-cn/api_with_cors_no_definitionbody.json, tests/translator/output/aws-us-gov/api_with_cors_no_definitionbody.json, tests/translator/output/error_api_invalid_definitionuri.json, tests/translator/test_translator.py
This makes DefinitionBody and DefinitionUri optional, and if not provided then the API will use the Swagger generated by SAM. This makes it easy for users who rely on Implicit API to use the existing Cors feature and upcoming Authorizers feature by defining an explicit API resource without needing to redefine their entire Swagger
=> feat(plugins): added DefaultDefinitionBody plugin

docs/globals.rst
Fixes a grammar mistake in the docs that implies that items in resource lists are added to the global list.
=> docs: fix grammar in globals.rst

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
Closes https://github.com/awslabs/serverless-application-model/issues/389
`PutJobFailureResult` & `PutJobSuccessResult` do not support resource-level permissions and require you to choose All resources.
> You specify the actions in the policy's Action field, and you specify a wildcard character (*) as the resource value in the policy's Resource field.
https://docs.aws.amazon.com/codepipeline/latest/userguide/permissions-reference.html
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. 👍
=> fix: Fix resource for CodePipelineLambdaExecutionPolicy policy template

samtranslator/parser/parser.py
The schema is currently lacking and therefore is just noise. We may add this back in the future or remove it entirely.
*Issue #535, if available:*
=> fix: remove JSON Schema validation warning

examples/2016-10-31/hello_world_vpc/README.md, examples/2016-10-31/hello_world_vpc/src/index.js, examples/2016-10-31/hello_world_vpc/template.yaml
*Issue #, if available:* Issue created in SAM CLI: https://github.com/awslabs/aws-sam-cli/issues/617
Adds a hello world VPC example to demonstrate how to add correct permissions for Lambda VPC enabled using SAM Policy Templates including link to the docs for other examples.
=> docs: add hello world example with VPCConfig

examples/apps/cloudfront-modify-response-header/template.yaml, examples/apps/cloudwatch-logs-process-data/template.yaml, examples/apps/cloudwatch-logs-to-loggly/template.yaml, examples/apps/cognito-sync-trigger/template.yaml, examples/apps/datadog-process-rds-metrics/template.yaml, examples/apps/inspector-scheduled-run/template.yaml, examples/apps/lex-book-trip-python/template.yaml, examples/apps/lex-book-trip/template.yaml, examples/apps/lex-make-appointment-python/template.yaml, examples/apps/lex-make-appointment/template.yaml, examples/apps/lex-order-flowers-python/template.yaml, examples/apps/lex-order-flowers/template.yaml, examples/apps/logicmonitor-send-cloudwatch-events/template.yaml, examples/apps/s3-get-object-python/template.yaml, examples/apps/s3-get-object-python3/template.yaml, examples/apps/s3-get-object/template.yaml, examples/apps/slack-echo-command-python/template.yaml, examples/apps/slack-echo-command/template.yaml, examples/apps/splunk-elb-application-access-logs-processor/template.yaml, examples/apps/splunk-elb-classic-access-logs-processor/template.yaml, examples/apps/splunk-logging/template.yaml
This fixes the parameter definition from a yaml string to a yaml object in example apps template.
*Tests*
Ran ```aws cloudformation package``` and ```aws cloudformation deploy``` succesfully
=> Fix parameter definition in example apps template

versions/2016-10-31.md
https://github.com/awslabs/serverless-application-model/issues/544
Added option of `PRIVATE` for the endpoint configuration in the docs.
=> docs: update API EndpointConfiguration options

samtranslator/model/eventsources/push.py, samtranslator/model/lambda_.py, tests/translator/input/alexa_skill_with_skill_id.yaml, tests/translator/output/alexa_skill_with_skill_id.json, tests/translator/output/aws-cn/alexa_skill_with_skill_id.json, tests/translator/output/aws-us-gov/alexa_skill_with_skill_id.json, tests/translator/test_translator.py
N/A
Allows users to optionally specify their skill ID when configuring an AlexaSkillEvent on a function. This will validate that the Lambda is called [by the expected skill](https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-an-aws-lambda-function.html#use-aws-cli) and is strongly recommended by Alexa.
I am open to changing the name to match the underlying CF property (EventSourceToken), but given this property must be the skill ID in this application I think this is a more sensible abstraction.
=> Expose skill ID for event source validation with skills

tests/translator/test_translator.py
Instead of using relative paths for these test files (which only works if the tests are run from the expected (base) directory of this repository), the paths were updated to use the full file path.
=> ci: update tests to use full path for files

requirements/base.txt
Fix Installation of aws-sam-translator using python3.7 when trying to do a vanilla install without using any previously built binaries.
enum34 Issue: https://bitbucket.org/stoneleaf/enum34/issues/21/setuppy-should-no-op-for-python-34
Command to use under a python 3.7 virtualenv
```
pip install -v --no-binary :all: --ignore-installed .
```
=> fix: conditionally install enum34 based on python version

samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
Add DynamoDBReconfigurePolicy which grants the user access to dynamo db:UpdateTable
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTable.html
#614 
Added DynamoDBReconfigurePolicy, which grants dynamodb:Update
=> Add DynamoDBReconfigurePolicy

requirements/dev.txt
`nose` isn't needed as a dependency anymore. I'm going to look into removing `parameterized` in the future as well.
*Issue #, if available:* #628 
*Description of changes:* Removed nose as a dependency.
=> Removed nose from dev requirements.

docs/internals/generated_resources.rst, docs/safe_lambda_deployments.rst, samtranslator/model/preferences/deployment_preference.py
*Description of changes:* Documented the hidden role parameter for DeploymentPreference so a custom CodeDeploy role ARN can be passed in
=> documented role parameter for DeploymentPreference

examples/apps/rekognition-python/template.yaml, examples/apps/s3-get-object-python/template.yaml, examples/apps/s3-get-object-python3/template.yaml, examples/apps/s3-get-object/template.yaml
#618 
Modified examples to create and grant read access to S3 Buckets created, these examples now can work out of the box. Needed to use !Sub and Prefix to get around circular dependency issues.
Based solution on method described [here](https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-circular-dependency-cloudformation/)
=> Fix s3 examples

docs/globals.rst, samtranslator/model/api/api_generator.py, samtranslator/model/apigateway.py, samtranslator/model/sam_resources.py, samtranslator/plugins/globals/globals.py, tests/translator/input/api_with_access_log_setting.yaml, tests/translator/input/api_with_canary_setting.yaml, tests/translator/output/api_with_access_log_setting.json, tests/translator/output/api_with_canary_setting.json, tests/translator/output/aws-cn/api_with_access_log_setting.json, tests/translator/output/aws-cn/api_with_canary_setting.json, tests/translator/output/aws-us-gov/api_with_access_log_setting.json, tests/translator/output/aws-us-gov/api_with_canary_setting.json, tests/translator/output/error_globals_api_with_stage_name.json, tests/translator/test_translator.py, versions/2016-10-31.md
#612 
Added samtranslator support for AccessLogSetting and CanarySetting to Api Gateway.
Translator tests updated.
=> Add Access log and canary setting support to templates.

docs/safe_lambda_deployments.rst
The current example configuration for `LatestVersionErrorMetricGreaterThanZeroAlarm` will always be in "Insufficient Data" state with no data if invoking against the 'live' alias as described in the guide.  This change fixes the alarm to point to the 'live' alias and the ExecutedVersion dimension.
=> docs: fix 'latest version' alarm in safe deployments guide

docs/cloudformation_compatibility.rst, docs/globals.rst, samtranslator/model/api/api_generator.py, samtranslator/model/apigateway.py, samtranslator/model/sam_resources.py, samtranslator/plugins/globals/globals.py, samtranslator/validator/sam_schema/schema.json, tests/translator/input/api_with_xray_tracing.yaml, tests/translator/output/api_with_xray_tracing.json, tests/translator/output/aws-cn/api_with_xray_tracing.json, tests/translator/output/aws-us-gov/api_with_xray_tracing.json, tests/translator/output/error_globals_api_with_stage_name.json, tests/translator/test_translator.py, versions/2016-10-31.md
CloudFormation recently got the ability to enable active tracing with X-Ray for API Gateway stages. This PR adds that ability to `AWS::Serverless::Api`.
I hope I updated it in all necessary places, including documentation etc., but if I didn't, please just tell me where it's missing and I'll update the PR accordingly. :smiley: 
Fixes #581
=> Add support for X-Ray to AWS::Serverless::Api

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
The read-only policy should also allow indexes to be used. This is an extension of #620 
*Description of changes:* Added explicit access to GSIs in the `DynamoDBReadPolicy` template.
=> Add GSIs to DynamoDBReadPolicy

samtranslator/plugins/application/serverless_app_plugin.py
The SAR client should only be initialized if a) it is passed into the plugin or b) it is necessary for the transform. Otherwise, SAM shouldn't worry about setting up the client.
=> fix: initialize the the sar boto3 client only if it's needed

samtranslator/model/s3.py, tests/translator/input/s3_multiple_functions.yaml, tests/translator/output/aws-cn/s3_multiple_functions.json, tests/translator/output/aws-us-gov/s3_multiple_functions.json, tests/translator/output/s3_multiple_functions.json
This is not an ideal situation- needing to update this resource with every single new feature. We should consider a way to update our underlying design so we don't need to continually update these resources, but let them pass through parameters to CFN.
https://github.com/awslabs/serverless-application-model/issues/679
Add missing `PublicAccessBlockConfiguration` parameter to S3 buckets
=> fix: add missing parameter to s3 bucket resource

samtranslator/model/eventsources/pull.py, samtranslator/validator/sam_schema/schema.json, tests/translator/input/sqs.yaml, tests/translator/input/streams.yaml, tests/translator/output/aws-cn/sqs.json, tests/translator/output/aws-cn/streams.json, tests/translator/output/aws-us-gov/sqs.json, tests/translator/output/aws-us-gov/streams.json, tests/translator/output/sqs.json, tests/translator/output/streams.json, versions/2016-10-31.md
Issue #669 
Added Enabled boolean option for SQS, DynamoDB and Kinesis events.
Updated documentation to show support for this property addition.
Modified translator tests to verify that cloudformation templates generate with Enabled as part of AWS::Lambda::EventSourceMapping.
=> Event source disabled

examples/2016-10-31/lambda_sns_filter_policy/README.md, examples/2016-10-31/lambda_sns_filter_policy/src/index.js, examples/2016-10-31/lambda_sns_filter_policy/template.yaml, samtranslator/model/__init__.py, samtranslator/model/eventsources/push.py, samtranslator/model/intrinsics.py, samtranslator/model/sam_resources.py, samtranslator/model/sns.py, samtranslator/validator/sam_schema/schema.json, tests/model/eventsources/test_cloudwatchlogs_event_source.py, tests/model/eventsources/test_sns_event_source.py, tests/translator/input/function_with_condition.yaml, tests/translator/input/function_with_sns_event_source_all_parameters.yaml, tests/translator/input/s3_with_condition.yaml, tests/translator/output/aws-cn/function_with_condition.json, tests/translator/output/aws-cn/function_with_sns_event_source_all_parameters.json, tests/translator/output/aws-cn/s3_with_condition.json, tests/translator/output/aws-us-gov/function_with_condition.json, tests/translator/output/aws-us-gov/function_with_sns_event_source_all_parameters.json, tests/translator/output/aws-us-gov/s3_with_condition.json, tests/translator/output/function_with_condition.json, tests/translator/output/function_with_sns_event_source_all_parameters.json, tests/translator/output/s3_with_condition.json, tests/translator/test_translator.py, tests/translator/validator/test_validator.py, versions/2016-10-31.md
*Issue #142 *
- added "Condition" to the _supported_resource_attributes of Resource
- SamFunction now passes attributes to constructor of LambdaFunction in _construct_lambda_function with the accepted attribute values of the source
- added test case in test_translator.py (plus one input and three outputs) that checks "Condition" being created
This is my first PR, I know there is still work to do:
- the passing of the attributes should also work for other SamResourceMacro's
- The "Condition" attribute should also be put on other resources created on behalf of this one
=> Condition handling (for issue #142)

samtranslator/model/dynamodb.py, samtranslator/model/sam_resources.py, tests/translator/output/aws-cn/depends_on.json, tests/translator/output/aws-cn/globals_for_simpletable.json, tests/translator/output/aws-cn/simple_table_with_extra_tags.json, tests/translator/output/aws-cn/simple_table_with_table_name.json, tests/translator/output/aws-cn/simpletable.json, tests/translator/output/aws-cn/simpletable_with_sse.json, tests/translator/output/aws-us-gov/depends_on.json, tests/translator/output/aws-us-gov/globals_for_simpletable.json, tests/translator/output/aws-us-gov/simple_table_with_extra_tags.json, tests/translator/output/aws-us-gov/simple_table_with_table_name.json, tests/translator/output/aws-us-gov/simpletable.json, tests/translator/output/aws-us-gov/simpletable_with_sse.json, tests/translator/output/depends_on.json, tests/translator/output/globals_for_simpletable.json, tests/translator/output/simple_table_with_extra_tags.json, tests/translator/output/simple_table_with_table_name.json, tests/translator/output/simpletable.json, tests/translator/output/simpletable_with_sse.json, versions/2016-10-31.md
*Issue #696 *
Made BillingMode: PAY_PER_REQUEST default for AWS::Serverless::SimpleTable
Adjusted 6 test cases (x3=18 for all regional tests)
Added the default to the documentation
=> BillingMode: PAY_PER_REQUEST default #696

samtranslator/model/sam_resources.py, tests/translator/input/basic_application.yaml, tests/translator/input/basic_layer.yaml, tests/translator/output/aws-cn/basic_application.json, tests/translator/output/aws-cn/basic_layer.json, tests/translator/output/aws-us-gov/basic_application.json, tests/translator/output/aws-us-gov/basic_layer.json, tests/translator/output/basic_application.json, tests/translator/output/basic_layer.json
*Issue #142 *
Pass passtrhough_resource_attributes when processing LayerVersion and Application
=> Passing Condition to new LayerVersion and Application for #142

samtranslator/model/__init__.py, samtranslator/model/sam_resources.py, tests/translator/input/layers_with_intrinsics.yaml, tests/translator/output/aws-cn/layers_with_intrinsics.json, tests/translator/output/aws-us-gov/layers_with_intrinsics.json, tests/translator/output/layers_with_intrinsics.json
https://github.com/awslabs/serverless-application-model/issues/703
Support reading intrinsics in LayerName, LicenseInfo, and Description
=> fix: layer logical ids now change when referenced parameters change

versions/2016-10-31.md
Adding missed resource `Type` in the documentation example for Nested Apps.
=> Add `Type: AWS::Serverless::Application` to the 2016-10-31.md 

README.md, examples/2016-10-31/image_resize_golang/README.md, examples/2016-10-31/image_resize_golang/main.go, examples/2016-10-31/image_resize_golang/template.yaml
**Description of changes**: This PR shows how to use aws sam to develop application that will trigger lambda function written in Go on S3 events like image upload.
=> Add example on how to use S3 events for lambda functions written in Go using sam

samtranslator/model/eventsources/cloudwatchlogs.py, samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, tests/translator/input/function_event_conditions.yaml, tests/translator/output/aws-cn/function_event_conditions.json, tests/translator/output/aws-cn/s3_with_condition.json, tests/translator/output/aws-us-gov/function_event_conditions.json, tests/translator/output/aws-us-gov/s3_with_condition.json, tests/translator/output/function_event_conditions.json, tests/translator/output/s3_with_condition.json, tests/translator/test_translator.py
#142 
Adds another test for Conditions, as well as makes sure they are added to all Event types (except for API). Will follow up with a fix (or detailed error for the meantime) for Conditions for API event types.
=> fix: add conditions to events and add tests

samtranslator/model/eventsources/push.py, tests/model/eventsources/test_api_event_source.py
*Issue #, if available:* #665
Adds a regex sub to remove the trailing slash from the path of the Api event source
=> fix: Removes trailing slashes from APIGW permissions

versions/2016-10-31.md
The current s3 link in the example implies that you must have RegionName in the url for an Application Resource's Location. This will give you an error implying that you are trying to use an application from the serverless application repository which is confusing.
=> Fix s3 link in application docs example

DEVELOPMENT_GUIDE.rst
Minor documentation fix - developer guide had a few markdown-style code blocks, but it is restructured-text. Updated to use correct `code-block::` directives.
Renders in github as follows:
=> Documentation: Code block formatting fixes

docs/globals.rst
CodeUri in Globals seems to be supported by at least sam-cli 0.6.1, making the comment about it being unsupported obsolete.
Remove comment about CodeUri being unsupported in Globals
=> Remove comment about CodeUri being unsupported in Globals

examples/2016-10-31/lambda_edge/README.md
This PR makes it clearer to a reader looking for Lambda@Edge examples that a custom IAM role is required without the user needing to look deeper into the `stack.yml` file. 
=> Lambda@Edge Role Required

docs/policy_templates.rst
Fixed small typo "availbale" -> "available"
=> Fixed small typo "availbale" -> "available"

samtranslator/plugins/api/implicit_api_plugin.py, tests/plugins/api/test_implicit_api_plugin.py
#766 
Handle key error from missing event keys.
*Checklist:*
=> fix: catch error caused by improper event configuration

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
SAR policy template was missing UpdateApplication operation. Added that and also new ListApplicationDependencies API.
make pr passes. Verified new actions against [this docs page](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-api-permissions-ref.html).
*Checklist:*
- [ x ] Write/update tests
- [ x ] `make pr` passes
- n/a Update documentation - [This page](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/using-aws-sam.html#serverlessrepo-read-write-access-policy) will need to be updated, but only after release.
=> fix(policy-templates): Add more actions to ServerlessRepoReadWriteAccessPolicy

samtranslator/model/sam_resources.py, tests/model/test_sam_resources.py, tests/translator/input/function_with_alias.yaml, tests/translator/output/aws-cn/function_with_alias.json, tests/translator/output/aws-us-gov/function_with_alias.json, tests/translator/output/function_with_alias.json, versions/2016-10-31.md
[#823](https://github.com/awslabs/serverless-application-model/issues/823l)
This PR Add an Additional `VersionDescription` property on Serverless::Function.  
I validated the changes by creating an instance of `SamFunction` and then setting the `VersionDescription` property of the instance. after this i called the `to_cloudformation` method of `SamFunction` and validated that the string passed in `VersionDescription` is proprly set on the instance of `LambdaVersion` class under `Description` property.
*Checklist:*
- [ x] Write/update tests
- [ x] `make pr` passes
=> Added VersionDescription property on  Serverless::Function

samtranslator/intrinsics/actions.py, samtranslator/translator/translator.py, tests/intrinsics/test_actions.py, tests/translator/input/layers_with_intrinsics.yaml, tests/translator/output/aws-cn/layers_with_intrinsics.json, tests/translator/output/aws-us-gov/layers_with_intrinsics.json, tests/translator/output/layers_with_intrinsics.json, tests/translator/test_translator.py
Support `Ref: 'AWS::Region'`
Added unit tests and end-to-end tests
*Checklist:*
=> feat: support Ref: 'AWS::Region'

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
Added /* to resource to fix Unauthorized error for es:ESHttpPost action.
Created a custom policy and tested to remove unauthorized error.
```yaml
Policies:
- Statement:
- Effect: Allow
Action:
- es:ESHttpPost
Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/*'
#- ElasticsearchHttpPostPolicy: 
```
*Checklist:*
=> Fix ElasticsearchHttpPostPolicy

samtranslator/intrinsics/actions.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/translator/translator.py, tests/intrinsics/test_actions.py, tests/intrinsics/test_resolver.py, tests/plugins/application/test_serverless_app_plugin.py, tests/translator/input/application_with_intrinsics.yaml, tests/translator/output/application_with_intrinsics.json, tests/translator/output/aws-cn/application_with_intrinsics.json, tests/translator/output/aws-us-gov/application_with_intrinsics.json, tests/translator/test_translator.py
- Add FindInMap action
- Support intrinsics in serverless app plugin to resolve ApplicationId and SemanticVersion under Location
Added unit tests and end to end tests
*Checklist:*
=> feat: Add support for FindInMap in serverless app plugin

docs/globals.rst, samtranslator/plugins/globals/globals.py, tests/translator/input/globals_for_function.yaml, tests/translator/output/aws-cn/globals_for_function.json, tests/translator/output/aws-us-gov/globals_for_function.json, tests/translator/output/error_globals_unsupported_property.json, tests/translator/output/globals_for_function.json
*Issue #, if available:* #760
*Description of changes:* Added "ReservedConcurrentExecutions" to the list of supported global properties for the AWS::Serverless::Function resource. PR also includes updates to relevant tests and an update to the Globals support doc.
=> Feat/func/add ReservedConcurrentExecutions to globals

examples/2016-10-31/api_swagger_cors/swagger.yaml
When integrating API Gateway with Lambda, "httpMethod" in swagger.yaml should be "POST" when defining API method is not POST.
It is kind to let the reader know it, because some people misunderstood it.
see https://forums.aws.amazon.com/thread.jspa?messageID=745275
NA
Add comment on "swagger.yaml" in "examples/2016-10-31/api_swagger_cors"
Open edited "swagger.yaml" with https://editor.swagger.io/ and it have no error about edited lines.
*Checklist:*
- [na] Write/update tests
- [na] `make pr` passes
=> Noting "httpMethod" attribute is for lambda call

examples/apps/cloudfront-ab-test/package.json, examples/apps/cloudfront-access-request-in-response/package.json, examples/apps/cloudfront-http-redirect/package.json, examples/apps/cloudfront-modify-querystring/package.json, examples/apps/cloudfront-modify-response-header/package.json, examples/apps/cloudfront-multiple-remote-calls-aggregate-response/package.json, examples/apps/cloudfront-redirect-on-viewer-country/package.json, examples/apps/cloudfront-response-generation/package.json, examples/apps/cloudfront-simple-remote-call/package.json
It looks like the algorithmia-blueprint package.json was copied across several example apps for no good reason. 
These example apps do not have any dependencies(and of course they don't depend on `algorithmia`) so it's best to delete those package.json
*Checklist:*
=> docs: Delete misplaced package.json in several example apps

examples/2016-10-31/lambda_safe_deployments/src/preTrafficHook.js, examples/2016-10-31/lambda_safe_deployments/src/safeTest.js, examples/2016-10-31/lambda_safe_deployments/template.yaml
n/a
PreTrafficHook example now uses NodeJS 8.10 runtime
=> example [lambda_safe_deployments] use nodejs8.10 for the PreTraffic hook

docs/globals.rst
N/A
Add Auth to API globals docs. It is supported in the code: https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/plugins/globals/globals.py#L42
*Checklist:*
=> docs: add Auth to supported Api Global properties

DEVELOPMENT_GUIDE.rst
(DEVELOPMENT_GUIDE): change --input-file to --template-file
(DEVELOPMENT_GUIDE): change --output-file to --output-template
=> (DEVELOPMENT_GUIDE): fix typo for input and output file parameter

versions/2016-10-31.md
It would be useful to have an example of a filter
*Checklist:*
=> Add S3 filter example

samtranslator/sdk/resource.py, tests/translator/input/error_function_with_invalid_condition_name.yaml, tests/translator/output/error_function_with_invalid_condition_name.json, tests/translator/test_translator.py
*Issue #892 :*
*Internal transform failure on bad Condition syntax:*
*Checklist:*
=>  Added fix for Internal transform failure on bad Condition syntax

samtranslator/model/sam_resources.py, tests/translator/input/error_function_invalid_event_type.yaml, tests/translator/output/error_function_invalid_event_type.json
#915
handle Attribute error in sam_resources to return a 4xx error for invalid event type in function
Added tests for bad event type and ran make pr.
*Checklist:*
=> fix: invalid event type error

tests/translator/test_translator.py
N/A
Exclude some additional warnings from cfn-lint
Tests run/pass
*Checklist:*
=> chore: update test_translator.py

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
N/A
Updates StepFunctionsExecutionPolicy to work in different partitions
Issue found while testing other partitions
*Checklist:*
=> fix: partitionalize arn in StepFunctionsExecutionPolicy

samtranslator/policy_templates_data/schema.json
For example, in https://travis-ci.org/awslabs/serverless-application-model/jobs/538917819:
```
/home/travis/build/awslabs/serverless-application-model/.tox/py36/lib/python3.6/site-packages/jsonschema/validators.py:893: DeprecationWarning: The metaschema specified by $schema was not found. Using the latest draft to validate, but this will raise an error in the future.
cls = validator_for(schema)
```
From the warning message, I think specifying the latest draft of jsonschema keeps the current behavior in samtranslator. Currently the latest draft is draft-07.
Run the test suite.
*Checklist:*
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Fix a deprecation warning from jsonschema 3.x

samtranslator/model/api/api_generator.py, samtranslator/swagger/swagger.py, tests/translator/input/api_with_binary_media_types_definition_body.yaml, tests/translator/output/api_with_binary_media_types.json, tests/translator/output/api_with_binary_media_types_definition_body.json, tests/translator/output/aws-cn/api_with_binary_media_types.json, tests/translator/output/aws-cn/api_with_binary_media_types_definition_body.json, tests/translator/output/aws-us-gov/api_with_binary_media_types.json, tests/translator/output/aws-us-gov/api_with_binary_media_types_definition_body.json, tests/translator/test_translator.py
Related Issues: #566 #553 #561
=> fix: fix API Binary Media Types update issue

samtranslator/model/preferences/deployment_preference_collection.py, samtranslator/model/sam_resources.py, samtranslator/translator/translator.py, tests/translator/input/function_with_custom_codedeploy_deployment_preference.yaml, tests/translator/output/aws-cn/function_with_custom_codedeploy_deployment_preference.json, tests/translator/output/aws-us-gov/function_with_custom_codedeploy_deployment_preference.json, tests/translator/output/function_with_custom_codedeploy_deployment_preference.json, tests/translator/test_function_resources.py
N/A
Supports `Fn::FindInMap` and other intrinsics for the new custom CodeDeploy configurations feature
Tests updated and pass
*Checklist:*
=> fix: fix bug in custom DeploymentPreference feature

.travis.yml, DEVELOPMENT_GUIDE.rst, tox.ini
Also updates Travis build to test against Python 3.7.
*Issue #, if available:* #945 
*Description of changes:* Update development guide's list of supported versions. Add python 3.7 to Travis build.
*Description of how you validated changes:* Travis build against this PR should validate the changes.
*Checklist:*
=> docs: update supported python versions

samtranslator/plugins/__init__.py
N/A
InvalidDocumentExceptions were being logged as uncaught exceptions. This removes this unnecessary logging.
`make pr` ran and passed. Travis is running.
*Checklist:*
=> fix: do not log InvalidDocumentException as an uncaught error

.github/PULL_REQUEST_TEMPLATE.md, versions/2016-10-31.md
just a small typo
*Checklist:*
=> typo in 2016-10-31.md

versions/2016-10-31.md
Documentation improvement: stating in the `DefinitionUri` section that intrinsic functions are not supported in the external Swagger files. 
=> Adds to documentation intrinsic functions are not working in external swagger files

samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
*Issue:* 
Fixes #974 
Removed unused CollectionId parameter of RekognitionFacesPolicy (policy template)
- `make test`: passed all tests
- verified transformed template in the steps written in [DEVELOPMENT_GUIDE](https://github.com/awslabs/serverless-application-model/blob/master/DEVELOPMENT_GUIDE.rst#verifying-transforms)
using this SAM template
```
Resources:
HogeFugaFunction:
Properties:
CodeUri: src/hogefuga/
Handler: app.lambda_handler
Policies:
- RekognitionFacesPolicy: {}
```
I executed the commands below:
```
aws cloudformation package --template-file MY_TEMPLATE_PATH/template.yaml --output-template-file output-template.yaml --s3-bucket MY_S3_BUCKET
bin/sam-translate.py …
```
=> Remove unused CollectionId parameter of RekognitionFacesPolicy

samtranslator/model/eventsources/push.py, samtranslator/model/sns.py, samtranslator/validator/sam_schema/schema.json, tests/model/eventsources/test_sns_event_source.py, tests/translator/input/function_with_sns_event_source_all_parameters.yaml, tests/translator/output/aws-cn/function_with_sns_event_source_all_parameters.json, tests/translator/output/aws-us-gov/function_with_sns_event_source_all_parameters.json, tests/translator/output/function_with_sns_event_source_all_parameters.json, versions/2016-10-31.md
#105 
Add support to specify a SNS topic that belongs to a different region.
I made changes in the steps written in the issue below:
https://github.com/awslabs/serverless-application-model/issues/105#issuecomment-476771718
I verified transformed template in the steps written in [DEVELOPMENT_GUIDE](https://github.com/awslabs/serverless-application-model/blob/master/DEVELOPMENT_GUIDE.rst#verifying-transforms).
I confirmed that SAM template below could be deployed successfully.
```yaml
Resources:
WorkerFunction:
Properties:
CodeUri: worker_lambda/
Handler: app.lambda_handler
Events:
MessageTopic:
Type: SNS
Properties:
Topic: (different region TopicArn)
Region: …
```
=> Add support to specify a SNS topic that belongs to a different region

samtranslator/model/eventsources/push.py
#1017 
I'm sorry if I was wrong but I understand CloudWatch Events trigger is no pull event. 
So I think docstrings of `to_cloudformation` of CloudWatchEvent class and Schedule class have to fix.
- [-] Write/update tests
- [-] `make pr` passes
- [-] Verify transformed template deploys and application functions as expected
- [-] Add/update example to `examples/2016-10-31`
=> fix: to_cloudformation functions of PushEventSource class docstrings

HOWTO.md
=> docs: add missing backslash to bash commands

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
Include es:ESHttpPut action in ElasticsearchHttpPostPolicy Template
*Issue #1010 
Add es:ESHttpPut action  available in Policy Template List as part of ElasticsearchHttpPostPolicy template.
*Checklist:*
=> Add es:ESHttpPut in ElasticsearchHttpPostPolicy

requirements/dev.txt
* py is a dependency of pytest, and apparently it's not imported directly in this project
* requests is used in examples only
*Checklist:*
- This is a minor change so I skip these steps.
=> Refine requirements/dev.txt

examples/2016-10-31/api_aws_iam_auth/template.yaml, samtranslator/swagger/swagger.py, tests/translator/input/api_with_aws_iam_auth_overrides.yaml, tests/translator/output/api_with_aws_iam_auth_overrides.json, tests/translator/output/aws-cn/api_with_aws_iam_auth_overrides.json, tests/translator/output/aws-us-gov/api_with_aws_iam_auth_overrides.json, versions/2016-10-31.md
#923 
Allows invoke role override (removes the "credentials" field as discussed in #923)
Verified that the transformed template removes the "credentials" section when InvokeRole is set to 'None' or null. Also deployed template to CFN to verify that "Invoke with caller credentials" and "execution role" were not set on the api method.
I also attempted to make it more explicit that `CALLER_CREDENTIALS` is the default value, due to a conversation in the above issue.
*Checklist:*
=> fix: allow setting InvokeRole to NONE or null

requirements/dev.txt, tests/translator/test_translator.py
#1008 
Removes cfn-lint test dependency
Tests run and pass
*Checklist:*
=> Remove cfn lint

samtranslator/model/eventsources/push.py, tests/model/eventsources/test_api_event_source.py, tests/translator/input/api_with_path_parameters.yaml, tests/translator/output/api_with_path_parameters.json, tests/translator/output/aws-cn/api_with_path_parameters.json, tests/translator/output/aws-us-gov/api_with_path_parameters.json, tests/translator/test_translator.py
#110
fix the issue #110
Deployed the following template successfully on CloudFormation.
Also I confirmed deployed APIs works well.
```yaml
Resources:
HelloWorldFunction:
Properties:
CodeUri: hello_world/
Handler: app.lambda_handler
Events:
HttpGetUserExampleExample:
Type: Api
Properties:
Path: '/users/example/example'
Method: GET
HttpGetUserGroupIdUserId:
Type: Api
Properties:
Path: '/users/{groupId}/{userId}'
Method: GET
HttpGetGroupAster:
Type: Api
Properties:
Path: '/groups/{proxy+}'
Method: GET
```
*Checklist:*
- **If this pull request is on the right path, I will add some tests**
By submitting this pull request, I confirm that my contribution is made under …
=> fix: "Invalid permissions on Lambda function" on path parameter

examples/2016-10-31/api_cognito_auth/package.json, examples/2016-10-31/api_cognito_auth/template.yaml
none 
- `region` and `stack-name` of api_cognito_auth example was hard corded.
- when I create stack on us-west-2 region, `npm run open-login-page` command returns wrong login-page.
- when I create stack named hoge, `npm run configure-cognito-user-pool` command fails.
- I fixed hard corded region and stack-name parameters in package.json
After I run the commands below, I verified the example worked well.
- npm run package-deploy 
- npm run configure-cognito-user-pool
*Checklist:*
- [-] Write/update tests
- [-] `make pr` passes
- [-] Update documentation
- [-] Verify transformed template deploys and application functions as expected
- [-] Add/update example to `examples/2016-10-31`
By submitting …
=> fix: hard corded region and stack name of api_cognito_auth example

samtranslator/model/sam_resources.py, tests/translator/input/error_table_primary_key_missing_name.yaml, tests/translator/input/error_table_primary_key_missing_type.yaml, tests/translator/output/error_table_primary_key_missing_name.json, tests/translator/output/error_table_primary_key_missing_type.json, tests/translator/test_translator.py
#884
Add validation to `AWS::Serverless::SimpleTable` to make sure `Name` and `Type` exists as a property of `PrimaryKey`
Added tests
*Checklist:*
- [-] Update documentation
- [-] Verify transformed template deploys and application functions as expected
- [-] Add/update example to `examples/2016-10-31`
=> fix: make sure Name and Type exists as a property of PrimaryKey of SimpleTable

samtranslator/plugins/application/serverless_app_plugin.py, tests/translator/input/error_null_application_id.yaml, tests/translator/output/error_null_application_id.json, tests/translator/test_translator.py
#1053
Please refer to https://github.com/awslabs/serverless-application-model/issues/1053
add test
*Checklist:*
- [-] Update documentation
- [-] Verify transformed template deploys and application functions as expected
- [-] Add/update example to `examples/2016-10-31`
=> fix: make sure ApplicationId is not null

docs/safe_lambda_deployments.rst, examples/2016-10-31/lambda_safe_deployments/template.yaml
Fixes: #452
It seems like the pretraffic hook policies in the safe lambda deployment examples don’t work as expected. When just using the ARN instead of the ARN+version the example works.
=> docs: fix policy in safe deployments example and documentation

examples/2016-10-31/iot_backend/template.yaml
#1058
Updated function event properties to remove 'AwsIotSqlVersion' property. Also removed key: id from Table as it will be auto created. Updated to nodejs10.x
sam validate -t template.yaml
*Checklist:*
- [na ] Write/update tests
=> Fixed iot_backend example

samtranslator/model/eventsources/push.py, tests/translator/input/api_with_default_aws_iam_auth_and_no_auth_route.yaml, tests/translator/output/api_with_default_aws_iam_auth_and_no_auth_route.json, tests/translator/output/aws-cn/api_with_default_aws_iam_auth_and_no_auth_route.json, tests/translator/output/aws-us-gov/api_with_default_aws_iam_auth_and_no_auth_route.json, tests/translator/test_translator.py
*Issue #1014*
Change the validation of `method_authorizer` to support the combination of `AWS_IAM` default authorizer and `NONE` method authorizer.
When using `AWS_IAM` permission, it is only specified in the `DefaultAuthorizer`.  [Reference](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api-auth-object). This is a special case which leads to the `api_authorizers` being empty and results to not being able to add
```
Auth:
Authorizer: 'NONE'
```
to a specific function, in order to override the default authorizer and make the function public.
*Checklist:*
=> Fix Authorizer: NONE support with AWS_IAM authorizer

examples/2016-10-31/api_lambda_request_auth/template.yaml
Your SAM Description says this is the "API Gateway with Lambda Token Authorizer" when, I believe, this is a Request Authorizer. Your API resource FunctionPayloadType says "REQUEST" and the link below seems to be the Token Authorizer example.
https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_lambda_token_auth/template.yaml
*Checklist:*
=> Request Authorizer, not Token Authorizer

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
#1071
add ssm:GetParametersByPath to SSMParameterReadPolicy
- make pr
- verified transformed template in the steps written in DEVELOPMENT_GUIDE
using this SAM template
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
Function:
Runtime: python3.7
Resources:
HelloWorldFunction:
Properties:
CodeUri: worker/
Handler: app.lambda_handler
Policies:
- SSMParameterReadPolicy:
ParameterName: '*'
```
Then I got expected transformed template like this:
```json
{
"PolicyName": "HelloWorldFunctionRolePolicy0", 
"PolicyDocument": {
"Statement": [
{
"Action": [
"ssm:DescribeParameters"
], 
"Resource": "*", 
"Effect": "Allow"
}, 
{ …
```
=> feat: add ssm:GetParametersByPath to SSMParameterReadPolicy

samtranslator/model/cloudformation.py, samtranslator/model/sam_resources.py, tests/translator/input/application_with_intrinsics.yaml, tests/translator/output/application_with_intrinsics.json, tests/translator/output/aws-cn/application_with_intrinsics.json, tests/translator/output/aws-us-gov/application_with_intrinsics.json
#1087 
Allow `!Ref` and other intrinsics in `NotificationARNs` property of a Serverless::Application.
Tests updated and pass. Deployed a template with desired changes.
*Checklist:*
=> fix: allow intrinsics in NotificationARNs property

docs/cloudformation_compatibility.rst, docs/internals/generated_resources.rst, examples/2016-10-31/api_cognito_auth/template.yaml, samtranslator/model/cognito.py, samtranslator/model/eventsources/push.py, samtranslator/translator/verify_logical_id.py, samtranslator/validator/sam_schema/schema.json, tests/translator/input/cognito_userpool_with_event.yaml, tests/translator/input/error_cognito_userpool_duplicate_trigger.yaml, tests/translator/output/aws-cn/cognito_userpool_with_event.json, tests/translator/output/aws-us-gov/cognito_userpool_with_event.json, tests/translator/output/cognito_userpool_with_event.json, tests/translator/output/error_cognito_userpool_duplicate_trigger.json, tests/translator/test_translator.py, versions/2016-10-31.md
*Issue #229, if available:*
Added support for Cognito event sources
It adds only one Permission per Lambda (logical_id de-dupe)
It changes to LambdaConfig property of the Cognito UserPool it refers to
Updated the example "examples/2016-10-31/api_cognito_auth"
Transformed and created stack in my account
Checked is PreSignUp trigger correctly refers to the Lambda
*Checklist:*
other todos:
=> feat: Cognito event sources #229

versions/2016-10-31.md
In the prose of the description for `PrimaryKey`, the default key name is said to be "ID". In the examples and in the translator tests, the default value is "id".
May no one else be bitten by this.
In short, I made the normative and descriptive texts match.
- Changed "ID" to "`id`" in the prose of the specification. This is a non-normative change, as the specified default is in the "Primary Key Object" section -- and it matches the normative value anyway.
- Added text specifying the default `Type` value. (`String`) This one _is_ a normative change, but it's adding something to the specification text which was already specified.
I checked the values in the normative part of the specification and the output of the …
=> docs: Clarify `AWS::Serverless::SimpleTable.PrimaryKey` Default Value

samtranslator/plugins/__init__.py, samtranslator/plugins/application/serverless_app_plugin.py
N/A
When catching some exceptions that cause a crash in `sam validate`, I noticed that stack traces where still being printing to console from the CLI. This is due to the translator using the root logger in some cases. Best practice is to use a scoped logger (to the module), so that users can set the logging how they wish (in our case not print stack traces to console from the cli). This PR addresses two spots in the codebase that where still using the root logger. This has no impact to logging within the translator (in the cloud), since it only changes what logger is used.
`make pr`
*Checklist:*
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> fix: Use scoped logger instead of root

versions/2016-10-31.md
cherry-picking resource policy docs in
*Checklist:*
=> docs: add resource policy to spec docs (#1103)

samtranslator/model/api/api_generator.py, samtranslator/plugins/globals/globals.py, samtranslator/swagger/swagger.py, samtranslator/translator/translator.py, tests/translator/input/api_request_model_openapi_3.yaml, tests/translator/input/api_with_open_api_version.yaml, tests/translator/input/error_api_with_invalid_open_api_version_type.yaml, tests/translator/output/api_request_model_openapi_3.json, tests/translator/output/aws-cn/api_request_model_openapi_3.json, tests/translator/output/aws-us-gov/api_request_model_openapi_3.json, tests/translator/output/error_api_with_invalid_open_api_version.json, tests/translator/output/error_api_with_invalid_open_api_version_type.json, tests/translator/test_translator.py
I am seeing tons of errors where SAM is bailing when the template defines openapi without the quotes. 
Modified existing tests to remove the quotes from openapiversion value, and the output does not change.
*Checklist:*
=> fix: openapiversion bails if it is not a string

samtranslator/model/api/api_generator.py, samtranslator/model/eventsources/push.py, tests/translator/input/api_with_incompatible_stage_name.yaml, tests/translator/output/api_with_incompatible_stage_name.json, tests/translator/output/aws-cn/api_with_incompatible_stage_name.json, tests/translator/output/aws-us-gov/api_with_incompatible_stage_name.json, tests/translator/test_translator.py
*Issue #1002*
("-") is not accepted in CFn logical ID, but the stage name of API Gateway and Lambda permission may include ("-").  I changed the way to generate logical ID by logical_id_generator.
I tried the following template, and it worked.
And I also added E2E tests.
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HelloWorld
Resources:
MyAPI:
Type: "AWS::Serverless::Api"
Properties:
StageName: test_test
HelloWorld:
Properties:
Handler: index.handler
Runtime: nodejs10.x
CodeUri: s3://xxx/xxx
Description: HelloWorld
MemorySize: 128
Timeout: 3
Events:
GetResource:
Type: Api
Properties:
Path: /hello
Method: get
RestApiId: !Ref MyAPI
``` …
=> fix: randomize logical IDs of API stage and Lambda permission

setup.py
In Arch Linux, we build [python-aws-sam-translator](https://www.archlinux.org/packages/community/any/python-aws-sam-translator/) package from sources. Before this change, test files are installed:
```
$ python setup.py install --root=arch-pkgdir
$ ls arch-pkgdir/usr/lib/python3.7/site-packages/tests
intrinsics  model  plugins  policy_template_processor  sdk  swagger  translator
```
This is a problem as the directory `/usr/lib/python3.7/site-packages/tests` conflicts with other packages.
After this change, there are no longer test files
```
$ python setup.py install --root=arch-pkgdir
$ ls arch-pkgdir/usr/lib/python3.7/site-packages
aws_sam_translator-1.15.0-py3.7.egg-info  samtranslator
``` …
=> chore: actually exclude test files from being installed

CONTRIBUTING.md
N/A
CONTRIBUTING.md contained a link to an non-existing Github repository. Changed it to this repo.
Both links work now.
*Checklist:*
=> Fix link to Github issues in CONTRIBUTING.md

versions/2016-10-31.md
Make it clear that the property MethodSettings is a list.
=> Updated MethodSettings from API Gateway

samtranslator/swagger/swagger.py, tests/translator/input/api_with_resource_policy.yaml, tests/translator/output/api_with_resource_policy.json, tests/translator/output/aws-cn/api_with_resource_policy.json, tests/translator/output/aws-us-gov/api_with_resource_policy.json
Custom statements are being generated once each for every path in the api causing regression in the sam generated api swagger.
Check for copies when appending to list.
unit test
*Checklist:*
=> fix: custom statements regression bug 

examples/2016-10-31/cloudwatch-event-to-msteams/template.yaml, samtranslator/model/events.py, samtranslator/model/eventsources/push.py, samtranslator/validator/sam_schema/schema.json, tests/translator/input/cloudwatchevent.yaml, tests/translator/output/aws-cn/cloudwatchevent.json, tests/translator/output/aws-us-gov/cloudwatchevent.json, tests/translator/output/cloudwatchevent.json, versions/2016-10-31.md
#1067
Add field `EventBusName` to events that are triggers to functions
Changes the input yaml and output CFN Templates to make sure it was put correctly. Even though it is supporting the "EventBridge" service the field is called ["EventBusName" on the rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Events.html)
*Checklist:*
=> Changes for EventBusName on CW Event

README.md
[#1163](https://github.com/awslabs/serverless-application-model/issues/1163)
added a new slack invite link
checked if the new link is redirecting to the correct page
*Checklist:*
=> fix slack channel link

versions/2016-10-31.md
N/A
Add documentation for a property that was missed.
*Checklist:*
=> docs: document the OpenApiVersion property

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
Added the `dynamodb:ConditionCheckItem` action to the DynamoDBCrudPolicy template to allow use of the conditional check item on transactional writes
Deployed a SAM application using  the template and verified it could preform all the actions on a table in the existing template
*Checklist:*
=> Updated DynamoDBCrudPolicy

examples/2016-10-31/sns_sqs/README.md
fix sns publish.  was using sqs.  from `aws sqs send-message` to `aws sns publish`
*Checklist:*
=> fix sns publish

examples/2016-10-31/policy_templates/all_policy_templates.yaml, samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
#1186 
Added KMSEncryptPolicy policy template following the similar KMSDecryptPolicy template and updated related tests.
Validated via "make pr" command and checking transformed template.
*Checklist:*
=> Added KMSEncryptPolicy policy template and related test changes

versions/2016-10-31.md
*Issue #, if available:* #1172 
=> [docs] fix CORS documentation regarding API Gateway literal values

versions/2016-10-31.md
*Issue #, if available:* #7
The reasoning given in #7 was that we wanted to mirror CFN documentation which has since been updated to reference OpenAPI.
=> docs: change references to Swagger to OpenAPI

docs/safe_lambda_deployments.rst, examples/2016-10-31/lambda_safe_deployments/template.yaml, samtranslator/model/sam_resources.py, samtranslator/sdk/parameter.py, tests/sdk/test_parameter.py, tests/translator/input/function_with_deployment_preference_all_parameters.yaml, tests/translator/input/function_with_deployment_preference_multiple_combinations.yaml, tests/translator/input/function_with_disabled_deployment_preference.yaml, tests/translator/test_function_resources.py, tests/translator/test_translator.py, versions/2016-10-31.md
Add intrinsic support for Serverless::Function.DeploymentPreference.Enabled
Added intrinsics for Serverless::Function.DeploymentPreferences.Enabled. It now supports Fn::If, Fn::FindInMap, !Ref, etc.
Wrote/updated unit tests validating the changes. Tested changes with a production template to verify changes manually.
*Checklist:*
=> Add intrinsic support for Serverless::Function.DeploymentPreference.Enabled

examples/2016-10-31/lambda_safe_deployments/template.yaml, samtranslator/model/codedeploy.py, samtranslator/model/preferences/deployment_preference.py, samtranslator/model/preferences/deployment_preference_collection.py, tests/translator/input/function_with_deployment_preference_all_parameters.yaml, tests/translator/model/preferences/test_deployment_preference.py, tests/translator/output/aws-cn/function_with_deployment_preference_all_parameters.json, tests/translator/output/aws-us-gov/function_with_deployment_preference_all_parameters.json, tests/translator/output/function_with_deployment_preference_all_parameters.json, versions/2016-10-31.md
*Issue #, if available:* #955 
*Description of changes:* Add support for trigger configurations on deployment preference resources.
*Description of how you validated changes:* Unit tests, test translate & deploy with a simple template making use of the new TriggerConfig parameter in DeploymentConfig.
*Checklist:*
=> feat: Add support for TriggerConfigurations in DeploymentConfiguration

examples/2016-10-31/custom_domains_with_route53/README.md, examples/2016-10-31/custom_domains_with_route53/template.yaml, samtranslator/model/api/api_generator.py, samtranslator/model/apigateway.py, tests/translator/input/api_with_custom_domain_route53.yaml, tests/translator/output/api_with_basic_custom_domain.json, tests/translator/output/api_with_basic_custom_domain_intrinsics.json, tests/translator/output/api_with_custom_domain_route53.json, tests/translator/output/aws-cn/api_with_basic_custom_domain.json, tests/translator/output/aws-cn/api_with_basic_custom_domain_intrinsics.json, tests/translator/output/aws-cn/api_with_custom_domain_route53.json, tests/translator/output/aws-us-gov/api_with_basic_custom_domain.json, tests/translator/output/aws-us-gov/api_with_basic_custom_domain_intrinsics.json, tests/translator/output/aws-us-gov/api_with_custom_domain_route53.json, versions/2016-10-31.md
Found an issue where we don't support using the distribution supported by apigateway for custom domains.
validated end to end
*Checklist:*
=> fix: adding support to point to api gateway distribution 

samtranslator/swagger/swagger.py
N/A
I found some typos during I was working on another issue on GitHub.
So I fixed it.
*Checklist:*
- ~Write/update tests~
- ~Update documentation~
- ~Verify transformed template deploys and application functions as expected~
- ~Add/update example to `examples/2016-10-31`~
=> chore: typo in swagger.py

tests/translator/output/api_with_swagger_authorizer_none.json, tests/translator/output/aws-cn/api_with_swagger_authorizer_none.json, tests/translator/output/aws-us-gov/api_with_swagger_authorizer_none.json
N/A
- Fixed failed tests
- The function role tag propagation feature was introduced by #1194
- Three tests did not correspond with this
- So I fixed it
*Checklist:*
- ~Update documentation~
- ~Verify transformed template deploys and application functions as expected~
- ~Add/update example to `examples/2016-10-31`~
=> fix: failed tests

versions/2016-10-31.md
N/A
fix a cognito event source example
N/A
*Checklist:*
- ~Write/update tests~
- ~Verify transformed template deploys and application functions as expected~
- ~Add/update example to `examples/2016-10-31`~
=> chore(docs): fix a cognito event source example

samtranslator/plugins/api/implicit_api_plugin.py, tests/plugins/api/test_implicit_api_plugin.py, tests/translator/input/error_api_event_import_vaule_reference.yaml, tests/translator/output/error_api_event_import_vaule_reference.json, tests/translator/test_translator.py
N/A
Fixes an uncaught error if the RestApiId property contains a dictionary (like an import value statement). **SAM does not yet support referencing an Api outside of the current template.**
Tests written, updated, and pass
*Checklist:*
=> fix: throw better error for improper api reference

versions/2016-10-31.md
#1268 
The link is broken  for DynamoDb and is working for Kinesis
fixed the link for DestinationConfig Object for DynamoDB
*Checklist:*
=> fix: destination config link

samtranslator/model/eventsources/push.py, tests/translator/output/aws-cn/cognito_userpool_with_event.json, tests/translator/output/aws-us-gov/cognito_userpool_with_event.json, tests/translator/output/cognito_userpool_with_event.json
*Issue #, if available:* Fixes #1253.
When the `AWS::Lambda::Permission` resource was created for a Cognito event, it used the `EventSourceToken` property. This caused authentication (or, in my case, _pre_-authentication) events to fail to execute "due to error `AccessDeniedException`". This PR changes that to the `SourceArn` property.
I deployed a transformed template of one of my applications and attempted to authenticate. I succeeded. 🎉
*Checklist:*
=> fix: Transform Cognito Events to a Permission with `SourceArn`

.travis.yml, DEVELOPMENT_GUIDE.rst, setup.py, tox.ini
https://github.com/awslabs/serverless-application-model/issues/945
Thank you for the ping @jpangburn
=> Add Python 3.8 as supported

docs/internals/generated_resources.rst
N/A
Fix rst markup, as Cognito is not been seen in TOC
*Checklist:*
=> Prettify document

examples/apps/inbound-ses-spam-filter/template.yaml
*Description of changes:* Currently, this filter is pretty useless to deploy as a nested stack. I cannot use the [published resource](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:077246666028:applications~inbound-ses-spam-filter) because I cannot tie the Function ARN to my SES ReceiptRuleAction. This change adds an output so that this template is useful for nested deployments.
*Description of how you validated changes:* No validation
*Checklist:*
=> Update inbound-ses-spam-filter to include Lambda ARN

examples/2016-10-31/policy_templates/all_policy_templates.yaml, samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
Added describe cloudwatch alarm history to list of policy templates.
- update tests
- `make pr` passes
- Update documentation
- Verify transformed template deploys and application functions as expected
- Add example to `examples/2016-10-31`
=> Adding cloudwatch:describeAlarmHistory policy

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
Resolves issue #1251
Added kinesis:DescribeStreamSummary action to KinesisCrudPolicy and KinesisReadStreamPolicy
Validated via unit test.
*Checklist:*
=> Allow kinesis:DescribeStreamSummary for KinesisCrudPolicy and KinesisReadStreamPolicy

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
*Issue #, if available:* #289
Please refer to https://github.com/awslabs/serverless-application-model/issues/289#issuecomment-537731710
- Fixed the DynamoDB stream ARN format
- ListStreams action does not support specific stream.
- make pr 
I deployed sam app like this:
```yaml
Globals:
Function:
Timeout: 10
Runtime: python3.7
Resources:
DDBTable:
Type: AWS::DynamoDB::Table
Properties:
AttributeDefinitions:
- AttributeName: id
AttributeType: S
KeySchema:
- AttributeName: id
KeyType: HASH
ProvisionedThroughput:
ReadCapacityUnits: 1
WriteCapacityUnits: 1
StreamSpecification:
StreamViewType: NEW_IMAGE
ProcessDDBStreamFunction:
Properties:
CodeUri: process_ddb_stream/
Handler: …
```
=> fix(PolicyTemplate): DynamoDBStreamReadPolicy

samtranslator/model/api/api_generator.py, samtranslator/model/apigateway.py, samtranslator/model/eventsources/push.py, samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py, tests/translator/input/api_with_auth_with_default_scopes.yaml, tests/translator/input/api_with_auth_with_default_scopes_openapi.yaml, tests/translator/output/api_with_auth_with_default_scopes.json, tests/translator/output/api_with_auth_with_default_scopes_openapi.json, tests/translator/output/aws-cn/api_with_auth_with_default_scopes.json, tests/translator/output/aws-cn/api_with_auth_with_default_scopes_openapi.json, tests/translator/output/aws-us-gov/api_with_auth_with_default_scopes.json, tests/translator/output/aws-us-gov/api_with_auth_with_default_scopes_openapi.json, tests/translator/test_translator.py, versions/2016-10-31.md
*Issue #, if available:* 
#652 
*Description of changes:* 
This adds support for authorisation scopes to the SAM spec. It is a small hanges to the swagger translator that add authorization scopes per method.
I have added an e2e test in the from of an example yaml file (`api_with_auth_with_scopes.yaml`) with all usage options. I also added swagger specific tests to `test_swagger.py`.
*Checklist:*
=> Add authorizationscopes

samtranslator/open_api/open_api.py, tests/translator/input/http_api_existing_openapi.yaml, tests/translator/input/http_api_existing_openapi_conditions.yaml, tests/translator/output/aws-cn/explicit_http_api.json, tests/translator/output/aws-cn/http_api_existing_openapi.json, tests/translator/output/aws-cn/http_api_existing_openapi_conditions.json, tests/translator/output/aws-cn/implicit_http_api_auth_and_simple_case.json, tests/translator/output/aws-cn/implicit_http_api_with_many_conditions.json, tests/translator/output/aws-us-gov/explicit_http_api.json, tests/translator/output/aws-us-gov/http_api_existing_openapi.json, tests/translator/output/aws-us-gov/http_api_existing_openapi_conditions.json, tests/translator/output/aws-us-gov/implicit_http_api_auth_and_simple_case.json, tests/translator/output/aws-us-gov/implicit_http_api_with_many_conditions.json, tests/translator/output/explicit_http_api.json, tests/translator/output/http_api_existing_openapi.json, tests/translator/output/http_api_existing_openapi_conditions.json, tests/translator/output/implicit_http_api_auth_and_simple_case.json, tests/translator/output/implicit_http_api_with_many_conditions.json
#1300 
Fix securitySchemes to be in the correct place in OpenApi doc.
Spec: https://swagger.io/docs/specification/authentication/
Tests updated and verified.
*Checklist:*
=> fix(httpapi): nest securitySchemes under components section in openapi

samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
#1136
Added the policy for Athena to the policy_template.json file
Added the suggested code to the local file and checked with a workgroup if access was granted and queries could be executed. 
*Checklist:*
=> feat: AthenaQueryPolicy template

examples/2016-10-31/lambda_edge/README.md, examples/2016-10-31/lambda_edge/template.yaml, tests/translator/input/error_function_with_no_alias_provisioned_concurrency.yaml, tests/translator/input/function_with_deployment_preference.yaml, tests/translator/output/aws-cn/function_with_deployment_preference.json, tests/translator/output/aws-us-gov/function_with_deployment_preference.json, tests/translator/output/function_with_deployment_preference.json
None
The current examples and templates for lambda provisioned concurrency works fine for a true valid condition, but if the condition in the example is false, it will fail with and error because the parent property ProvisionedConcurrencyConfig will still be present, but will have no child configuration settings.
In the example templates, change the condition AliasProvisionedConcurrencyEnabled to false
Then when you try to deploy the template, cloudformation deploy will fail with the error:
```
Property ProvisionedConcurrentExecutions cannot be empty.
```
I also added a missing condition in the lambda_edge/template.yaml 
*Checklist:*
By submitting this pull request, I confirm that my …
=> Amend provisioned concurrency examples and templates to work for false condition

samtranslator/plugins/application/serverless_app_plugin.py, tests/plugins/application/test_serverless_app_plugin.py
If `AWS::Serverless::Application` has a `Location` property with `ApplicationId` and `SemanticVersion`, but `SemanticVersion` is passed an explicit `null` value, SAM will throw an uncaught error. This fix adds a check for this case so SAM returns a validation error as expected.
`make pr` passes. Also manually verified using sam-translate.py and this sample template:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
NestedApp:
Type: AWS::Serverless::Application
Properties:
Location:
ApplicationId: foo
SemanticVersion: null
```
Without the fix:
```sh
% ./bin/sam-translate.py --template-file foo.yaml
ERROR:samtranslator.plugins:Plugin …
```
=> fix: handle explicit null in nested app SemanticVersion

versions/2016-10-31.md
Adding a note that we are in process of migrating to official docs.
*Checklist:*
=> fix: adding official docs page in versions.md

samtranslator/model/eventsources/push.py, tests/translator/input/error_function_with_api_key_false.yaml, tests/translator/output/error_function_with_api_key_false.json, tests/translator/test_translator.py
#1328 
added a check if api_auth exists
added an error case
make pr
*Checklist:*
=> fix: throw error for apikey false in api event when not defined in api

versions/2016-10-31.md
*Description of changes:* I updated the broken section of the documentation which confuses ApiKey users.
*Checklist:*
=> -Fixed code documentation of API Auth Key format

versions/2016-10-31.md
Remove comment stating FIFO SQS Queues aren't supported
https://aws.amazon.com/blogs/compute/new-for-aws-lambda-sqs-fifo-as-an-event-source/
=> docs: remove comment stating FIFO SQS Queues aren't supported

DEVELOPMENT_GUIDE.rst
This PR address #1391.
Updated the dev guide to have proper formatting command instructions.
*Checklist:*
- Fails for 5 files that are currently wrong in the `develop` branch. Can update if needed.
=> 1391: update black instructions in dev guide

examples/2016-10-31/policy_templates/all_policy_templates.yaml, samtranslator/policy_templates_data/policy_templates.json
Adding a policy `TextractPolicy` that grants full access to Textract. It grants the following permissions:
- textract:*
Adding a policy `TextractDetectAnalyzePolicy` that grants detect and analyze access to Textract. It grants the following permissions:
- textract:DetectDocumentText
- textract:StartDocumentTextDetection
- textract:StartDocumentAnalysis
- textract:AnalyzeDocument
Adding a policy `TextractDetectAnalyzePolicy` that grants get result access to Textract. It grants the following permissions:
- textract:GetDocumentTextDetection
- textract:GetDocumentAnalysis
I ran make pr.
*Checklist:*
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> feat(policy-templates): add Textract policies

versions/2016-10-31.md
The YAML with `authorizers` example was malformed.
*Issue #, if available:* #1378
*Description of changes:* 
I splitted the example YAML in the _API Auth Object_ section between the main _Auth:_ section and the _Authorizers:_ subsection.
Manually checked it with a markdown viewer
*Checklist:*
_All above are irrelevant_
=> Fix Template Specification API Auth Object section

samtranslator/model/sam_resources.py, tests/translator/output/aws-cn/basic_function.json, tests/translator/output/aws-cn/globals_for_function.json, tests/translator/output/aws-us-gov/basic_function.json, tests/translator/output/aws-us-gov/globals_for_function.json, tests/translator/output/basic_function.json, tests/translator/output/globals_for_function.json
#1401 
X-Ray is now using the `AWSXRayDaemonWriteAccess` policy. This policy has the exact same permissions as `AWSXrayWriteOnlyAccess`, which is being deprecated.
*Checklist:*
=> fix: update policy used for xray tracing

examples/apps/README.md
N/A
I accidentally deleted this change before it was merged. This adds a README to point to the new home of the example applications.
*Checklist:*
=> docs: add README pointing to example apps

.travis.yml, bin/sam-translate.py, samtranslator/model/sam_resources.py, tests/translator/model/preferences/test_deployment_preference_collection.py, tests/translator/test_api_resource.py, tests/translator/test_translator.py, tests/translator/validator/test_validator.py
Updating black to the latest version. This will make it easier for people to make contributions and format their PRs.
*Checklist:*
=> chore: update black version

versions/2016-10-31.md
=> Updating spec to include EventBusName for both CloudWatchEvent and EventBridgeRule, which are identical

samtranslator/translator/translator.py
This handles the error of when referencing an API via Ref so that the dictionary check actually occurs. This makes the type checks equivalent and isn't as restrictive as the OrderedDict class. Helps for when things like cfn-lint pass in templates which is where I noticed the bug after updating to the latest version.
*Checklist:*
=> fix: unhashable type: 'dict_node' when referencing RestApiId by Ref in Lambda event mapping on redeploy check

samtranslator/model/api/api_generator.py, tests/translator/output/aws-cn/api_with_usageplans.json, tests/translator/output/aws-us-gov/api_with_usageplans.json
N/A
Related to PR #1179 
Usage plans, when the SHARED option was selected, was adding the same api multiple times.
`make pr` and updated tests
*Checklist:*
=> fix: fix usage plan SHARED bug

examples/2016-10-31/policy_templates/all_policy_templates.yaml, samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
*Description of changes:* Adds a dedicated template policy for EventBridge granting the permissions to publish events to EventBus either custom ones or partner events.
*Description of how you validated changes:* Unit tests for transformed had been added to validate that the additional policy had been output.
*Checklist:*
=> Added EventBridgePutEventsPolicy template

samtranslator/translator/translator.py
https://github.com/aws-cloudformation/cfn-python-lint/issues/1325
Do a correct type check, which will fix a recent SAM bug in cfn-lint
`make pr`
*Checklist:*
=> fix: use isinstance check instead of type (#1411)

samtranslator/model/sam_resources.py, tests/translator/output/aws-cn/basic_function.json, tests/translator/output/aws-cn/globals_for_function.json, tests/translator/output/aws-us-gov/basic_function.json, tests/translator/output/aws-us-gov/globals_for_function.json, tests/translator/output/basic_function.json, tests/translator/output/globals_for_function.json
This reverts commit 2d5d7a0cd76b02a80fea3c0d8c99867036189abe.
N/A
Reverts the XRay policy update. This update caused some customers deployments to break due to tightly controlled permissions regarding specific managed policies. While the permissions in these policies are the exact same, the names are different and caused some failures.
`make pr`
*Checklist:*
=> revert: "fix: update policy used for xray tracing (#1405)"

samtranslator/model/eventsources/push.py, samtranslator/open_api/open_api.py, tests/translator/input/http_api_existing_openapi.yaml, tests/translator/output/aws-cn/http_api_existing_openapi.json, tests/translator/output/aws-us-gov/http_api_existing_openapi.json, tests/translator/output/http_api_existing_openapi.json, versions/2016-10-31.md
#1317 
Allow setting `TimeoutInMillis` on HttpApi events.
`make pr`
*Checklist:*
=> feat: add TimeoutInMillis to HttpApi events

tests/translator/input/http_api_explicit_stage.yaml, tests/translator/output/aws-cn/http_api_explicit_stage.json, tests/translator/output/aws-us-gov/http_api_explicit_stage.json, tests/translator/output/http_api_explicit_stage.json, versions/2016-10-31.md
N/A
Document support for AccessLogSettings for Http Api and add tests.
`make pr`
*Checklist:*
=> docs: document support for HTTP API Access Log Settings

DEVELOPMENT_GUIDE.rst
Only text changes. Tested via Github's preview
=> Fix markdown style links in not-markdown

versions/2016-10-31.md
The term "AWS Serverless Application Definition template" is not one I have seen anywhere else in this doc nor on any other doc, but "AWS Serverless Application Model template" is found. I'm assuming this is a prior naming convention that should be updated to prevent confusion.
Changing two instances of the word "Definition" to "Model"
n/a
*Checklist:*
=> Switch Definition to Model

samtranslator/model/sam_resources.py, tests/translator/input/api_with_usageplans.yaml, tests/translator/output/api_with_usageplans.json, tests/translator/output/aws-cn/api_with_usageplans.json, tests/translator/output/aws-us-gov/api_with_usageplans.json
#1432 
made usageplan resources a referable property to api
*Checklist:*
=> fix: make usageplan properties referable

samtranslator/model/eventsources/pull.py, tests/translator/output/aws-cn/function_with_event_source_mapping.json, tests/translator/output/aws-us-gov/function_with_event_source_mapping.json, tests/translator/output/function_with_event_source_mapping.json
#1475 
removed the `Type` property after transformation as its used by SAM internally to determine the type of the policy to add.
*Checklist:*
=> fix: remove type property after transformation

examples/2016-10-31/http_api_cors/template.yaml, samtranslator/model/api/http_api_generator.py, samtranslator/model/sam_resources.py, samtranslator/plugins/globals/globals.py, tests/translator/input/explicit_http_api.yaml, tests/translator/input/http_api_explicit_stage.yaml, tests/translator/output/aws-cn/explicit_http_api.json, tests/translator/output/aws-cn/http_api_explicit_stage.json, tests/translator/output/aws-us-gov/explicit_http_api.json, tests/translator/output/aws-us-gov/http_api_explicit_stage.json, tests/translator/output/explicit_http_api.json, tests/translator/output/http_api_explicit_stage.json, versions/2016-10-31.md
=> feat(HttpApi): add support for FailOnWarnings

samtranslator/model/eventsources/push.py, samtranslator/open_api/open_api.py, tests/translator/input/http_api_existing_openapi.yaml, tests/translator/input/implicit_http_api.yaml, tests/translator/output/aws-cn/http_api_existing_openapi.json, tests/translator/output/aws-cn/implicit_http_api.json, tests/translator/output/aws-us-gov/http_api_existing_openapi.json, tests/translator/output/aws-us-gov/implicit_http_api.json, tests/translator/output/http_api_existing_openapi.json, tests/translator/output/implicit_http_api.json
=> fix(HttpApi): add path parameters if not present

versions/2016-10-31.md
=> merge master into develop

versions/2016-10-31.md
=> document IpV6 option on Domain Configuration object

setup.py
#1595
Exclude test modules from whl
Built whl locally to make sure `tests.*` modules are not packaged in the whl.
*Checklist:*
=> chore: Exclude test modules in whl

samtranslator/model/cognito.py
#1506 
Added missing property types
*Checklist:*
=> fix : missing UserPool properties (#1506)

samtranslator/swagger/swagger.py, tests/model/eventsources/test_api_event_source.py
Why is this change necessary?
* To transfrom the arn in the api gateway resource policy to be "*"
instead of the name of the path itself.
How does it address the issue?
* Allow to address the appropriate resource.
What side effects does this change have?
* None that are known at this point.
https://github.com/awslabs/serverless-application-model/issues/1549
* Transform path of kinds, {path+}, {proxy+} into "*"
- deployed the template without errors as referenced in https://github.com/awslabs/serverless-application-model/issues/1549
*Checklist:*
=> fix: resource policy generation for {path+}

examples/2016-10-31/api_endpointconfiguration/template.yaml, samtranslator/model/api/api_generator.py, samtranslator/model/sam_resources.py, tests/translator/input/api_endpoint_configuration_with_vpcendpoint.yaml, tests/translator/output/actual, tests/translator/output/api_endpoint_configuration_with_vpcendpoint.json, tests/translator/output/aws-cn/api_endpoint_configuration_with_vpcendpoint.json, tests/translator/output/aws-us-gov/api_endpoint_configuration_with_vpcendpoint.json, tests/translator/output/error_api_with_custom_domains_invalid.json, tests/translator/test_translator.py, tests/translator/validator/test_validator.py, versions/2016-10-31.md
*Issue #1327
Adds support for configuring a PRIVATE  RestApi Endpoint
added unit tests with expected input and output
*Checklist:*
=> feat: add support for VPCEndpointIds in EndpointConfiguration

docs/policy_templates.rst
#1677 
Updated URL of file in doc
*Checklist:*
*Examples?*
=> docs: fix link to all_policy_templates example file

samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py
=> add new arguments to allow vpc/vpce endpoints as intrinsics

samtranslator/model/eventsources/push.py, tests/model/eventsources/test_cloudwatch_event_source.py
#1742 
Target#Id property in Event::Rule resource is a mandatory property[1]. We have an abstraction in SAM which generates TargetId based on LogicalId and a suffix. Issue is TargetId has a limit of 64 characters. So in case user have a long logical id there is no way for user to provide a shorter Target Id. This changes adds an option Target property which can be used to pass Id. If Target#Id is present then in that case we'll use that Id otherwise generate id as we are generating.
[1] https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Target.html#eventbridge-Type-Target-Id
*Checklist:*
*Examples?*
Please reach out in the comments, if you want to add an example. Examples will be …
=> fix: adding support for passing target id to EventBridgeRule

.pre-commit-config.yaml, .travis.yml, DEVELOPMENT_GUIDE.rst, Makefile, requirements/dev.txt, samtranslator/model/__init__.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/iam.py, samtranslator/model/lambda_.py, samtranslator/model/sam_resources.py, samtranslator/parser/parser.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/swagger/swagger.py, samtranslator/translator/translator.py, tests/model/test_api_v2.py, tests/swagger/test_swagger.py, tests/test_model.py, tests/translator/test_function_resources.py, tox.ini
update black version to 20.8b1 and make it managed by requirement dev.txt.
This change is a counterpart of https://github.com/aws/aws-sam-cli/pull/2314 
**Note: Since black does not support Python 2.7, nor the later black releases contains a binary artifact, I turned off black check for Python 2.7.** (https://github.com/psf/black/issues/1669)
*Checklist:*
*Examples?*
=> Manage black version using requirement file

requirements/base.txt, requirements/dev.txt
Update all dependencies versions in requirement txts to match their latest available versions.
Since we are either using `~=x.y` or `>=x.y.z`, this PR does not have effective change.
I left `pylint` untouched because it is not being used right now. I created another PR #1745 for enabling it.
*Checklist:*
*Examples?*
=> chore: Upgrade outdated dependencies in base.txt and dev.txt

requirements/base.txt, requirements/dev.txt
`>=` usage was introduced to SAM more than 2 years ago (67826f2a396c725d89d10637cdddeae41f6fee4d) and we have been using it ever since.
`>=` can be breaking if our one of our dependencies has a breaking major/minor release. It is safer to manage upgrade ourselves with exception of patch version releases. Using `~=` ([Compatible release clause](https://www.python.org/dev/peps/pep-0440/#compatible-release)) can maintain compatibility as much as possible without losing access to security patches.
Checked with `pip freeze` of existing `develop` to ensure they are the versions we are using:
```
(samtranslator37) ~/P/serverless-application-model ❯❯❯ pip freeze
appdirs==1.4.4
astroid==1.6.6 …
```
=> chore: Use Compatible release clause in requirement files

samtranslator/model/api/api_generator.py, samtranslator/model/eventsources/push.py, tests/translator/input/error_cognito_userpool_not_string.yaml, tests/translator/input/error_state_machine_with_invalid_default_authorizer.yaml, tests/translator/output/error_cognito_userpool_not_string.json, tests/translator/output/error_state_machine_with_invalid_default_authorizer.json, tests/translator/test_translator.py
=> Fix: DefaultAuth not a string exception

samtranslator/model/sam_resources.py, samtranslator/model/stepfunctions/events.py, samtranslator/model/stepfunctions/generators.py, tests/model/stepfunctions/test_state_machine_generator.py, tests/translator/input/state_machine_with_permissions_boundary.yaml, tests/translator/output/aws-cn/state_machine_with_permissions_boundary.json, tests/translator/output/aws-us-gov/state_machine_with_permissions_boundary.json, tests/translator/output/state_machine_with_permissions_boundary.json, tests/translator/test_translator.py
Taking over https://github.com/aws/serverless-application-model/pull/1635 from Vaib. I'm not a maintainer, so I wasn't able to edit the existing PR to address the comments.
---
* Adding `PermissionsBoundary` property for State Machine resource similar to that for [SAM Function](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-permissionsboundary)
* `PermissionsBoundary` property only works if the role is generated by SAM (using the `Policies` property)
* `PermissionsBoundary` property also applies to the roles created for the event sources.
*Checklist:*
*Examples?*
Please reach out in the comments, if you want to add an …
=> Adding PermissionsBoundary property for State Machine resource

samtranslator/model/sam_resources.py, tests/translator/output/aws-cn/basic_function.json, tests/translator/output/aws-cn/globals_for_function.json, tests/translator/output/aws-us-gov/basic_function.json, tests/translator/output/aws-us-gov/globals_for_function.json
Previously used `AWSXrayWriteOnlyAccess` policy name is deprecated and not available in gov & cn regions. With this change we are going to assign newer policy name (`AWSXRayDaemonWriteAccess `) for those regions.
Updated unit tests and validated different region has different policy names.
*Checklist:*
*Examples?*
=> fix: use newer policy name in gov & cn regions for xray

samtranslator/model/api/http_api_generator.py, samtranslator/open_api/open_api.py, tests/model/api/test_http_api_generator.py, tests/translator/input/error_implicit_http_api_auth_any_method.yaml, tests/translator/output/error_implicit_http_api_auth_any_method.json, tests/translator/test_translator.py
Fix: Regex issue when basepath is /
Fix: keyerror in open_api when method is ANY
*Checklist:*
*Examples?*
=> Fix: Regex issue and Keyerror crash

appveyor.yml, tox.ini
=> Move Tests to Appveyor

requirements/base.txt
#1809 
Reverts `boto3` pinned dependency from `~=1.15.16` back to `~=1.5` (original PR: #1762)
Ran tests locally
*Checklist:*
*Examples?*
=> Revert boto3 dependency pin to ~=1.5

samtranslator/intrinsics/resolver.py, samtranslator/swagger/swagger.py, tests/intrinsics/test_resolver.py, tests/translator/input/error_invalid_method_definition.yaml, tests/translator/input/error_mappings_is_null.yaml, tests/translator/input/error_swagger_security_not_dict.yaml, tests/translator/output/error_invalid_method_definition.json, tests/translator/output/error_mappings_is_null.json, tests/translator/output/error_swagger_security_not_dict.json, tests/translator/test_translator.py
Fix: SAM crashes method_definition for path is invalid
Fix: SAM crashes when mappings is null
Fix: Swagger security not a dict
*Checklist:*
*Examples?*
=> Fix: SAM crashes method_definition for path is invalid

appveyor.yml, requirements/base.txt, tox.ini
=> Revert boto3 dependency pin to ~=1.5 (#1810)

Makefile, samtranslator/model/eventsources/push.py, tests/translator/input/function_event_conditions.yaml, tests/translator/output/aws-cn/function_event_conditions.json, tests/translator/output/aws-us-gov/function_event_conditions.json, tests/translator/output/function_event_conditions.json
This fixes a bug of not having `Condition` propagated to the generated `AWS::SQS::QueuePolicy` resource if a SNS event source is used with `SqsSubscription` in a `AWS::Serverless::Function` resource.
Also updated the black commands in `Makefile` to check only `.py` files
*Checklist:*
*Examples?*
=> fix: propagate condition to sqs queue policy for sqssubscription

samtranslator/model/preferences/deployment_preference_collection.py, samtranslator/region_configuration.py, samtranslator/translator/arn_generator.py, tests/unit/model/preferences/test_deployment_preference_collection.py, tests/unit/test_region_configuration.py, tests/unit/translator/test_arn_generator.py
CodeDeploy is migrating from AWSCodeDeployRoleForLambda to AWSCodeDeployRoleForLambdaLimited.
Some partitions do not support AWSCodeDeployRoleForLambda and therefore we need to use the newer
one in those partitions. We cannot widely update to AWSCodeDeployRoleForLambdaLimited since this
can cause customer's stacks to fail unexpectedly.
*Checklist:*
*Examples?*
=> fix: Support new CodeDeploy ManagedPolicy

samtranslator/model/eventsources/pull.py, samtranslator/model/lambda_.py, tests/translator/input/function_with_event_source_mapping.yaml, tests/translator/output/aws-cn/function_with_event_source_mapping.json, tests/translator/output/aws-us-gov/function_with_event_source_mapping.json, tests/translator/output/function_with_event_source_mapping.json, versions/2016-10-31.md
Added support for FuntionResponseTypes in EventSourceMapping model. This is required to support custom checkpointing for Kinesis and DDB streams. 
https://aws.amazon.com/blogs/compute/optimizing-batch-processing-with-custom-checkpoints-in-aws-lambda/
`make pr` succeeds.
*Checklist:*
*Examples?*
Added translator tests which contain a sample input.
=> Sam support for custom checkpointing

samtranslator/model/api/http_api_generator.py, samtranslator/open_api/open_api.py, tests/model/test_sam_resources.py, tests/openapi/test_openapi.py, tests/translator/input/http_api_description.yaml, tests/translator/output/aws-cn/http_api_description.json, tests/translator/output/aws-us-gov/http_api_description.json, tests/translator/output/http_api_description.json
This PR fixes how the `Description` property is handled for a `AWS::Serverless::HttpApi` resource:
When `Description` is set, one of the followings will happen:
* if `DefinitionBody` is not set, an error will be thrown
* if `DefinitionBody` is set and `description` is already set in the OpenAPI definition, an error will be thrown
* if `DefinitionBody` is set and no `description` is set in the OpenAPI definition, `description` will be set in the OpenAPI definition.
Before the changes, deploying a `AWS::Serverless::HttpApi` resource with `Description` set will result in an error:
```
Redundant fields [description="description"] provided when either Body or
BodyS3Location is not empty (Service: null; Status Code: 0; Error Code: null;
Request …
```
=> Fix: Description in AWS::Serverless::HttpApi

samtranslator/model/api/http_api_generator.py, tests/model/api/test_http_api_generator.py
In HTTP API authorizers, we don't yet handle intrinsics, and an attempt
to use them creates a crash when it tries to hash the input `dict`. This
change starts by wrapping that use case properly so that a helpful error
is raised until intrinsics are supported here.
Note: Does not yet handle `!Sub`, looking at options for that.
*Checklist:*
=> fix: Better Error Handling of Intrinsics

samtranslator/feature_toggle/feature_toggle.py
boto3 client has default 60 seconds timeout for both read and connection.
The worst case would be 360 seconds from 120 seconds timeout * 3 retires.
SAM translator lambda function has 120 seconds timeout which can be exceeded if AppConfig experiences a long response delay issue.
Tested with 900ms network latency. (1800ms roundt trip)
*Checklist:*
*Examples?*
=> fix(AppConfig): Updated AppConfig boto3 Client Timeout

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Based on the SAM CLI repo templates
=> chore: Add issue and feature request GitHub templates

versions/2016-10-31.md
followup to https://github.com/awslabs/serverless-application-model/pull/1290
Minor fix for missing item in table of contents.
Manual validation
*Checklist:*
=> docs: link to HttpApi from "Event source types"

samtranslator/sdk/parameter.py, samtranslator/translator/arn_generator.py, samtranslator/translator/translator.py, tests/sdk/test_parameter.py, tests/translator/test_arn_generator.py
https://github.com/awslabs/aws-sam-cli/issues/442
This is the first part in solving https://github.com/awslabs/aws-sam-cli/issues/442. Specifically, SAM uses boto to get a region and then pick the associated partition it lives within. This is mainly for two things (that I can tell):
1. Get the partition so it can be added to a generated arn in the generated template
2. Add pseudo values as Parameters so SAM can do some basic resolving. 
For the first, we shouldn't need to explicitly put the partition into the template anywhere but instead use the CloudFormation pseudo value when writing the template. I attempted to do this initially but required changing every single output.json test file we have and the pr started to really grow. So I …
=> feat: Allow Boto3 Session to be configured

samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
#1854
Added a policy template `AcmGetCertificatePolicy` that give a permission to read a certificate from AWS Certificate Manager. 
- **Granted permission**: [GetCertificate](https://docs.aws.amazon.com/acm/latest/APIReference/API_GetCertificate.html) ( `acm:GetCertificate` )
- **Resource**: The certificate ARN. 
I pass the full certificate's ARN, not the id, because the CloudFormation resource [AWS::CertificateManager::Certificate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html) returns only the ARN.
Lambda function in a private network making HTTPS requests to a private server. The Lambda needs to add the certificate chain to its CA Bundle.
By submitting this pull request, I confirm that my contribution is made under the …
=> feat(policy-templates): add AcmGetCertificatePolicy

samtranslator/feature_toggle/feature_toggle.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/translator/managed_policy_translator.py
Produce more log before/after boto3.client makes API calls. This is to help to make debugging AWS dependencies' issue easier.
*Checklist:*
*Examples?*
=> chore: Add logging to boto3.client usage

integration/helpers/base_test.py, integration/helpers/resource.py, integration/resources/expected/single/function_with_deployment_preference_alarms_intrinsic_if.json, integration/resources/templates/single/function_with_deployment_preference_alarms_intrinsic_if.yaml, integration/single/test_basic_function.py, samtranslator/model/function_policies.py, samtranslator/model/intrinsics.py, samtranslator/model/preferences/deployment_preference_collection.py, samtranslator/model/resource_policies.py, samtranslator/translator/translator.py, tests/model/test_function_policies.py, tests/test_intrinsics.py, tests/translator/input/error_function_with_deployment_preference_invalid_alarms.yaml, tests/translator/input/function_with_deployment_preference_alarms_intrinsic_if.yaml, tests/translator/model/preferences/test_deployment_preference_collection.py, tests/translator/output/aws-cn/function_with_deployment_preference_alarms_intrinsic_if.json, tests/translator/output/aws-us-gov/function_with_deployment_preference_alarms_intrinsic_if.json, tests/translator/output/error_function_with_deployment_preference_invalid_alarms.json, tests/translator/output/function_with_deployment_preference_alarms_intrinsic_if.json, tests/translator/test_translator.py
**Issue #, if available:**
#1624 
**Description of changes:**
Handles `Fn::If` in `DeploymentPreference/Alarms` where we would only allow a list before.
**Description of how you validated changes:**
- Unit tests
- E2E tests
- Deployed the resulting CFN template and verified the stack content
- Integration test
**Checklist:**
**Examples?**
=> feat: Handle Fn::If intrinsic for Alarms

samtranslator/policy_templates_data/policy_templates.json, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
The action underlying this policy does not take a particular resource.
Resolves #1944
Removes templated ARN from `AMIDescribePolicy`, replacing it with a static `*`.
Aside from the translator tests, created a Lambda Function using these permissions and successfully performed the action.
*Checklist:*
*Examples?*
=> fix(policy-templates): Correct AMIDescribePolicy

samtranslator/policy_templates_data/policy_templates.json, tests/translator/input/all_policy_templates.yaml, tests/translator/output/all_policy_templates.json, tests/translator/output/aws-cn/all_policy_templates.json, tests/translator/output/aws-us-gov/all_policy_templates.json
*Issue #, if available:* https://github.com/aws/serverless-application-model/issues/1930
*Description of changes:* Add "Route53ChangeResourceRecordSetsPolicy" policy
*Checklist:*
=> feat(policy-templates): add Route53ChangeResourceRecordSetsPolicy

integration/helpers/base_test.py, integration/helpers/yaml_utils.py
change yaml.load to yaml.safe_load for the security best practice
=> fix: Change yaml.load to yaml_parse as a best practice

integration/helpers/base_test.py, integration/helpers/yaml_utils.py
* change yaml.load to yaml.safe_load for the security best practice
* use yaml_parse for consistant style
*Checklist:*
*Examples?*
=> fix: Change yaml.load to yaml_parse as a best practice (#1951)

setup.py
Unit tests are excluded from installation. I assume the convention also applies to integration tests.
Running `python setup.py install` without this patch creates `~/.local/lib/python3.9/site-packages/integration`. That folder is no longer installed after this patch.
*Checklist:*
N/A - only the build script is changed
*Examples?*
=> chore: don't install integration tests

tests/openapi/test_openapi.py, tests/swagger/test_swagger.py
None
While browsing through the Repository and the Tests, I found two instances where the List Comprehension has been used unnecessarily. I have fixed that to make the code more readable and understanding. 
*Checklist:*
=> Fix: Remove unnecessary use of comprehension

samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/region_configuration.py
SAR does not provide service in af-south-1. SAM translator will throw a 5xx error instead of a 4xx.
*Checklist:*
*Examples?*
=> fix: Added SAR Support Check

samtranslator/swagger/swagger.py, tests/translator/input/function_with_request_parameters.yaml, tests/translator/output/aws-cn/function_with_request_parameters.json, tests/translator/output/aws-us-gov/function_with_request_parameters.json, tests/translator/output/function_with_request_parameters.json
As per [this documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html#sam-function-api-requestparameters), Request Parameters names can contain dots.
fix the request parameter parsing, the value can contain dots
*Checklist:*
*Examples?*
=> fix the request parameter parsing, the value can contain dots

docs/internals/generated_resources.rst
*Description of changes:* Fixed the incorrectly formatted header for HTTP API section. Previously, the section wasn't corrected recognized and not rendered in the table of contents too
*Description of how you validated changes:* generated preview
*Checklist:*
*Examples?*
=> Documentation: fix incorrect header

samtranslator/intrinsics/resolver.py, samtranslator/model/apigateway.py, samtranslator/model/intrinsics.py, samtranslator/model/stepfunctions/generators.py, samtranslator/open_api/open_api.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/swagger/swagger.py, samtranslator/translator/arn_generator.py, samtranslator/translator/translator.py, tests/intrinsics/test_resolver.py, tests/translator/test_arn_generator.py
=> fix: mutable default values in method definitions

samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py, tests/translator/input/error_api_with_invalid_path_object.yaml, tests/translator/output/error_api_with_invalid_path_object.json, tests/translator/test_translator.py
When customers use auth and define an invalid method in the open api
definition, SAM would return a 'server error'. This was actually
due to SAM attempting to get the method from the path. If the method
was not a supported method and non-lowercase, SAM would attempt to fetch
the lower case method and crash with a KeyError. This PR addresses that
by checking for the valid methods supported.
*Checklist:*
*Examples?*
=> fix: Crash when using an invalid method in open api

samtranslator/translator/managed_policy_translator.py, tests/translator/test_managed_policies_translator.py
SAM runs within a Lambda function and loads IAM Managed Policies once per
Lambda. Previous to this, SAM would call IAM 9 times which could cause
throttling by IAM. With this change, we update the MaxItems from the
default of 100 to the max (1000). In local testing, this has shown
a 0.6 second reduction in the latency in calling IAM.
n/a
See above
I tested the updated Policy loader in a python interpreter validating the pagination works as expected.
*Checklist:*
*Examples?*
By submitting this pull request, I confirm that my …
=> fix: Increase PageSize of ListPolicies Paginator

samtranslator/model/apigateway.py, tests/model/test_api.py, tests/translator/input/api_with_auth_all_minimum.yaml, tests/translator/output/api_with_auth_all_minimum.json, tests/translator/output/aws-cn/api_with_auth_all_minimum.json, tests/translator/output/aws-us-gov/api_with_auth_all_minimum.json
This reverts commit 0eb3630410ae569503513e52670ece61dc4d4301.
This change caused regression, reverting until the bug is fixed.
bug: `ReauthorizeEvery` can be a `dict` when intrinsic functions are used.
*Checklist:*
*Examples?*
=> Revert "Issue 1508 remove check requiring identity ... (#1577)"

samtranslator/model/api/api_generator.py, samtranslator/model/eventsources/push.py, samtranslator/model/sam_resources.py, tests/translator/input/api_with_usageplans_shared_attributes_three.yaml, tests/translator/input/api_with_usageplans_shared_attributes_two.yaml, tests/translator/output/api_with_usageplans_shared_attributes_three.json, tests/translator/output/api_with_usageplans_shared_attributes_two.json, tests/translator/output/aws-cn/api_with_usageplans_shared_attributes_three.json, tests/translator/output/aws-cn/api_with_usageplans_shared_attributes_two.json, tests/translator/output/aws-us-gov/api_with_usageplans_shared_attributes_three.json, tests/translator/output/aws-us-gov/api_with_usageplans_shared_attributes_two.json, tests/translator/test_translator.py, tests/unit/model/api/TestSharedApiUsagePlan.py
When using Shared Usage plan for `AWS::Serverless::Api` resource, following auto-generated resources should contain the resource level attributes from (multiple) API definitions `ApiGatewayUsagePlan`, `ApiGatewayApiKey`, `ApiGatewayUsagePlanKey`
Added unit tests and additional templates for validation
*Checklist:*
*Examples?*
=> fix: Shared Usage Plan scenarios for Resource Level Attribute Support

tests/translator/input/api_with_usageplans_shared_no_side_effect_1.yaml, tests/translator/input/api_with_usageplans_shared_no_side_effect_2.yaml, tests/translator/output/api_with_usageplans_shared_no_side_effect_1.json, tests/translator/output/api_with_usageplans_shared_no_side_effect_2.json, tests/translator/output/aws-cn/api_with_usageplans_shared_no_side_effect_1.json, tests/translator/output/aws-cn/api_with_usageplans_shared_no_side_effect_2.json, tests/translator/output/aws-us-gov/api_with_usageplans_shared_no_side_effect_1.json, tests/translator/output/aws-us-gov/api_with_usageplans_shared_no_side_effect_2.json, tests/translator/test_translator.py
Added a new group test `test_transform_success_no_side_effect` in `tests/translator/test_translator.py` to test for side effects between translator executions
*Checklist:*
*Examples?*
=> test: New test group to test for side effects

docs/safe_lambda_deployments.rst
https://github.com/aws/serverless-application-model/issues/2010
Same as https://github.com/aws/serverless-application-model/pull/2044 but against `develop`, how it should've been.
*Checklist:*
*Examples?*
=> docs: fix dead link (develop)

samtranslator/feature_toggle/dialup.py, samtranslator/feature_toggle/feature_toggle.py, samtranslator/translator/translator.py, tests/feature_toggle/input/feature_toggle_config.json, tests/feature_toggle/test_dialup.py, tests/feature_toggle/test_feature_toggle.py
Add support for Percentage-based Enablement for Feature Toggle.
When `enabled-%` is set (instead of `enabled`) under a region config, `is_enabled_for_account_in_region(...)` will determine whether the given `account_id` falls in the percentage range for feature enablement.
Added more tests
*Checklist:*
*Examples?*
=> Percentage-based Enablement for Feature Toggle

Makefile, integration/metrics/test_metrics_integration.py, samtranslator/metrics/metrics.py, samtranslator/translator/translator.py, tests/metrics/test_metrics.py
=> Adding support for metric publishing, manually tested and tests pending.

integration/combination/test_function_with_kinesis.py, integration/resources/expected/combination/function_with_kinesis_intrinsics.json, integration/resources/templates/combination/function_with_kinesis_intrinsics.yaml, tests/translator/input/kinesis_intrinsics.yaml, tests/translator/output/aws-cn/kinesis_intrinsics.json, tests/translator/output/aws-us-gov/kinesis_intrinsics.json, tests/translator/output/kinesis_intrinsics.json, tests/translator/test_translator.py
=> feat(Intrinsic Tests): Added Tests for Kinesis Event Source with Intrinsics

samtranslator/open_api/open_api.py, samtranslator/swagger/swagger.py, tests/translator/input/api_with_any_method_in_swagger.yaml, tests/translator/output/api_with_any_method_in_swagger.json, tests/translator/output/aws-cn/api_with_any_method_in_swagger.json, tests/translator/output/aws-us-gov/api_with_any_method_in_swagger.json, tests/translator/test_translator.py
N/A
[here](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/swagger/swagger.py#L628) the method_name, which is a [key](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/swagger/swagger.py#L623) in the path hash, is normalized (may be modified) then get [fetched](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/swagger/swagger.py#L630) again from the same hash which will result in KeyError if the normalization modified the key
Not normalizing the key. It looks like the logic was just a copy/paste from another place where the normalization was needed. but here it is not needed at all.
*Checklist:*
*Examples?* …
=> fix: Don't attempt to refetch a swagger method object by its name as we already have it

samtranslator/model/apigateway.py, tests/model/test_api.py, tests/translator/input/api_with_auth_all_minimum.yaml, tests/translator/input/api_with_identity_intrinsic.yaml, tests/translator/output/api_with_auth_all_minimum.json, tests/translator/output/api_with_identity_intrinsic.json, tests/translator/output/aws-cn/api_with_auth_all_minimum.json, tests/translator/output/aws-cn/api_with_identity_intrinsic.json, tests/translator/output/aws-us-gov/api_with_auth_all_minimum.json, tests/translator/output/aws-us-gov/api_with_identity_intrinsic.json, tests/translator/test_translator.py
#1508
Was originally introduced #1577 but reverted #2038 due to service impact. Specifically, the originally implementation did not consider intrinsics as the value (a dict) and therefore threw a `TypeError` and caused SAM to unexpectedly crash.
This PR reverts the revert (re-introducing the originally changes) but updated the implementation to support handling intrinsics. Also adding more unit tests to cover a wider range of inputs and new functional tests to test a "live" template with intrinsics in it.
Ran both the functional tests and unit tests on develop and this branch. Which pass. 
Here is the output from the unit tests:
```
(venv-python38) ➜  serverless-application-model git:(develop) ✗ …
```
=> fix(bug): Check if Identity.ReauthorizeEvery equals zero

integration/helpers/deployer/deployer.py
There is no such punctuation as `..`. There is a period (`.`). There is an ellipsis (`…` or `…`).
This corrects the grammar in the line to use punctuation which exists.
=> fix: Correct grammar in the waiting for changeset message

samtranslator/model/api/http_api_generator.py, tests/model/api/test_http_api_generator.py
None
The API gateway supports multiple segments in the base path mappings like specified in this [repository](https://github.com/aws-samples/sessions-with-aws-sam/blob/master/multi-level-mapping/reportingv1.yaml#L21). However, whenever a ```BasePath``` with multiple segments is specified in a ```AWS::Serverless::HttpApi``` (see examples below), than the template does not contain these multiple segments after the transformation anymore.
```yaml
HttpApi:
Type: AWS::Serverless::HttpApi
Properties:
Domain:
DomainName: somedomain.com
CertificateArn: some-certificate-arn
BasePath:
- "api/v1"
EndpointConfiguration: REGIONAL
Route53:
HostedZoneId: some-hosted-zone
```
```json
// transformed template
"HttpApiapiApiMapping": {
"Type": …
```
=> fix: Allow multiple path segments in BasePath

samtranslator/feature_toggle/feature_toggle.py, samtranslator/metrics/method_decorator.py, samtranslator/metrics/metrics.py, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/eventsources/__init__.py, samtranslator/model/eventsources/cloudwatchlogs.py, samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/model/sam_resources.py, samtranslator/model/stepfunctions/events.py, samtranslator/model/stepfunctions/generators.py, samtranslator/plugins/api/default_definition_body_plugin.py, samtranslator/plugins/api/implicit_api_plugin.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/plugins/globals/globals_plugin.py, samtranslator/plugins/policies/policy_templates_plugin.py, samtranslator/translator/managed_policy_translator.py, samtranslator/translator/translator.py, tests/metrics/test_method_decorator.py
This commit enables metric collection per resource, if a `Metrics` instance is been defined and configured to use CloudWatch.
*Checklist:*
- [] Update documentation
=> feat: add metrics per resource transformation

samtranslator/model/api/api_generator.py, tests/translator/input/error_gateway_response_invalid_type_int.yaml, tests/translator/input/error_gateway_response_invalid_type_intrinsic.yaml, tests/translator/output/error_gateway_response_invalid_type_int.json, tests/translator/output/error_gateway_response_invalid_type_intrinsic.json, tests/translator/test_translator.py
Thanks to Ruperto for helping with this PR.
*Checklist:*
*Examples?*
=> fix: Check GatewayResponse value type.

samtranslator/metrics/metrics.py, tests/metrics/test_metrics.py
We're seeing noise in our logs when attempting to publish empty metrics.
```
Traceback (most recent call last):
File "/var/task/samtranslator/metrics/metrics.py", line 54, in _flush_metrics
self.cloudwatch_client.put_metric_data(Namespace=namespace, MetricData=metric_data)
File "/var/task/botocore/client.py", line 386, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/aws_xray_sdk/ext/botocore/patch.py", line 42, in _xray_traced_botocore
meta_processor=aws_meta_processor,
File "/var/task/aws_xray_sdk/core/recorder.py", line 435, in record_subsegment
return_value = wrapped(*args, **kwargs)
File "/var/task/botocore/client.py", line 705, in _make_api_call
raise error_class(parsed_response, operation_name) …
```
=> fix: Check Metrics List is Not Empty Before Publishing

samtranslator/model/api/api_generator.py, tests/model/api/test_api_generator.py, tests/translator/input/error_api_invalid_usage_plan.yaml, tests/translator/output/error_api_invalid_usage_plan.json
=> Raise InvalidResourceException when UsagePlan type is not correct

samtranslator/parser/parser.py, tests/parser/test_parser.py
A follow-up to #2032 to try/catch potential failures from schema validation during parsing.
Added unit tests for `Parser` to address particular failure points.
*Checklist:*
*Examples?*
=> Add try catch to prevent schema validation fails transform while parsing

samtranslator/model/api/api_generator.py, samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py, tests/translator/input/error_api_with_cors_and_empty_allow_origin.yaml, tests/translator/output/error_api_with_cors_and_empty_allow_origin.json
If a template with empty AllowOrigins is passed to SAM we detect and throw `ValueError`, this error is then left uncaught and causes service error. This PR Is converting that `ValueError` to a SAM specific error which is then handled properly and proper error message is returned as part of transform failure.
Added functional test.
*Checklist:*
*Examples?*
=> Fix no allowed origin

samtranslator/plugins/api/implicit_http_api_plugin.py, samtranslator/plugins/api/implicit_rest_api_plugin.py, tests/translator/input/error_function_invalid_event_api_ref.yaml, tests/translator/input/error_function_invalid_event_http_api_ref.yaml, tests/translator/output/error_api_event_import_vaule_reference.json, tests/translator/output/error_api_swagger_integration_with_condition_intrinsic_api_id.json, tests/translator/output/error_api_swagger_integration_with_find_in_map_intrinsic_api_id.json, tests/translator/output/error_api_swagger_integration_with_getatt_intrinsic_api_id.json, tests/translator/output/error_api_swagger_integration_with_join_intrinsic_api_id.json, tests/translator/output/error_api_swagger_integration_with_select_intrinsic_api_id.json, tests/translator/output/error_api_swagger_integration_with_sub_intrinsic_api_id.json, tests/translator/output/error_api_swagger_integration_with_transform_intrinsic_api_id.json, tests/translator/output/error_function_invalid_event_api_ref.json, tests/translator/output/error_function_invalid_event_http_api_ref.json
… string
*Checklist:*
*Examples?*
=> Raise InvalidEventException when RestApiId/ApiId is not resolved to a string

samtranslator/model/eventsources/pull.py, tests/translator/input/error_function_with_invalid_stream_eventsource_dest_type.yaml, tests/translator/input/error_function_with_missing_on_failure_in_stream_event_destination_config.yaml, tests/translator/input/function_with_event_source_mapping.yaml, tests/translator/output/aws-cn/error_function_with_invalid_stream_eventsource_dest_type.json, tests/translator/output/aws-cn/error_function_with_missing_on_failure_in_stream_event_destination_config.json, tests/translator/output/aws-cn/function_with_event_source_mapping.json, tests/translator/output/aws-us-gov/error_function_with_invalid_stream_eventsource_dest_type.json, tests/translator/output/aws-us-gov/error_function_with_missing_on_failure_in_stream_event_destination_config.json, tests/translator/output/aws-us-gov/function_with_event_source_mapping.json, tests/translator/output/error_function_with_invalid_stream_eventsource_dest_type.json, tests/translator/output/error_function_with_missing_on_failure_in_stream_event_destination_config.json, tests/translator/output/function_with_event_source_mapping.json
Fix `DestinationConfig` of streaming event sources by ensuring `OnFailure` is defined before it's used.
If `OnFailure` is missing, an error will be thrown.
*Checklist:*
*Examples?*
=> Fix DestinationConfig in streaming event sources

samtranslator/model/api/api_generator.py, samtranslator/swagger/swagger.py, tests/translator/input/error_api_no_cors_invalid_openapi_null_path.yaml, tests/translator/input/error_api_no_cors_invalid_openapi_string_path.yaml, tests/translator/output/error_api_no_cors_invalid_openapi_null_path.json, tests/translator/output/error_api_no_cors_invalid_openapi_string_path.json
`_openapi_postprocess` expects the value at a path to be a dict. The following template would cause an unhandled error: 
```
Resources:
ApiWithInvalidPath:
Type: AWS::Serverless::Api
Properties:
StageName: Prod
OpenApiVersion: 3.0.1
DefinitionBody:
openapi: 3.0.1
info:
title: test invalid paths Api
paths:
/foo: null
```
This PR checks that it is a dict and throws an error if it's not. Also did some refactoring while I updated this part of the code.
Added end-to-end tests
*Checklist:*
*Examples?*
By submitting this pull request, I …
=> fix: handle non-dict DefinitionBody path item in _openapi_postprocess

Makefile, requirements/dev.txt
Run unit tests in parallel, on my 16-inch macbook pro, the time of `make test` is reduced from 227.18s to 64.78s, which is a 72% reduction.
*Checklist:*
*Examples?*
=> Run unit tests in parallel

samtranslator/model/eventsources/push.py, tests/translator/input/api_with_no_properties.yaml, tests/translator/output/api_with_no_properties.json, tests/translator/output/aws-cn/api_with_no_properties.json, tests/translator/output/aws-us-gov/api_with_no_properties.json, tests/translator/test_translator.py
=> Handle when HttpApi resource doesn't have properties

samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py, tests/translator/input/error_api_auth_invalid_path_item.yaml, tests/translator/input/error_api_auth_null_path_item.yaml, tests/translator/output/error_api_auth_invalid_path_item.json, tests/translator/output/error_api_auth_null_path_item.json
Add validation of path item objects when creating the SwaggerEditor object.
Possible concerns:
**What if it breaks some existing template despite they are invalid, customers are still using them?**
I just did a test with CFN, turns out even we don't do validation ourselves, CFN/Api Gateway will fail.
Tested templates:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
ApiWithInvalidPath:
Type: AWS::Serverless::Api
Properties:
StageName: Prod
DefinitionBody:
swagger: 2.0
paths:
/foo: ""
```
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
ApiWithInvalidPath:
Type: AWS::Serverless::Api
Properties:
StageName: Prod
DefinitionBody:
swagger: 2.0
paths:
/foo: …
```
=> Validate swagger path item objects

samtranslator/swagger/swagger.py, tests/translator/input/error_null_method_definition.yaml, tests/translator/output/error_invalid_method_definition.json, tests/translator/output/error_null_method_definition.json
=> Validate swagger method value is a valid dict before processing

samtranslator/parser/parser.py
https://github.com/aws/aws-sam-cli/issues/3493
- remove `.join` call on `validation_errors`, which is already a string
- replace deprecated `LOG.warn` with `LOG.warning` (https://stackoverflow.com/questions/15539937/whats-the-difference-between-logging-warn-and-logging-warning-in-python)
Ran transform with debugger and the message was printed properly
*Checklist:*
*Examples?*
=> fix: fix validation errors log message that calls join on a string

samtranslator/model/__init__.py, tests/translator/input/resource_with_invalid_type.yaml, tests/translator/output/aws-cn/resource_with_invalid_type.json, tests/translator/output/aws-us-gov/resource_with_invalid_type.json, tests/translator/output/resource_with_invalid_type.json, tests/translator/test_translator.py
We should verify that the type of resource type is a string before trying to hash it. It should then work similarly to the current behaviour. If the type of a resource is invalid, we should skip that resource and continue processing the other resources.
*Checklist:*
*Examples?*
=> fix: Check type of resource type is a string

samtranslator/plugins/application/serverless_app_plugin.py, tests/plugins/application/test_serverless_app_plugin.py
n/a
Currently, if an API call to Serverless Application Repository (SAR) is throttled while querying for the status of an application, the transform fails.  This change allows the transform to sleep and then retry, up to the time limit configured in code.
Unit tests were added.
*Checklist:*
*Examples?*
=> Do not abort SAR loop on throttling

integration/resources/expected/single/basic_api_with_mode_update.json
Update expected result for a integration test case to incorporate py27hashfix changes
*Checklist:*
*Examples?*
=> Update integ test expected result to incorporate py27hashfix changes

examples/apps/README.md
The repo pointed to by the link to examples is archived an no longer current. This changes the link to the correct repo which the SAM CLI pulls down the quickstart templates from in `sam init`.
Verified this is the repo outputted by the SAM CLI during cloning.
*Checklist:*
*Examples?*
=> [minor docs] Updates examples link to current non-archived repo

versions/2016-10-31.md
* adding missing properties of EventBridgeRule
* adding DeadLetterConfig Object and RetryPolicy Object to Data Types section
* improving EventBridgeRule example
#1427
*Checklist:*
=> docs: updating EventBridgeRule documentation

samtranslator/open_api/open_api.py, tests/translator/input/error_http_api_invalid_tags_format.yaml, tests/translator/output/error_http_api_invalid_tags_format.json
N.A.
If the tags in the definition body is not a list, the tags parsing will cause iteration errors.
Added a check for the validity of the definition body that has tags specified.
*Checklist:*
*Examples?*
=> fix: Add handling for OpenApi definition that has tags with invalid format

.pylintrc, requirements/base.txt, samtranslator/intrinsics/actions.py, samtranslator/intrinsics/resource_refs.py, samtranslator/model/__init__.py, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/eventbridge_utils.py, samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/model/function_policies.py, samtranslator/model/resource_policies.py, samtranslator/model/role_utils/role_constructor.py, samtranslator/model/s3_utils/uri_parser.py, samtranslator/model/sam_resources.py, samtranslator/model/stepfunctions/events.py, samtranslator/model/stepfunctions/generators.py, samtranslator/model/types.py, samtranslator/open_api/open_api.py, samtranslator/plugins/api/implicit_http_api_plugin.py, samtranslator/plugins/api/implicit_rest_api_plugin.py, samtranslator/plugins/globals/globals.py, samtranslator/swagger/swagger.py, samtranslator/translator/logical_id_generator.py, samtranslator/translator/translator.py, samtranslator/yaml_helper.py, tests/sdk/test_template.py
- Remove `six`
*Checklist:*
*Examples?*
=> Remove six as dependency

pytest.ini, requirements/dev.txt, samtranslator/intrinsics/actions.py, samtranslator/metrics/metrics.py, samtranslator/model/eventsources/push.py, samtranslator/open_api/open_api.py
Fix all deprecation warnings in tests
*Checklist:*
*Examples?*
=> Fix all warnings in tests

.github/PULL_REQUEST_TEMPLATE.md
=> Update PR template to add integration tests in checklist

samtranslator/model/api/api_generator.py, tests/translator/input/error_api_with_custom_domains_route53_invalid_type.yaml, tests/translator/output/error_api_with_custom_domains_route53_invalid_type.json
=> Improve exception processing for Route53 with invalid type

samtranslator/model/eventsources/push.py, tests/translator/input/error_s3_lambda_configuration_invalid_type.yaml, tests/translator/output/error_s3_lambda_configuration_invalid_type.json
=> fix: Check S3 Lambda Configuration Type is a List

samtranslator/model/apigateway.py, tests/validator/input/api/error_auth_cognito.yaml, tests/validator/output/api/error_auth_cognito.json
=> fix: ValueError is not caught by int()

samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/region_configuration.py, tests/unit/test_region_configuration.py
n/a
Generalize existing `RegionConfiguration.is_sar_supported` method into a `is_service_supported` method as we'll need to check availability of other services as well.
Unit tests.
*Checklist:*
=> Add method for determining service availability in a region

.pylintrc, Makefile, requirements/dev.txt
Previously, this repo did not do any linting. The linting that is enabled
is basic, as this commit disables all of what pylint was complaining about.
Linting was not done on commits, this update changes this. The `.pylintrc` file was copied from our other repos (aws-sam-cli) that we maintain.
Add linting and make linting run on `make pr`.
I will make this more useful to us in the near future by fixing some of the smaller issues and likely just forcing pylint to ignore the rest. That way new code is always linted and we can work on removing/update the "legacy" code to be cleaner.
Ran `make pr`
*Checklist:*
*Examples?*
Please reach out in the comments, if you want to add an example. Examples will …
=> chore: Enable pylint on project

samtranslator/model/sam_resources.py, tests/translator/input/error_function_with_invalid_dlq_property_type.yaml, tests/translator/output/error_function_with_invalid_dlq_property_type.json
Update validation for dlq 
*Checklist:*
*Examples?*
=> update validation for dead letter queue

samtranslator/utils/py27hash_fix.py, tests/utils/test_py27hash_fix.py
*Issue #, if available:* n/a
Implement `__deepcopy__` for `Py27Dict` and related classes in order to improve performance.  The generic deep copy in `copy` works, but is slow.
Unit tests were added, and existing unit tests cover `Py27Dict` functionality.  We also timed how long the transform took for a large template before and after the changes (for a very large template, these changes reduced processing time by ~80%). We confirmed that the transformed templates were the same before and after the changes.
*Checklist:*
=> Py27dict deepcopy performance

integration/combination/test_function_with_deployment_preference.py, integration/resources/expected/combination/function_with_custom_code_deploy.json, integration/resources/templates/combination/function_with_custom_code_deploy.yaml
- Fix flaky integration test case due to potentially conflicting Deployment Config name.
- Run the modified test case and validated it passed
*Checklist:*
*Examples?*
=> Update function_with_custom_code_deploy integration test case

integration/combination/test_http_api_with_cors.py
Cfn recently released an update to add default tags to APIGW V2 resources to include some additional default tags. Our tests need to be updated to reflect these changes.
*Checklist:*
*Examples?*
=> fix: Update tag count check for apigw v2 resources

samtranslator/model/apigatewayv2.py, tests/translator/input/error_api_authorizer_property_indentity_with_invalid_type.yaml, tests/translator/output/error_api_authorizer_property_indentity_with_invalid_type.json
updated validation checks to validate that property type of `LambdaAuthorizer` property `indentity`
*Checklist:*
*Examples?*
=> validate Lambda Authorizer property identity

integration/combination/test_api_with_gateway_responses.py
=> test: Add retries on flaky integration test

samtranslator/model/eventsources/push.py, tests/translator/input/error_api_with_models_of_invalid_type.yaml, tests/translator/output/error_api_with_models_of_invalid_type.json
Added validation to Api property Model to ensure that its either of type dict or an intrinsic function.
if a customer provides in a SAM a value API property Model and its neither a type dict nor an intrinsic function. An error is raised notifying the customer of the invalid type.
*Checklist:*
*Examples?*
=> Validation for API property Model

samtranslator/model/__init__.py, samtranslator/model/apigateway.py, samtranslator/model/apigatewayv2.py, samtranslator/plugins/api/implicit_api_plugin.py, tests/model/test_api.py
N/A
Use string formatting when preparing the exception messages. Otherwise it is creating issues when concatenating a string with Py27Dict object.
*Checklist:*
*Examples?*
=> fix: use formatting instead of concatenating when preparing the exception messages

bin/sam-translate.py
also: https://github.com/aws/aws-cdk/pull/19656, https://github.com/cloudtools/troposphere/pull/2028, https://github.com/awslabs/goformation/pull/445
[CloudFormation templates can currently only be 1MB](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html), and [template size limits apply even after transformation processing](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-macros.html#template-macros-use)
Simply reducing indentation from 2 to 1 should remove ~1/4 of the template file size for everyone by default while still preserving indentation formatting. Beyond improving the default, those wishing to reduce readability for further reduced file size could opt into using something like [`jq`](https://stedolan.github.io/jq/) on …
=> reduce CloudFormation template size

tests/utils/test_py27hash_fix.py
N/A
Remove usage of deprecate `self.assert_` for `self.assertTrue`
Ran `make pr`
*Checklist:*
*Examples?*
=> chore(test): Move assert_ to assertTrue

samtranslator/model/eventsources/push.py, samtranslator/open_api/open_api.py, samtranslator/swagger/swagger.py, tests/openapi/test_openapi.py, tests/swagger/test_swagger.py
N/A
Replaced `ValueError` exceptions with `InvalidDocumentException` which should help SAM Transform to gracefully exit execution for invalid Swagger/OpenAPI inputs.
*Checklist:*
=> fix: use InvalidDocumentException instead of ValueError

bin/sam-translate.py, samtranslator/feature_toggle/feature_toggle.py
#1911 
Remove `sys.path` overrides that were done to support a testing script.
Remove `sys.path` overriding.
*Checklist:*
*Examples?*
=> chore: remove sys.path override

samtranslator/model/sam_resources.py, tests/translator/input/function_with_function_url_config_conditions.yaml, tests/translator/output/aws-cn/function_with_function_url_config_conditions.json, tests/translator/output/aws-us-gov/function_with_function_url_config_conditions.json, tests/translator/output/function_with_function_url_config_conditions.json, tests/translator/test_translator.py
https://github.com/aws/serverless-application-model/issues/2385
=> fix: pass the condition attribute to the generated function url resources for the conditional functions

samtranslator/plugins/api/implicit_http_api_plugin.py, tests/translator/input/error_function_api_invalid_properties.yaml, tests/translator/output/error_function_api_invalid_properties.json
N/A
Fix validation for `Properties` field of `HttpApi` event source for Serverless Function.
Tested with the case where `Properties` field would be an empty string, and added error test cases to cover that.
*Checklist:*
*Examples?*
=> fix: raise InvalidEventException for incorrect Properties field usage for Api event type

samtranslator/model/sam_resources.py, tests/model/api/test_http_api_generator.py, tests/translator/output/aws-cn/function_with_function_url_config_and_autopublishalias.json, tests/translator/output/aws-us-gov/function_with_function_url_config_and_autopublishalias.json, tests/translator/output/function_with_function_url_config_and_autopublishalias.json
https://github.com/aws/serverless-application-model/issues/2373
Grant public access to function alias
*Checklist:*
*Examples?*
=> Furl AutopublishAlias bug fix 

integration/single/test_basic_function.py, requirements/dev.txt
*Issue #, if available:* 
N/A
Update FURL integration test to test invoke the created Lambda Function
Running the updated tests from my laptop
*Checklist:*
*Examples?*
=> Update FURL integ test to test invoke

integration/combination/test_api_settings.py, integration/combination/test_api_with_authorizer_apikey.py, integration/combination/test_api_with_authorizers.py, integration/config/logger_configurations.py, integration/helpers/base_test.py, integration/helpers/request_utils.py, integration/single/test_basic_api.py, integration/single/test_basic_function.py, integration/single/test_function_with_http_api_and_auth.py, pytest.ini
We've seen errors in APIGW requests before that we haven't been able to debug since we haven't logged the necessary request IDs. This PR adds some filtering to extract relevant headers for all requests to APIGW and log them to the console.
Unfortunately, since the `requests` and `urllib3` libraries don't use Python's logger module, we have to add some custom logic here to log the relevant headers.
Relevant link: https://stackoverflow.com/questions/16337511/log-all-requests-from-the-python-requests-module
*Checklist:*
=> test: Add logging for relevant Amazon headers useful for debugging

integration/resources/templates/combination/api_with_authorizers_invokefunction_set_none.yaml, integration/resources/templates/single/basic_api_with_mode.yaml, integration/resources/templates/single/basic_api_with_mode_update.yaml
N/A
Upgrade Python3.6 runtime to Python3.8 in integration test templates, as Python3.6 runtime is being deprecated
*Checklist:*
*Examples?*
=> Update python3.6 runtime in integration test templates

tests/translator/input/definition_body_intrinsics_support.yaml, tests/translator/output/aws-cn/definition_body_intrinsics_support.json, tests/translator/output/aws-us-gov/definition_body_intrinsics_support.json, tests/translator/output/definition_body_intrinsics_support.json, tests/translator/test_translator.py
Adding missing end-to-end test to make sure we keep supporting intrinsics where we currently support them in DefinitionBody.
*Checklist:*
*Examples?*
=> test: Add tests for intrinsics support for DefinitionBody

samtranslator/open_api/open_api.py, tests/translator/input/error_http_api_null_method.yaml, tests/translator/output/error_http_api_null_method.json
N/A
Checks if method is not `None` before proceeding to work on it.
Adding a new test case and verifying the older ones.
*Checklist:*
*Examples?*
=> fix: check null method for open api

samtranslator/model/apigatewayv2.py, tests/translator/input/error_api_authorizer_property_indentity_header_with_invalid_type.yaml, tests/translator/output/error_api_authorizer_property_indentity_header_with_invalid_type.json
added validation to validate the property type of Authorizers Identity parameter Headers to arrest a situation where an intrinsic value can't be resolved.
created a test sam template and tested the exception
*Checklist:*
*Examples?*
=> validate Http Api Authorizers identity Header

samtranslator/open_api/open_api.py, tests/translator/output/error_http_api_null_method.json
Follow up for #2409
Changed error message to contain normalized method name rather than method object
Re-running unit tests which contains example use case
*Checklist:*
*Examples?*
=> fix: update error message to contain the normalized method rather than the method dict

samtranslator/model/eventsources/push.py, samtranslator/open_api/open_api.py, samtranslator/swagger/swagger.py, tests/translator/output/error_http_api_invalid_openapi.json
N/A
Replace `str` parameters with array of exceptions for `InvalidDocumentException` constructor call.
By running existing test cases.
*Checklist:*
*Examples?*
=> fix: use array of exceptions instead of str for InvalidDocumentException

README.md
=> blogs, video and workshop update in readme

samtranslator/model/sam_resources.py, tests/translator/input/error_auto_publish_alias_empty_string.yaml, tests/translator/output/error_auto_publish_alias_empty_string.json
n/a
Check if AutoPublishAlias is "truthy", which matches what we do elsewhere in the code. 
Added the test first, which failed and after patching the test passed. 
*Checklist:*
*Examples?*
=> fix: Fail gracefully when AutoPublishAlias is an empty string

samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/sam_resources.py, samtranslator/translator/translator.py, tests/model/api/test_http_api_generator.py, tests/translator/input/api_with_custom_domain_route53_multiple.yaml, tests/translator/input/api_with_custom_domain_route53_multiple_intrinsic_hostedzoneid.yaml, tests/translator/input/http_api_with_custom_domain_route53_multiple.yaml, tests/translator/input/mixed_api_with_custom_domain_route53_multiple.yaml, tests/translator/output/api_with_custom_domain_route53_multiple.json, tests/translator/output/api_with_custom_domain_route53_multiple_intrinsic_hostedzoneid.json, tests/translator/output/aws-cn/api_with_custom_domain_route53_multiple.json, tests/translator/output/aws-cn/api_with_custom_domain_route53_multiple_intrinsic_hostedzoneid.json, tests/translator/output/aws-cn/http_api_with_custom_domain_route53_multiple.json, tests/translator/output/aws-cn/mixed_api_with_custom_domain_route53_multiple.json, tests/translator/output/aws-us-gov/api_with_custom_domain_route53_multiple.json, tests/translator/output/aws-us-gov/api_with_custom_domain_route53_multiple_intrinsic_hostedzoneid.json, tests/translator/output/aws-us-gov/http_api_with_custom_domain_route53_multiple.json, tests/translator/output/aws-us-gov/mixed_api_with_custom_domain_route53_multiple.json, tests/translator/output/http_api_with_custom_domain_route53_multiple.json, tests/translator/output/mixed_api_with_custom_domain_route53_multiple.json, tests/translator/test_translator.py
#1829 
Keep track of created `AWS::Route53::RecordSetGroup` resources in a cache. If a logical ID is already contained in the cache, use the created one and append a record set into it. Otherwise, create a new `AWS::Route53::RecordSetGroup` for that logical ID and keep it in the cache.
- Added e2e test (`tests/translator/input/api_with_custom_domain_route53_multiple.yaml`) to confirm the template is transformed as expected
*Checklist:*
*Examples?*
By submitting this pull request, I confirm that my contribution is made under the terms …
=> Fix route53 record set groups

integration/single/test_function_with_http_api_and_auth.py
N.A.
To exclude regions for http tests so it does not get tested in regions not supporting http api
This change uses the same decorator used in other http api tests
*Checklist:*
*Examples?*
=> chore: Add region skip condition and retry for http test

samtranslator/swagger/swagger.py, tests/translator/input/error_swagger_security_not_dict_with_api_key_required.yaml, tests/translator/output/error_swagger_security_not_dict.json, tests/translator/output/error_swagger_security_not_dict_with_api_key_required.json
N/A
Adding a validation to confirm security is a dict in swagger when ApiKeyRequired is set to true
*Checklist:*
*Examples?*
=> Add validation for swagger security when ApiKeyRequired is true

integration/combination/test_api_with_authorizer_apikey.py, integration/combination/test_function_with_self_managed_kafka.py, integration/helpers/base_test.py
One of the tests use "arn:aws:apigateway" has URI prefix, but for special region's partitions it doesn't work since the partition name would be different
Added a partition property into base test and use partition instead
*Checklist:*
*Examples?*
=> chore: Add missing import and add partition into base test for integration test

samtranslator/metrics/metrics.py, tests/metrics/test_metrics.py
N/A
Allow customized timestamp when recording metrics.
Updated existing tests to include test cases with customized timestamp
*Checklist:*
*Examples?*
=> Update methods in Metrics class to accept timestamp

samtranslator/model/stepfunctions/events.py, tests/model/stepfunctions/test_schedule_event.py, tests/translator/input/error_state_machine_with_invalid_schedule_event.yaml, tests/translator/input/state_machine_with_event_schedule_state.yaml, tests/translator/output/aws-cn/state_machine_with_event_schedule_state.json, tests/translator/output/aws-us-gov/state_machine_with_event_schedule_state.json, tests/translator/output/error_state_machine_with_invalid_schedule_event.json, tests/translator/output/state_machine_with_event_schedule_state.json
#2467 
add State property to Schedule EventSource for AWS::Serverless::StateMachine.
added invalid input and transform tests
*Checklist:*
*Examples?*
=> feat: Add State Property to Schedule EventSource in StateMachine

samtranslator/feature_toggle/feature_toggle.py, tests/feature_toggle/test_feature_toggle.py
We need to monitor all SAM Translator dependencies usage and failures, and this change to allow SAM Translator service to send a monitored APP Config client to the FeatureToggleAppConfigConfigProvider class to be used instead of creating a new client. 
*Checklist:*
*Examples?*
=> chore: Change FeatureToggleAppConfigConfigProvider to accept AppConfig client, so SAM-T can send a monitored client.

Makefile, mypy.ini, requirements/dev.txt, samtranslator/intrinsics/actions.py, samtranslator/model/__init__.py, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/model/sam_resources.py, samtranslator/model/sqs.py, samtranslator/model/stepfunctions/events.py, samtranslator/plugins/globals/globals.py, samtranslator/public/helpers.py, samtranslator/sdk/resource.py, samtranslator/utils/py27hash_fix.py
Have bare minimal type check and we can enable more checks in the future to ensure code quality and correctness.
No behavior changes have been made in this PR.
*Checklist:*
*Examples?*
=> chore: Add basic mypy check (no behavior change)

samtranslator/model/eventsources/push.py, tests/model/eventsources/test_eventbridge_rule_source.py, tests/translator/input/error_function_with_invalid_event_bridge_rule.yaml, tests/translator/input/function_with_event_bridge_rule_state.yaml, tests/translator/output/aws-cn/function_with_event_bridge_rule_state.json, tests/translator/output/aws-us-gov/function_with_event_bridge_rule_state.json, tests/translator/output/error_function_with_invalid_event_bridge_rule.json, tests/translator/output/function_with_event_bridge_rule_state.json
N/A
Add state property to EventBridgeRule EventSource for AWS::Serverless::Function.
Added invalid input and transform tests.
*Checklist:*
*Examples?*
=> feat: Add State Property to EventBridgeRule EventSource in Function

samtranslator/model/cognito.py, tests/translator/input/cognito_userpool_with_event.yaml, tests/translator/output/aws-cn/cognito_userpool_with_event.json, tests/translator/output/aws-us-gov/cognito_userpool_with_event.json, tests/translator/output/cognito_userpool_with_event.json
#2496
Added `UserAttributeUpdateSettings` to Cognito model.
A sample template that contained the `UserAttributeUpdateSettings` property was run with `bin/sam-translate.py` before and after the changes to validate the property was picked up by the reference to the `AWS::Cognito::UserPool` in the function's events.
*Checklist:*
*Examples?*
=> feat: Added UserAttributeUpdateSettings to Cognito

integration/conftest.py, integration/helpers/client_provider.py, integration/resources/templates/single/basic_application_sar_location.yaml, integration/resources/templates/single/basic_application_sar_location_with_intrinsics.yaml, integration/setup/example-sar-app.yaml, integration/setup/test_setup_teardown.py, integration/single/test_basic_application.py
Instead of using a SAR App from another account, create one before tests begin and use that one.
=> chore: Use pre-created SAR app during integration tests

.gitignore, Makefile, integration/combination/test_api_settings.py, integration/combination/test_api_with_authorizer_apikey.py, integration/config/logger_configurations.py, integration/helpers/base_test.py, integration/single/test_function_with_http_api_and_auth.py, pytest.ini
N.A.
In the integration test logging, when tests are running in parallel, the position of the logging messages does not follow the exact test it belongs to. Therefore a header is added to indicate the test case each request belongs to.
Ran locally to see the logs:
REQUEST LOG [test_cors_1_combination_api_with_cors_openapi] | Time: 2022-09-22 22:28:08,487 Request made to https://* | Status: 200 | Headers: {*}
*Checklist:*
*Examples?*
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> chore: Add test name to request logging and remove default region from pytest.ini

integration/combination/test_api_with_authorizers.py, integration/helpers/base_test.py
N.A.
To clean up integration test run experience for non-internal test runs
Tested outputs locally with and without --internal
*Checklist:*
*Examples?*
=> chore: Only do request logging when internal flag is provided

pytest.ini, requirements/dev.txt
Some tests fail due to transient service issues that should be retried. This should help solve it more generally.
Made a test fail and ran `pytest`:
```
...
[gw3] [ 94%] PASSED tests/translator/test_translator.py::TestTranslatorEndToEnd::test_transform_success_733_connector_bucket_to_function 
[gw2] [ 96%] PASSED tests/translator/test_translator.py::TestTranslatorEndToEnd::test_transform_success_734_connector_bucket_to_function 
[gw4] [ 98%] PASSED tests/translator/test_translator.py::TestTranslatorEndToEnd::test_transform_success_732_connector_bucket_to_function 
[gw1] [100%] RERUN tests/translator/test_translator.py::test_transform_invalid_document[error_connector] …
```
=> chore: rerun failing tests

integration/helpers/deployer/deployer.py
Dealing with cases where integration tests fail and produce no useful logging feedback.
=> Add Integration Test Deployer Logging Improvements

samtranslator/model/stepfunctions/events.py, samtranslator/validator/sam_schema/schema.json, tests/model/eventsources/test_eventbridge_rule_source.py, tests/model/stepfunctions/test_eventbridge_rule_source.py, tests/translator/input/eventbridgerule_with_dlq.yaml, tests/translator/input/state_machine_with_cwe.yaml, tests/translator/output/aws-cn/eventbridgerule_with_dlq.json, tests/translator/output/aws-cn/state_machine_with_cwe.json, tests/translator/output/aws-us-gov/eventbridgerule_with_dlq.json, tests/translator/output/aws-us-gov/state_machine_with_cwe.json, tests/translator/output/eventbridgerule_with_dlq.json, tests/translator/output/state_machine_with_cwe.json
#2509 
- Added a schema and test to support `State` property of `AWS::Events::Rule` in SAM
Used `bin/sam-translate.py` to generate a CFN template from SAM template which I then successfully deployed in my AWS account with desired changes taking effect.
*Checklist:*
*Examples?*
=> Add ability to set State of EventBridge Rule

integration/helpers/resource.py
Need this so that integration tests can handle regions where this resource is not yet present.
=> Add Integ Test Skip Flag for EventBus

.pylintrc, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/sam_resources.py, samtranslator/model/stepfunctions/generators.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/swagger/swagger.py, samtranslator/translator/logical_id_generator.py, samtranslator/translator/translator.py
Enable more pylint rules. Fix the pylint issues introduced by new rules.
Unit test passed.
=> chore: Enable more pylint rules and fixes pylint issues

.github/workflows/codeql.yml
Default [CodeQL](https://codeql.github.com/) workflow, with only change from:
```
branches: [ "develop", feat/*, main, master, py27hash-20210918, release/* ]
```
to
```
branches: [ "develop" ]
```
=> chore: add CodeQL

.pylintrc, samtranslator/intrinsics/actions.py, samtranslator/intrinsics/resolver.py, samtranslator/intrinsics/resource_refs.py, samtranslator/model/__init__.py, samtranslator/model/api/api_generator.py, samtranslator/model/architecture.py, samtranslator/model/connector/connector.py, samtranslator/model/connector_profiles/profile.py, samtranslator/model/intrinsics.py, samtranslator/model/preferences/deployment_preference_collection.py, samtranslator/model/s3_utils/uri_parser.py, samtranslator/model/sam_resources.py, samtranslator/open_api/open_api.py, samtranslator/plugins/globals/globals.py, samtranslator/swagger/swagger.py, samtranslator/translator/translator.py
Enable more rules.
Unit tests passed.
=> Enable more pylint rules and fixes pylint issues

samtranslator/model/eventsources/pull.py, samtranslator/model/lambda_.py, tests/translator/output/aws-cn/function_with_msk.json, tests/translator/output/aws-cn/function_with_msk_with_intrinsics.json, tests/translator/output/aws-cn/function_with_self_managed_kafka.json, tests/translator/output/aws-cn/self_managed_kafka_with_intrinsics.json, tests/translator/output/aws-us-gov/function_with_msk.json, tests/translator/output/aws-us-gov/function_with_msk_with_intrinsics.json, tests/translator/output/aws-us-gov/function_with_self_managed_kafka.json, tests/translator/output/aws-us-gov/self_managed_kafka_with_intrinsics.json, tests/translator/output/function_with_msk.json, tests/translator/output/function_with_msk_with_intrinsics.json, tests/translator/output/function_with_self_managed_kafka.json, tests/translator/output/self_managed_kafka_with_intrinsics.json
#2546
Fix property names according to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#aws-resource-lambda-eventsourcemapping-properties
=> fix: Correct kafka property names in generated event source mapping

DEVELOPMENT_GUIDE.md, Makefile, bin/add_transform_test.py
Added a script to allow easier transform tests creation.
Verified by manual trigger. 
Tested with and without `--disable-api-configuration`, work as expected.
Tested with `arn:aws...`, work as expected.
Not affecting SAM T functionality.
=> chore: Add transform test creation script

bin/add_transform_test.py
=> Do not change input file and exit if hardcoded partition used

integration/resources/templates/combination/connector_bucket_to_function_write.yaml
```
pytest --no-cov integration/combination/test_connectors.py -k connector_bucket_to_function_write
```
=> chore: use connector logical ID for DependsOn in integ test

.pylintrc
Everything time running `make pr`, pylint is giving warnings with unrecognized options. Removing these options.
Make lint still works.
=> Remove unrecognized pylint options

samtranslator/model/__init__.py, samtranslator/model/apigateway.py, samtranslator/model/apigatewayv2.py, samtranslator/model/cloudformation.py, samtranslator/model/codedeploy.py, samtranslator/model/cognito.py, samtranslator/model/dynamodb.py, samtranslator/model/events.py, samtranslator/model/eventsources/cloudwatchlogs.py, samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/model/iam.py, samtranslator/model/iot.py, samtranslator/model/lambda_.py, samtranslator/model/log.py, samtranslator/model/route53.py, samtranslator/model/s3.py, samtranslator/model/sam_resources.py, samtranslator/model/sns.py, samtranslator/model/sqs.py, samtranslator/model/stepfunctions/events.py, samtranslator/model/stepfunctions/resources.py, samtranslator/model/types.py, samtranslator/sdk/resource.py
=> chore: Make PropertyType and related validator typed

README.md
=> docs: use `sam sync` instead of `sam deploy`

samtranslator/model/eventsources/pull.py
https://github.com/aws-cloudformation/cfn-lint/issues/2395
- More pythonic way of determining a type of a value
*Checklist:*
*Examples?*
=> Better test for type of a variable

setup.py
=> chore: Prevent bin/ from installed as a package

bin/_file_formatter.py, bin/json-format.py, bin/yaml-format.py
=> chore: Add --add-test-metadata option to yaml formatter

samtranslator/model/sam_resources.py, tests/translator/input/error_function_with_function_url_config_with_invalid_cors_parameter.yaml, tests/translator/output/error_function_with_function_url_config_with_invalid_cors_parameter.json
=> fix: Raise correct exception when FunctionUrlConfig.Cors is not dict

samtranslator/swagger/swagger.py, tests/translator/input/error_swagger_security_definitions_not_dict.yaml, tests/translator/output/error_swagger_security_definitions_not_dict.json
=> fix: Raise correct exception when swagger: securityDefinitions is not dict

samtranslator/model/api/api_generator.py, samtranslator/swagger/swagger.py, tests/translator/input/error_api_invalid_openapi_path_with_invalid_responses.yaml, tests/translator/output/error_api_invalid_openapi_path_with_invalid_responses.json
=> fix: Raise correct exception when swagger: responses.headers is not a dict

samtranslator/schema/schema.json, samtranslator/schema/schema.py
=> chore: add schema types for Connector and SimpleTable

samtranslator/schema/schema.json, samtranslator/schema/schema.py
=> chore: add schema types to Application

samtranslator/schema/schema.json, samtranslator/schema/schema.py
=> chore: add schema types to LayerVersion

samtranslator/model/api/api_generator.py, samtranslator/schema/schema.py, tests/translator/input/error_api_with_custom_domains_invalid.yaml, tests/translator/output/error_api_with_custom_domains_invalid.json
=> fix: Raise correct exception when Api.Domain is not a map

samtranslator/model/apigateway.py, tests/translator/input/error_api_authorizer_property_indentity_with_invalid_type.yaml, tests/translator/output/error_api_authorizer_property_indentity_with_invalid_type.json
=> fix: Raise correct exception when Identity.Headers is not of valid type

samtranslator/model/eventsources/pull.py, samtranslator/validator/value_validator.py, tests/translator/input/error_function_with_invalid_event_destination_config.yaml, tests/translator/output/aws-cn/error_function_with_missing_on_failure_in_stream_event_destination_config.json, tests/translator/output/aws-us-gov/error_function_with_missing_on_failure_in_stream_event_destination_config.json, tests/translator/output/error_function_with_invalid_event_destination_config.json, tests/translator/output/error_function_with_missing_on_failure_in_stream_event_destination_config.json
Remove unused error files in aws-cn and aws-us-gov
=> fix: Raise correct exception when event OnFailure is not of valid type

samtranslator/schema/schema.json, samtranslator/schema/schema.py
=> chore: add HttpApi schema

samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/open_api/open_api.py, tests/translator/output/error_s3_lambda_configuration_invalid_type.json
=> fix: Raise correct exception when some properties are not dict when used with .get()

samtranslator/schema/aws_serverless_function.py, samtranslator/schema/common.py, samtranslator/schema/docs.yaml, samtranslator/schema/schema.json, samtranslator/schema/schema.py
#1133 
Adds scaffolding so we can support documentation in SAM template hover tooltips.
Will need many more changes but serves as a starting point.
=> chore: scaffolding for schema docs

samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/apigateway.py, samtranslator/swagger/swagger.py
another round of scan of dict type validation
=> fix: Raise correct exception when some properties are not dict when used dict methods

samtranslator/feature_toggle/feature_toggle.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/utils/constants.py
Add connect_timeout=5 (consistent with what we have been using with AppConfig) to SAR. read_timeout remains default, which is 60s as it can take a while to complete request.
=> chore: Add connect timeout to serverlessrepo clients

samtranslator/schema/aws_serverless_application.py, samtranslator/schema/aws_serverless_connector.py, samtranslator/schema/aws_serverless_layerversion.py, samtranslator/schema/aws_serverless_simpletable.py, samtranslator/schema/schema.json, tests/translator/input/function_with_function_url_config_with_intrinsics.yaml
=> chore: docs to Connector/Application/LayerVersion/SimpleTable

samtranslator/schema/aws_serverless_api.py, samtranslator/schema/schema.json
=> chore: add schema docs to `AWS::Serverless::Api`

samtranslator/schema/aws_serverless_function.py, samtranslator/schema/schema.json
=> chore: add docs for Function event Type/Properties

samtranslator/schema/aws_serverless_httpapi.py, samtranslator/schema/schema.json
=> add schema docs to AWS::Serverless::HttpApi

samtranslator/schema/aws_serverless_statemachine.py, samtranslator/schema/schema.json
=> chore: add schema docs to AWS::Serverless::StateMachine

samtranslator/schema/aws_serverless_function.py, samtranslator/schema/common.py, samtranslator/schema/schema.json
See:
https://github.com/aws/serverless-application-model/blob/5e3741c05f0635135469b15db5a2feabdd263440/samtranslator/model/eventsources/push.py#L948-L957
=> chore: tighter schema type for RestApiId

samtranslator/model/api/api_generator.py, samtranslator/model/eventsources/push.py, samtranslator/model/stepfunctions/events.py, samtranslator/open_api/base_editor.py, samtranslator/open_api/open_api.py, samtranslator/plugins/globals/globals.py, samtranslator/swagger/swagger.py
These two classes share so many same code, making it tedious to sync the code fixes.
Move the same methods into their super class. There are 2 methods that are not shared `validate_path_item_is_dict` and `validate_is_dict` but I think it will be useful in `OpenApiEditor` as well as it is generic.
=> chore: Refactor OpenApiEditor and SwaggerEditor to reduce duplicate code

samtranslator/open_api/base_editor.py, samtranslator/open_api/open_api.py, samtranslator/swagger/swagger.py, tests/translator/output/error_http_api_null_method.json, tests/translator/output/error_invalid_method_definition.json, tests/translator/output/error_null_method_definition.json
`get_conditional_contents` returns `List[Any]`, and we often treats them as list of dicts and perform `.get()`, `.items()` or `.keys()`. It happens to path item and method item, so this PR add validation to all of them
=> fix: Raise correct exception when path/method items from get_conditional_contents are not dict

samtranslator/swagger/swagger.py, tests/swagger/test_swagger.py, tests/translator/input/api_model_without_properties.yaml, tests/translator/output/api_model_without_properties.json, tests/translator/output/aws-cn/api_model_without_properties.json, tests/translator/output/aws-us-gov/api_model_without_properties.json
#1559 
JSON schema doesn't require `properties` at the top-level, see e.g. https://json-schema.org/understanding-json-schema/reference/array.html#items.
=> fix: allow `Api` model without `properties`

integration/resources/templates/combination/intrinsics_serverless_function.yaml
Node 12.x is not supported in some regions; AWS recommends 16.x so updating to use that.
Updates node.js version used in intrinsics integration test
=> chore: Update node.js version in test

samtranslator/model/apigateway.py, tests/translator/input/error_api_gateway_responses_responseparameter_invalid_type.yaml, tests/translator/output/error_api_gateway_responses_responseparameter_invalid_type.json
=> fix: Raise correct exception when "ResponseParameters" is not dict

samtranslator/model/sam_resources.py, tests/translator/input/error_function_with_event_dest_type.yaml, tests/translator/output/error_function_with_event_dest_type.json
=> fix: Raise correct exception when DestinationConfig or DestinationConfig.x is not dict

samtranslator/model/eventsources/push.py, tests/translator/input/error_s3_bucket_invalid_properties.yaml, tests/translator/output/error_s3_bucket_invalid_properties.json
=> fix: Raise correct exception when S3 event referring to a bucket whose properties is not dict

samtranslator/third_party/py27hash/hash.py, samtranslator/utils/py27hash_fix.py
Profiling indicated that we spend a lot of time in our custom deepcopy, mostly due to maintaining compatibility with python2.7 hashes and their ordering of keys. If we change the ordering of keys, we will change logical IDs of some generated resources, breaking backwards compatibility.
We found that during the hashing code, we made some 13MM calls to Hash.hash, but with caching this is reduced to 1040 calls for a large test template.
On my laptop, this reduces wall clock time from ~15s to ~13s, or ~34s to ~27s with cProfiler.
By submitting this pull request, I confirm that my contribution is made …
=> Add a cache on top of python27 hashing

integration/combination/test_http_api_with_fail_on_warnings.py, integration/resources/expected/combination/http_api_with_fail_on_warnings_and_default_stage_name.json, integration/resources/templates/combination/http_api_with_fail_on_warnings_and_default_stage_name.yaml, integration/resources/templates/combination/intrinsics_serverless_function.yaml, samtranslator/model/api/http_api_generator.py, tests/translator/output/aws-cn/explicit_http_api.json, tests/translator/output/aws-cn/http_api_explicit_stage.json, tests/translator/output/aws-cn/http_api_with_default_stage_name_and_fail_on_warnings.json, tests/translator/output/aws-us-gov/explicit_http_api.json, tests/translator/output/aws-us-gov/http_api_explicit_stage.json, tests/translator/output/aws-us-gov/http_api_with_default_stage_name_and_fail_on_warnings.json, tests/translator/output/explicit_http_api.json, tests/translator/output/http_api_explicit_stage.json, tests/translator/output/http_api_with_default_stage_name_and_fail_on_warnings.json
https://github.com/aws/serverless-application-model/issues/2297
Before the change, when we turn on `FailOnWarnings` flag and use a default stage name, the deployment will fail because it will generate a warning saying 
```
Warnings found during import: Parse issue: attribute paths. 
Resource $default should start with / 
```
Added integ test and ran all unit tests.
=> Fix warning when using default stage name and FailOnWarnings is on

samtranslator/model/eventsources/push.py, tests/translator/input/error_http_api_with_invalid_auth_while_method_auth_is_none.yaml, tests/translator/output/error_http_api_with_invalid_auth_while_method_auth_is_none.json
=> fix: Handle when httpapi Auth could be null

samtranslator/open_api/base_editor.py, tests/translator/input/error_api_with_invalid_if_condition_swagger.yaml, tests/translator/output/error_api_with_invalid_if_condition_swagger.json
=> fix: Raise correct exception when Fn::If value is not a list

samtranslator/swagger/swagger.py, tests/translator/output/aws-cn/api_request_model_openapi_3.json, tests/translator/output/aws-cn/api_swagger_integration_with_ref_intrinsic_api_id.json, tests/translator/output/aws-cn/api_swagger_integration_with_string_api_id.json, tests/translator/output/aws-cn/api_with_aws_iam_auth_overrides.json, tests/translator/output/aws-cn/api_with_default_aws_iam_auth.json, tests/translator/output/aws-cn/api_with_default_aws_iam_auth_and_no_auth_route.json, tests/translator/output/aws-cn/api_with_method_aws_iam_auth.json, tests/translator/output/aws-us-gov/api_request_model_openapi_3.json, tests/translator/output/aws-us-gov/api_swagger_integration_with_ref_intrinsic_api_id.json, tests/translator/output/aws-us-gov/api_swagger_integration_with_string_api_id.json, tests/translator/output/aws-us-gov/api_with_aws_iam_auth_overrides.json, tests/translator/output/aws-us-gov/api_with_default_aws_iam_auth.json, tests/translator/output/aws-us-gov/api_with_default_aws_iam_auth_and_no_auth_route.json, tests/translator/output/aws-us-gov/api_with_method_aws_iam_auth.json
https://github.com/aws/serverless-application-model/issues/1667
Caller credentials defaults to use hardcoded partition. It doesn't work in US Gov or CN regions.
All unit tests file updated and ran successfully.
=> Update caller credential partition

DEVELOPMENT_GUIDE.md
We no longer support 3.6, and we added support to 3.10
Picked versions based on https://www.python.org/downloads/
=> Update DEVELOPMENT_GUIDE.md to use modern python

samtranslator/intrinsics/actions.py, tests/intrinsics/test_actions.py, tests/translator/input/error_invalid_mapping_by_findinmap.yaml, tests/translator/output/error_invalid_mapping_by_findinmap.json
**I want to use `dict_deep_get()` but it doesn't have the same behavior here.**
=> fix: Raise correct exception FindInMap used on parameters not a 2-level-map

samtranslator/model/eventsources/push.py, tests/translator/input/error_s3_bucket_invalid_properties.yaml, tests/translator/output/error_s3_bucket_invalid_properties.json
=> fix: Raise correct exception when bucket tags are not list

samtranslator/intrinsics/resolver.py, samtranslator/policy_template_processor/template.py, tests/policy_template_processor/test_template.py, tests/translator/input/policy_template_import_vaule_refs_parameters_with_same_name_as_policy_parameter.yaml, tests/translator/output/aws-cn/policy_template_import_vaule_refs_parameters_with_same_name_as_policy_parameter.json, tests/translator/output/aws-us-gov/policy_template_import_vaule_refs_parameters_with_same_name_as_policy_parameter.json, tests/translator/output/policy_template_import_vaule_refs_parameters_with_same_name_as_policy_parameter.json
…the parameter refs a CFN parameter with the same name
=> fix: Prevent infinite recursion when resolving policy parameter when the parameter refs a CFN parameter with the same name

integration/combination/test_function_with_kinesis.py, integration/resources/expected/combination/function_with_kinesis.json, integration/resources/templates/combination/function_with_kinesis.yaml, samtranslator/model/eventsources/pull.py, samtranslator/model/lambda_.py, samtranslator/schema/aws_serverless_function.py, samtranslator/schema/schema.json, tests/translator/input/function_with_kinesis_with_start_time_timestamp.yaml, tests/translator/output/aws-cn/function_with_kinesis_with_start_time_timestamp.json, tests/translator/output/aws-us-gov/function_with_kinesis_with_start_time_timestamp.json, tests/translator/output/function_with_kinesis_with_start_time_timestamp.json
https://github.com/aws/serverless-application-model/issues/2754
Verified that CFN now supports `AT_TIMESTAMP` as one of the possible value for [StartingPosition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-startingposition)
If we support `AT_TIMESTAMP`, we also need to support [StartingPositionTimestamp](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-startingpositiontimestamp)
Added transform and integration tests
By …
=> Add support for AT_TIMESTAMP and StartingPositionTimestamp

Makefile, samtranslator/policy_templates_data/policy_templates.json
None I can find
The policy_templates.json has many formatting discrepancies. For example 
CloudWatchDescribeAlarmHistoryPolicy has 
```json
"Parameters": {},
``` 
where as others have a empty block with white space
```json
"Parameters": {
},
```
RekognitionFacesManagementPolicy has not been formated with array object like other Statement objects
```json
"Statement": [{
"Effect": "Allow",
"Action": [
"rekognition:IndexFaces",
"rekognition:DeleteFaces",
"rekognition:SearchFaces",
"rekognition:SearchFacesByImage",
"rekognition:ListFaces"
],
```
policy_templates.json is still valid JSON 
```sh
cat samtranslator/policy_templates_data/policy_templates.json | jq .
```
added to `sam init` through …
=> Format policy_templates.json

samtranslator/open_api/open_api.py, samtranslator/swagger/swagger.py
=> chore: Add cw_timer to deepcopy in SwaggerEditor and OpenApiEditor

samtranslator/translator/translator.py
Spot an unecessary deepcopy on the entire SAM Function resource dict despite only the property "FunctionName" can be potentially mutated by `resolve_parameter_refs`.
Only to deepcopy the part we don't want to mutate.
Tested on a template with a single function with 411 `Api` event sources. Transform time is reduced from 45s to 36s (**20.7%** improvement)
```
before: 39.48s user 0.49s system 87% cpu 45.437 total
after: 30.83s user 0.53s system 86% cpu 36.140 total
```
=> chore: Optimize the use of deepcopy in Translator._get_function_names()

samtranslator/model/eventsources/pull.py, tests/translator/output/error_missing_broker.json, tests/translator/output/error_missing_queue.json, tests/translator/output/error_missing_startingposition.json, tests/translator/output/error_missing_stream.json
When I am using DynamoDB event, the mentioning of "MSK" in the error message is not helpful.
=> chore: Move some PullEventSource validations to subclasses

samtranslator/translator/arn_generator.py, tests/translator/test_arn_generator.py, tests/translator/test_resource_level_attributes.py, tests/translator/test_translator.py, tests/unit/translator/test_arn_generator.py
Tested on a template with 411 Api event sources. By looking at the profile result, `get_partition_name()` is called 824 times, making up 10.76s (out of 47s, ~23%).
```
824	0.004326	5.25e-06	10.76	0.01306	arn_generator.py:38(get_partition_name)
```
After this change, it only called **twice** and only took 0.01s.
```
2 | 1.1e-05 | 5.5e-06 | 0.01354 | 0.006768 | arn_generator.py:40(get_partition_name)
```
this brought down the time from 47s to 40s (the duration fluctuates so it doesn't have exact 10.76s difference).
By submitting this pull request, I confirm that my contribution is made under the terms …
=> chore: Cache get_partition_name to reduce transform latency

integration/resources/templates/combination/api_with_authorizer_apikey.yaml
In some AWS regions, Fn::GetAtt Key.APIKeyId does not work, but Ref: Key also returns the API Key ID and seems to work even in these regions.
Manually deployed minimally modified [test template](https://github.com/aws/serverless-application-model/blob/develop/integration/resources/templates/combination/api_with_authorizer_apikey.yaml) in ap-southeast-4 both with and without this change; with change the stack deploys successfully and without, we see:
```
Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: resource MyFirstApiKey does not support attribute type APIKeyId in Fn::GetAtt
```
Please reach out in the comments if you want to add an example. Examples …
=> Replace Fn::GetAtt Key.APIKeyId with Ref: Key

.coveragerc, samtranslator/metrics/metrics.py, samtranslator/model/__init__.py, samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/plugins/api/implicit_api_plugin.py, tests/test_model.py
Remove NotImplemented error and turn these classes into abstract classes.
=> Remove not implemented methods

samtranslator/model/api/api_generator.py, samtranslator/model/apigateway.py, samtranslator/model/eventsources/push.py, samtranslator/model/stepfunctions/events.py, tests/translator/output/error_api_mtls_configuration_invalid_field.json, tests/translator/output/error_api_mtls_configuration_invalid_type.json
=> chore: Remove all # type: ignore[attr-defined]

samtranslator/intrinsics/actions.py, samtranslator/intrinsics/resolver.py, samtranslator/model/connector/connector.py, tests/intrinsics/test_actions.py
=> chore: Adding more type hints

MANIFEST.in, Makefile, samtranslator/schema/sam.schema.json, tests/schema/test_validate_schema.py
Renames `schema.json` to `sam.schema.json`, and `unified.schema.json` to `schema.json`.
The unified schema is the "main" schema; e.g. we're adding resource attributes to non-SAM resources in https://github.com/aws/serverless-application-model/pull/2772 so we need control over the CloudFormation schema as well.
=> chore: make unified schema the default

samtranslator/schema/sam.schema.json, samtranslator/schema/schema.py
=> fix: better property title

samtranslator/plugins/__init__.py, tests/test_plugins.py
In https://github.com/aws/serverless-application-model/commit/ff75c8afd0579f124c06e48f187cadf02e3e1682#diff-a5c7f4a8324ba62f991e6b2846fd0ac4e85894b65143a3e61430fc7080a3567eR23-L30 we removed the required `name` argument of `BasePlugin` constructor. It might break whoever is consuming SAM-T library. This PR brings it back as an optional argument.
=> chore: Add back argument "name" to BasePlugin for compatibility

Makefile
=> ci: mypy/pylint/format schema_source package

integration/combination/test_connectors.py, integration/helpers/resource.py, integration/resources/templates/combination/connector_function_to_location_place_index.yaml
Shorten place index length to fix tests failure.
=> Revert last change and Re-add location exclusion in connector tests 

Makefile, bin/json-format.py, requirements/dev.txt, ruff.toml, samtranslator/model/__init__.py, samtranslator/model/api/api_generator.py, samtranslator/model/eventsources/pull.py, samtranslator/model/sam_resources.py, schema_source/any_cfn_resource.py
ruff (https://github.com/charliermarsh/ruff) is extremely fast and covers a lot of lint rules from different linters.
Our pylint check is very slow.
=> ci: (experimental) Add ruff before pylint to lint the codebase

bin/json-format.py, requirements/dev.txt, ruff.toml
I believe the rule "too-many-args" is still valuable but adding `noqa` to them all is tedious. Excluding at the file level is easier to do
=> ci: Upgrade ruff to 0.0.239

docs/schema.md
Some barebones overview of how the schema is generated.
=> docs: schema generation

README.md
=> docs: add workshop

bin/parse_docs.py
Some minor filtering when parsing CFN docs to ensure identifier matches expected format.
=> chore: filter CFN docs

bin/public_interface.py
This command allows extraction of all public interfaces into a file. This allows us to compare two files to determine if there is a compatibility-breaking changes.
```
bin/public_interface.py extract out.json
```
Snippet of generated JSON file:
```
{
"constants": [
"samtranslator.feature_toggle.feature_toggle.BOTO3_CONNECT_TIMEOUT",
"samtranslator.intrinsics.resolver.DEFAULT_SUPPORTED_INTRINSICS",
"samtranslator.model.api.api_generator.GatewayResponseProperties",
"samtranslator.model.api.http_api_generator.DefaultStageName",
"samtranslator.model.api.http_api_generator.HttpApiTagName",
"samtranslator.model.apigatewayv2.APIGATEWAY_AUTHORIZER_KEY",
"samtranslator.model.architecture.ARM64",
"samtranslator.model.architecture.X86_64",
"samtranslator.model.connector_profiles.profile.PROFILE", …
```
=> ci: Add public_interface command

bin/add_transform_test.py, bin/sam-translate.py, requirements/dev.txt
Useless dependency, and warnings at installation.
```
% python bin/sam-translate.py --template-file tests/translator/input/connector_esm_dependson.yaml
Wrote transformed CloudFormation template to: transformed-template.yaml
```
```
% python bin/add_transform_test.py --template-file foo.yaml
Transform Test input file generated /Users/rehnc/Desktop/schemastuff/serverless-application-model/bin/../tests/translator/input/foo.yaml
Wrote transformed CloudFormation template to: /var/folders/8p/907sv7jd1673mkdw5b609_992s40z7/T/tmpboomgz8l
Transform Test output files generated /Users/rehnc/Desktop/schemastuff/serverless-application-model/bin/../tests/translator/output/aws-cn/foo.json
Transform Test output files generated /Users/rehnc/Desktop/schemastuff/serverless-application-model/bin/../tests/tran …
```
=> chore: remove docopt

bin/public_interface.py, tests/bin/test_public_interface.py
Why print markdown? So we can forward the output and present it in PR comment. 
```
❯❯❯ bin/public_interface.py check out.json new.json
Compatibility breaking changes detected!!!
** These changes are considered breaking changes and may break packages consuming
aws-sam-translator on pypi.
Please consider revisiting these changes to make sure they are intentional:**
- samtranslator.model.sam_resources.IMAGE
- samtranslator.model.sam_resources.X86_64
- samtranslator.model.sam_resources.ZIP
- samtranslator.model.stepfunctions.events.CONDITION
- samtranslator.model.stepfunctions.events.SFN_EVETSOURCE_METRIC_PREFIX
- samtranslator.plugins.api.implicit_api_plugin.MIN_NUM_CONDITIONS_TO_COMBINE
- samtranslator.plugins.application.serverless_app_plugin.BOTO3_CONNECT_TIMEOUT
- …
```
=> ci: Add public interface command check

bin/sam-translate.py
Fixes https://github.com/aws/serverless-application-model/issues/2873
Removed in https://github.com/aws/serverless-application-model/pull/2865.
```
% python3 -m venv .venv && source .venv/bin/activate
% pip install -r serverless-application-model/requirements/base.txt
% pip install pyyaml
% python serverless-application-model/bin/sam-translate.py --template-file foo.yaml --output-template bar.yaml
Wrote transformed CloudFormation template to: bar.yaml
```
=> fix(sam-translate.py): add samtranslator to path

LICENSE
Before:
After (see https://github.com/hoffa/serverless-application-model):
The `{}` come from the original commit, where the date/name placeholders were delimited with them:
https://github.com/aws/serverless-application-model/blob/38b4a782bd42e2a51f202a50bb6abea2e317d6a8/LICENSE#L189
However the original Apache-2.0 license (at the time of checking) uses square brackets: https://www.apache.org/licenses/LICENSE-2.0.txt
=> fix: recognize license

bin/public_interface.py
`ConnectorResourceReference` was not detected in https://github.com/aws/serverless-application-model/pull/2878/
=> ci: Fix interface scan omits types (e.g., ConnectorResourceReference)

tests/translator/input/basic_layer.yaml, tests/translator/output/aws-cn/basic_layer.json, tests/translator/output/aws-us-gov/basic_layer.json, tests/translator/output/basic_layer.json
Bring the change from https://github.com/aws/aws-sam-cli/pull/4672 to SAM-T
=> chore: Remove outdated CompatibleRuntimes in basic_layer.yaml (from sam-cli#4672)

samtranslator/internal/__init__.py, samtranslator/internal/deprecation_control.py, samtranslator/model/types.py, tests/internal/test_deprecation_control.py
Create a file "bin/test_deprecation.py" with the content:
```py
from samtranslator.model.types import is_str
if __name__ == "__main__":
is_str()("hi")
```
Then:
```sh
(samtranslator37) ~/P/serverless-application-model ❯❯❯ python bin/test_deprecation.py
bin/test_deprecation.py:4: DeprecationWarning: is_str is deprecated, please consider to use IS_STR
is_str()("hi")
```
=> chore: Add decorator @deprecated and add it to is_str()

requirements/dev.txt, samtranslator/feature_toggle/feature_toggle.py, samtranslator/metrics/method_decorator.py, samtranslator/model/__init__.py, samtranslator/model/api/http_api_generator.py, samtranslator/model/eventsources/scheduler.py, samtranslator/model/sam_resources.py, tests/test_model.py
mypy 1.0.0 is [launched](https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html), with 40% faster!
=> chore: Upgrade mypy to 1.0.0 and type hint cw_timer

samtranslator/internal/deprecation_control.py, samtranslator/metrics/method_decorator.py
https://peps.python.org/pep-0612/
=> chore: Use ParamSpec from PEP 612

integration/helpers/deployer/exceptions/exceptions.py, integration/helpers/deployer/utils/colors.py, integration/helpers/deployer/utils/table_print.py, requirements/dev.txt
=> chore: Remove click from dev.txt

Makefile
```
pytest --no-cov integration/*                                                                                                                          ✘ 2 
=============================================================================================== test session starts ===============================================================================================
platform darwin -- Python 3.7.2, pytest-6.2.5, py-1.9.0, pluggy-0.13.1
rootdir: /Users/xinhol/Projects/serverless-application-model, configfile: pytest.ini
plugins: xdist-2.5.0, rerunfailures-9.1.1, env-0.6.2, cov-2.10.1, forked-1.3.0
collected 0 items …
```
=> chore: Fix make integ-test as integration contains non-py files

integration/helpers/base_test.py, samtranslator/region_configuration.py
N/A
Changes how we fetch AWS parittion name from region to be consistent across code base.
Integration tests, unit tests
=> Use consistent method of determining AWS Partition from a region

tests/model/api/test_http_api_generator.py
`self.route53_record_set_groups` is mutated in unit tests and could cause undefined test failures if they are executed sequentially. 
Run the test in a single runner. 
=> fix: Fix TestCustomDomains unit tests have side effect on others

integration/resources/templates/combination/connector_function_to_eventbus_write.yaml
Hardcoding resource name could prevent future tests from running when previous ones are not cleaned up properly. This PR reduces such risk.
=> fix: Avoid hardcoded eventbus name in integ test

integration/helpers/base_test.py, samtranslator/region_configuration.py
I missed a spot when removing partition attribute from BaseTest in 59dd0d827db12d5dfe385ae851907c1b07a251f7; adds it back using ArnGenerator for consistency. 
=> fix: Add partition attribute to BaseTest

.cfnlintrc.yaml, samtranslator/model/sam_resources.py, samtranslator/translator/managed_policy_translator.py, samtranslator/translator/transform.py, samtranslator/translator/translator.py, tests/translator/input/managed_policies_minimal.yaml, tests/translator/output/aws-cn/managed_policies_minimal.json, tests/translator/output/aws-us-gov/managed_policies_minimal.json, tests/translator/output/managed_policies_minimal.json
Preliminary changes to make https://github.com/aws/serverless-application-model/pull/2839 easier to review.
=> refactor: preliminary changes for managed policy improvements

samtranslator/model/lambda_.py, tests/translator/input/function_string_memorysize.yaml, tests/translator/output/aws-cn/function_string_memorysize.json, tests/translator/output/aws-us-gov/function_string_memorysize.json, tests/translator/output/function_string_memorysize.json
A customer is reporting `AWS::Lambda::Function` supports string-type integers for memory size but `AWS::Serverless::Function` doesn't support it. So it's time to get rid of the property validations.
Deploying the transformed templates.
=> Remove property validations for lambda resources

samtranslator/model/apigateway.py, samtranslator/model/apigatewayv2.py, samtranslator/model/cloudformation.py, samtranslator/model/codedeploy.py, samtranslator/model/cognito.py, samtranslator/model/dynamodb.py, samtranslator/model/events.py, samtranslator/model/iam.py, samtranslator/model/iot.py, samtranslator/model/log.py, samtranslator/model/route53.py, samtranslator/model/s3.py, samtranslator/model/scheduler.py, samtranslator/model/sns.py, samtranslator/model/sqs.py
`PropertyType` checks the type at runtime, which means there's a risk (as we've already observed) of us failing to transform a valid template. Also it adds overhead.
Instead, using `GeneratedProperty()` there are no runtime checks. We should instead rely on regular types and testing to make sure what we generate is correct.
=> chore: replace generated properties by GeneratedProperty()

bin/parse_docs.py, requirements/dev.txt, samtranslator/model/api/api_generator.py, samtranslator/model/api/http_api_generator.py, samtranslator/open_api/open_api.py, samtranslator/third_party/py27hash/hash.py, samtranslator/translator/translator.py, samtranslator/utils/py27hash_fix.py
ruff adds a new rule that catches these:
```
bin/parse_docs.py:95:13: PLW2901 Outer for loop variable `description` overwritten by inner assignment target
bin/parse_docs.py:96:13: PLW2901 Outer for loop variable `description` overwritten by inner assignment target
bin/parse_docs.py:102:13: PLW2901 Outer for loop variable `description` overwritten by inner assignment target
samtranslator/model/api/api_generator.py:524:17: PLW2901 Outer for loop variable `basepath` overwritten by inner assignment target
samtranslator/model/api/http_api_generator.py:405:17: PLW2901 Outer for loop variable `path` overwritten by inner assignment target
samtranslator/open_api/open_api.py:222:21: PLW2901 Outer for loop variable `param` overwritten by inner assignment target …
```
=> chore: Batch update dev dependencies

integration/resources/expected/combination/connector_appsync_to_table.json, integration/resources/templates/combination/connector_appsync_to_table.yaml
I initially didn't run the integ test and forgot to include the list of required resources.
Running integ test for AppSync -> DDB connector
=> fix: appsync-ddb connector integ tests

bin/sam-translate.py, samtranslator/feature_toggle/feature_toggle.py, samtranslator/metrics/method_decorator.py, samtranslator/metrics/metrics.py, samtranslator/parser/parser.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/plugins/policies/policy_templates_plugin.py, samtranslator/region_configuration.py, samtranslator/sdk/parameter.py, samtranslator/translator/arn_generator.py, samtranslator/translator/managed_policy_translator.py, samtranslator/translator/transform.py, samtranslator/translator/translator.py, samtranslator/utils/py27hash_fix.py
=> chore: Remove "type: ignore" in samtranslator/translator

integration/resources/expected/combination/connector_appsync_to_table.json, integration/resources/templates/combination/connector_appsync_to_table.yaml
=> Downgrade TriggerFunction node to v14 because 18 is not available in all regions

samtranslator/model/iam.py, samtranslator/model/stepfunctions/events.py
Add typing to `construct_assume_role_policy_for_service_principal()`. Removed `# type: ignore` comments.
Passes `make pr`.
=> chore: add stricter typing to construct assume role policy function

samtranslator/model/events.py, samtranslator/model/eventsources/push.py, samtranslator/model/stepfunctions/events.py, tests/translator/input/event_bridge_rule_super_long_id.yaml, tests/translator/output/aws-cn/event_bridge_rule_super_long_id.json, tests/translator/output/aws-us-gov/event_bridge_rule_super_long_id.json, tests/translator/output/event_bridge_rule_super_long_id.json
https://github.com/aws/serverless-application-model/issues/2941
According to the `Id` property in this documentation https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Target.html, the max length is 64. Truncate it if it's too long.
=> fix: Truncate Event Bridge Rule if Id is over 64 characters

samtranslator/plugins/globals/globals.py, tests/translator/input/api_merge_definitions_global.yaml, tests/translator/output/api_merge_definitions_global.json, tests/translator/output/aws-cn/api_merge_definitions_global.json, tests/translator/output/aws-us-gov/api_merge_definitions_global.json, tests/translator/output/error_globals_api_with_stage_name.json
Add merge definitions to global and add transform tests
Already added MergeDefinitions property to our schema in the previous PR #2943. However, I never added support or tests related for globals, so in schema it says we support MergeDefinitions as a global, but we actually don't. Fixing it.
=> fix: Add MergeDefinitions property to Global Section

samtranslator/internal/intrinsics.py, samtranslator/model/__init__.py, samtranslator/model/sam_resources.py, schema_source/sam.schema.json, tests/test_import.py
#2975
`samtranslator.models.__init__` should not import `samtranslator.intrinsics.*` which in turn import `samtranslator.models.__init__`
Added a new import test, without the fix, it will fail:
=> fix: Decouple samtranslator.models and *.intrinsics and add import tests

bin/parse_docs.py, bin/public_interface.py, requirements/dev.txt, ruff.toml, samtranslator/feature_toggle/dialup.py, samtranslator/feature_toggle/feature_toggle.py, samtranslator/metrics/metrics.py, samtranslator/model/__init__.py, samtranslator/model/exceptions.py, samtranslator/model/resource_policies.py, samtranslator/plugins/application/serverless_app_plugin.py, samtranslator/plugins/globals/globals.py, samtranslator/plugins/globals/globals_plugin.py, samtranslator/policy_template_processor/exceptions.py, samtranslator/policy_template_processor/processor.py, samtranslator/policy_template_processor/template.py, samtranslator/sdk/parameter.py, samtranslator/validator/validator.py
An arbitrary change to trigger something
For the auto fix:
```
>>> "#\s+Properties" == "#\\s+Properties"
True
```
=> ci: Upgrade ruff to 0.0.253 and enable more rules

samtranslator/model/eventsources/pull.py, samtranslator/model/eventsources/push.py, samtranslator/model/sam_resources.py, samtranslator/model/stepfunctions/events.py, samtranslator/model/types.py, tests/test_types.py
Adding type check `IS_BOOL`, `IS_INT` and `IS_LIST`
=> chore: adding some type checks as constants

setup.py
We test on 3.11 since https://github.com/aws/serverless-application-model/pull/2991.
=> chore: add Python 3.11 to classifiers

.cfnlintrc.yaml
Notice workflow failure in https://github.com/aws/serverless-application-model/pull/2998. At glance, the parameters are used, so I'm not sure what `cfn-lint` is complaining about. In any case, the rule is of no meaningful consequence, so getting rid of some red tape.
=> ci: ignore unused parameter cfn-lint rule

integration/combination/test_function_with_sns.py
=> chore: Add skip_using_service_detector to sns integ tests

requirements/dev.txt, samtranslator/internal/schema_source/any_cfn_resource.py
=> chore: Upgrade ruff to 0.0.254

integration/combination/test_api_settings.py, integration/conftest.py, integration/helpers/base_test.py, integration/helpers/deployer/utils/artifact_exporter.py, integration/helpers/resource.py, integration/helpers/stack.py
=> chore: Get rid of py2 import stuff

integration/resources/templates/combination/api_with_cors_and_apikey.yaml
Changed AWS to ${AWS::Partition}
=> fix: integration test cors_with_apikey_and_cors

requirements/base.txt, samtranslator/internal/deprecation_control.py, samtranslator/metrics/method_decorator.py, samtranslator/metrics/metrics.py, samtranslator/model/eventsources/pull.py
I had to dig through usage to understand what `dimensions` looks like. Adding `MetricDimension` and other types.
=> chore: Add type to metrics code and deprecate CWMetricsPublisher

bin/public_interface.py
See #3026, an example of unnecessary workflow failure
=> ci: Exclude samtranslator.internal from interface scan

Makefile
N/A
Run `make test-cov-report` in parallel (related PR: [#2222](https://github.com/aws/serverless-application-model/pull/2222)). Time to run test on my M1 macbook goes from 211 seconds to 48 seconds (~80% reduction). 
Also added command to automatically open html coverage report (for macs) which gives a better UI for seeing which parts of the codebase are covered through tests and which are missing.
=> chore: run test coverage command in parallel

samtranslator/model/cognito.py, tests/translator/input/cognito_user_pool_with_new_property_and_cognito_event.yaml, tests/translator/output/aws-cn/cognito_user_pool_with_new_property_and_cognito_event.json, tests/translator/output/aws-us-gov/cognito_user_pool_with_new_property_and_cognito_event.json, tests/translator/output/cognito_user_pool_with_new_property_and_cognito_event.json
https://github.com/aws/serverless-application-model/issues/2581
This is a quick fix to the issue, but we should fix the root cause which is that it validates the resource specified by a customer (see https://github.com/aws/serverless-application-model/issues/2581#issuecomment-1474422567). So this will keep happening for every new property. I'm toying with a longer-term fix in https://github.com/aws/serverless-application-model/pull/3040.
=> fix: add `DeletionProtection` to `AWS::Cognito::UserPool`

.cfnlintrc.yaml, integration/combination/test_function_with_mq.py, tests/translator/input/function_with_mq.yaml, tests/translator/output/aws-cn/function_with_mq.json, tests/translator/output/aws-us-gov/function_with_mq.json, tests/translator/output/function_with_mq.json
Pipeline failure due to MQ integ test failed.
```
Availability Zone [eu-central-1a] of requested subnet [subnet-0c75dfefaf31287d0] does not support broker instance type [mq.t3.micro]. Specify a subnet in a different Availability Zone. (Service: AmazonMQInternal; Status Code: 400; Error Code: BadRequestException; Request ID: 5e8bff7d-9412-4263-a8ce-e3997b90e941; Proxy: null)
```
Temporarily disable the test and add it as a transform test.
=> fix: Skip MQ Integ Test and add it to Transform Test

samtranslator/model/__init__.py, tests/model/test_resource.py
In the `Resource` class, we have an override on `__setattr__` that checks if the attribute that is being modified is in the `property_types` dictionary or `_keywords` set (logical_id, relative_id, etc...).
Because of this, we cannot create class variables that can be modified after initialization. An example of why this can be annoying for developers is if you have a state that you would like to track throughout the class, you must do so internally with a local variable. This change adds a new boolean attribute to `Resource`, `validate_setattr`. If set to True (which is default value), then validation will be performed as normal. When it's false, it will bypass the `property_types` and `_keywords` check and allow you to modify other class variables without trouble.
Added unit tests where …
=> feat: allow classes that inherit Resource to disable __setattr__ validation

samtranslator/internal/schema_source/aws_serverless_function.py, samtranslator/internal/schema_source/common.py, samtranslator/internal/schema_source/schema.py, schema_source/sam.schema.json, tests/schema/test_validate_schema.py
Scaffolding to partly address limitation (3) in https://github.com/aws/serverless-application-model/discussions/2645:
> Pass-through values are not validated. Pass-through properties (e.g. [AccessLogSettings](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html#sam-httpapi-accesslogsettings)) are passed directly to underlying CloudFormation resources.
So instead of using the documentation from SAM, for pass-through properties we use the documentation straight from the source: from the actual property being passed-through to.
This means pass-through properties get accurate types, even for nested pass-throughs. Previously it would accept anything.
Used schema modeline in VS Code, played around with templates that previously wouldn't have …
=> feat: scaffolding for improved pass-throughs in schema

samtranslator/internal/schema_source/aws_serverless_function.py, samtranslator/internal/schema_source/schema.py, schema_source/sam.schema.json
A couple more. Shows nicely how it works when properties pass-through to various resources and mismatching property names.
=> chore: more improved schema pass-throughs

samtranslator/model/eventsources/push.py, tests/translator/input/api_merge_definitions_with_any_method.yaml, tests/translator/output/api_merge_definitions_with_any_method.json, tests/translator/output/aws-cn/api_merge_definitions_with_any_method.json, tests/translator/output/aws-us-gov/api_merge_definitions_with_any_method.json
There is a new availability dip that happens because customers input `ANY/any/Any` for event source API methods. In the SAM generated open api definition, we will create a `x-amazon-apigateway-any-method`. 
This caused an availability dip because we're looking for `any` in dictionary and keyError happened. Fix it.
=> fix: Fix availability dip from API MergeDefinitions property

bin/run_cfn_lint.sh
Prevents issues where e.g. using same venv for a while and `cfn-lint` is updated, but it won't try to install it again, causing checks to fail.
Checked it's "pretty fast" to run it every time, so no significant impact on duration.
=> chore: improve cfn-lint install

samtranslator/internal/schema_source/aws_serverless_api.py, samtranslator/internal/schema_source/aws_serverless_function.py, samtranslator/internal/schema_source/common.py, samtranslator/internal/schema_source/schema.py, schema_source/sam.schema.json
Had to change how the pass-through schema is referenced, as it's not as nicely consistent as I initially expected.
The end change is in `schema.json`.
=> chore: more improved pass-through schemas

samtranslator/model/connector/connector.py, tests/translator/input/connector_with_non_id_source_and_destination.yaml, tests/translator/output/aws-cn/connector_with_non_id_source_and_destination.json, tests/translator/output/aws-us-gov/connector_with_non_id_source_and_destination.json, tests/translator/output/connector_with_non_id_source_and_destination.json
There is a connector bug when using `RoleName` + `Type`.
```
MyReadConnector:
Type: AWS::Serverless::Connector
Properties:
Source:
RoleName: MyRole
Destination:
Id: MyTable
Permissions:
- Read
```
Because we didn't input `Id`, it will directly use `Type` and try to find a profile using `AWS::Serverless::Function` to `AWS::DynamoDB::Table`. It will fail because not such profile is found. We should be using `AWS::lambda::Function` instead.
Added tests
=> fix: Connector "Type" cannot be Serverless resource types

samtranslator/model/connector/connector.py
This change will get rid of `str()` casting without these errors:
```
samtranslator/model/connector/connector.py:151: error: Argument 2 to "_get_resource_arn" has incompatible type "Optional[Any]"; expected "str"  [arg-type]
samtranslator/model/connector/connector.py:153: error: Argument 3 to "_get_resource_role_name" has incompatible type "Optional[Any]"; expected "str"  [arg-type]
samtranslator/model/connector/connector.py:155: error: Argument 2 to "_get_resource_queue_url" has incompatible type "Optional[Any]"; expected "str"  [arg-type]
samtranslator/model/connector/connector.py:157: error: Argument 2 to "_get_resource_id" has incompatible type "Optional[Any]"; expected "str"  [arg-type]
samtranslator/model/connector/connector.py:159: error: Argument 2 to "_get_resource_name" has …
```
=> chore: Use TypeGuard to avoid unncessary type casts

integration/resources/templates/combination/function_with_alias_and_event_sources.yaml, integration/resources/templates/combination/function_with_all_event_types.yaml, integration/resources/templates/combination/function_with_all_event_types_condition_false.yaml, integration/resources/templates/combination/function_with_dynamodb.yaml
We had policy engine risks about not enabling on-demand or auto-scaling mode on dynamodb tables. Enable them in integ tests.
Integ tests passed locally.
=> chore: Enable DynamoDB on demand mode

integration/resources/expected/combination/graphqlapi_pipeline_resolver.json, integration/resources/templates/combination/graphqlapi_pipeline_resolver.yaml, samtranslator/internal/schema_source/aws_serverless_graphqlapi.py, samtranslator/model/sam_resources.py, schema_source/sam.schema.json, tests/translator/input/error_graphqlapi.yaml, tests/translator/input/graphqlapi_ddb_datasource_all_properties.yaml, tests/translator/input/graphqlapi_ddb_datasource_connector.yaml, tests/translator/input/graphqlapi_function_datasource_property.yaml, tests/translator/input/graphqlapi_function_overwrite_resolver_code_settings.yaml, tests/translator/input/graphqlapi_function_use_resolver_code_settings.yaml, tests/translator/output/aws-cn/graphqlapi_ddb_datasource_all_properties.json, tests/translator/output/aws-cn/graphqlapi_ddb_datasource_connector.json, tests/translator/output/aws-cn/graphqlapi_function_datasource_property.json, tests/translator/output/aws-cn/graphqlapi_function_overwrite_resolver_code_settings.json, tests/translator/output/aws-cn/graphqlapi_function_use_resolver_code_settings.json, tests/translator/output/aws-us-gov/graphqlapi_ddb_datasource_all_properties.json, tests/translator/output/aws-us-gov/graphqlapi_ddb_datasource_connector.json, tests/translator/output/aws-us-gov/graphqlapi_function_datasource_property.json, tests/translator/output/aws-us-gov/graphqlapi_function_overwrite_resolver_code_settings.json, tests/translator/output/aws-us-gov/graphqlapi_function_use_resolver_code_settings.json, tests/translator/output/graphqlapi_ddb_datasource_all_properties.json, tests/translator/output/graphqlapi_ddb_datasource_connector.json, tests/translator/output/graphqlapi_function_datasource_property.json, tests/translator/output/graphqlapi_function_overwrite_resolver_code_settings.json, tests/translator/output/graphqlapi_function_use_resolver_code_settings.json
Modified how users define DataSources in `Serverless::GraphQLApi`. Now, all DataSources will be held under one parent property, `DataSources`, with specifier properties underneath for the specific ones (currently only `DynamoDb` is supported).
Modified transform tests and integration tests with new shape. Passes `make pr`.
=> fix: Change DataSource Shape

samtranslator/plugins/application/serverless_app_plugin.py, tests/plugins/application/test_serverless_app_plugin.py
Allow sar_client to be lazy created by passing a creator instead of sar client itself.
=> chore: Add sar_client_creator to ServerlessAppPlugin constructor

requirements/dev.txt, ruff.toml
=> chore: Upgrade ruff to 0.0.263 and enable more rules

integration/combination/test_graphqlapi_lambda_resolver.py, integration/resources/expected/combination/graphqlapi_lambda_resolver.json, integration/resources/templates/combination/graphqlapi_lambda_resolver.yaml
Added an integration test for `Serverless::GraphQLApi` that has a resolver which contains a function with a Lambda datasource.
Integration test runs successfully.
=> chore: integration test for Lambda resolver in Serverless::GraphQLApi

tests/translator/input/managed_policies_everything.yaml, tests/translator/output/aws-cn/managed_policies_everything.json, tests/translator/output/aws-us-gov/managed_policies_everything.json, tests/translator/output/managed_policies_everything.json
https://github.com/aws/serverless-application-model/issues/3152
Adding some tests to ensure we have better coverage of allowed values in `Policies`.
=> chore: add `Policies` test with every type

integration/combination/test_function_with_msk.py, tests/translator/input/function_with_msk_2.yaml, tests/translator/input/function_with_msk_using_managed_policy.yaml, tests/translator/output/aws-cn/function_with_msk_2.json, tests/translator/output/aws-cn/function_with_msk_using_managed_policy.json, tests/translator/output/aws-us-gov/function_with_msk_2.json, tests/translator/output/aws-us-gov/function_with_msk_using_managed_policy.json, tests/translator/output/function_with_msk_2.json, tests/translator/output/function_with_msk_using_managed_policy.json
Encountering flakiness every blue moon with this tests; added equivalent transform tests and marking as non-blocking since we've already tested it.
For reference, the guidelines for marking tests as `@nonblocking` are:
https://github.com/aws/serverless-application-model/blob/801c3fc2f457a8077edc717b8eb6879111031fbe/integration/helpers/base_test.py#L57-L63
In this case we do use `Parameters`. Specifically, the tests use these subnets:
https://github.com/aws/serverless-application-model/blob/801c3fc2f457a8077edc717b8eb6879111031fbe/integration/resources/templates/combination/function_with_msk.yaml#L34-L40
https://github.com/aws/serverless-application-model/blob/801c3fc2f457a8077edc717b8eb6879111031fbe/integration/combination/test_function_with_msk.py#L55-L59
Created by the companion stack: …
=> chore: make MSK tests non-blocking

.github/workflows/schema.yml
Currently runs at 5 PM PDT; this sets it during normal hours at 11 AM PDT.
=> chore: run schema update earlier in the day

samtranslator/model/connector/connector.py, samtranslator/model/connector_profiles/profile.py, samtranslator/model/connector_profiles/profiles.json, tests/model/connector_profiles/test_profile.py
We want to read from profiles.json and get CFN resource properties for SAM Connectors
Added new tests, all tests passed.
=> chore: Get CFN resource properties from profiles.json for SAM Connectors

DEVELOPMENT_GUIDE.md
=> docs: fix schema links

integration/combination/test_custom_http_api_domains_test.py, integration/combination/test_custom_rest_api_domains.py, tests/translator/input/api_with_custom_domain_regional.yaml, tests/translator/input/api_with_custom_domains_edge.yaml, tests/translator/input/api_with_custom_domains_regional_ownership_verification.yaml, tests/translator/input/http_api_with_custom_domains_regional.yaml, tests/translator/input/http_api_with_custom_domains_regional_ownership_verification.yaml, tests/translator/output/api_with_custom_domain_regional.json, tests/translator/output/api_with_custom_domains_edge.json, tests/translator/output/api_with_custom_domains_regional_ownership_verification.json, tests/translator/output/aws-cn/api_with_custom_domain_regional.json, tests/translator/output/aws-cn/api_with_custom_domains_edge.json, tests/translator/output/aws-cn/api_with_custom_domains_regional_ownership_verification.json, tests/translator/output/aws-cn/http_api_with_custom_domains_regional.json, tests/translator/output/aws-cn/http_api_with_custom_domains_regional_ownership_verification.json, tests/translator/output/aws-us-gov/api_with_custom_domain_regional.json, tests/translator/output/aws-us-gov/api_with_custom_domains_edge.json, tests/translator/output/aws-us-gov/api_with_custom_domains_regional_ownership_verification.json, tests/translator/output/aws-us-gov/http_api_with_custom_domains_regional.json, tests/translator/output/aws-us-gov/http_api_with_custom_domains_regional_ownership_verification.json, tests/translator/output/http_api_with_custom_domains_regional.json, tests/translator/output/http_api_with_custom_domains_regional_ownership_verification.json
Encountering certificate issues with these tests; added equivalent transform tests and marking as non-blocking since we've already tested it.
The integration tests mostly check that the right resources are made and that some of the properties are transformed as expected. This can be verified through the transform tests. 
https://github.com/aws/serverless-application-model/blob/2c06b57402ab6000a3f0e3c2085babac54aa2648/integration/combination/test_custom_http_api_domains_test.py#L32-L37
https://github.com/aws/serverless-application-model/blob/2c06b57402ab6000a3f0e3c2085babac54aa2648/integration/combination/test_custom_rest_api_domains.py#L28-L31
There are cases where the integration tests check inside files of the deployed s3 bucket …
=> chore: make custom domains api test nonblocking

integration/combination/test_state_machine_with_schedule.py, tests/translator/input/state_machine_with_schedule_cloudwatch_event.yaml, tests/translator/input/state_machine_with_schedule_cloudwatch_event_target_id.yaml, tests/translator/output/aws-cn/state_machine_with_schedule_cloudwatch_event.json, tests/translator/output/aws-cn/state_machine_with_schedule_cloudwatch_event_target_id.json, tests/translator/output/aws-us-gov/state_machine_with_schedule_cloudwatch_event.json, tests/translator/output/aws-us-gov/state_machine_with_schedule_cloudwatch_event_target_id.json, tests/translator/output/state_machine_with_schedule_cloudwatch_event.json, tests/translator/output/state_machine_with_schedule_cloudwatch_event_target_id.json
These tests blocked the pipeline; added equivalent transform tests and marking as non-blocking since we've already tested it.
The integration tests only check that the right resources are made and that the properties are transformed as expected. This can be verified through the transform tests. 
https://github.com/aws/serverless-application-model/blob/b02c0a43f71f2759389307f8c77802ca12831443/integration/combination/test_state_machine_with_schedule.py#L33-L61
Ensured new transform tests are same as the integration ones and that the output is expected. 
By submitting this pull request, I confirm that …
=> chore: make statemachine cw events test nonblocking

DEVELOPMENT_GUIDE.md, bin/add_transform_test.py, tests/translator/input/api_with_custom_domains_regional.yaml, tests/translator/input/basic_state_machine_with_tags.yaml, tests/translator/input/state_machine_with_api_combination.yaml, tests/translator/input/state_machine_with_api_single.yaml, tests/translator/output/api_with_custom_domains_regional.json, tests/translator/output/aws-cn/api_with_custom_domains_regional.json, tests/translator/output/aws-cn/basic_state_machine_with_tags.json, tests/translator/output/aws-cn/state_machine_with_api_combination.json, tests/translator/output/aws-cn/state_machine_with_api_single.json, tests/translator/output/aws-us-gov/api_with_custom_domains_regional.json, tests/translator/output/aws-us-gov/basic_state_machine_with_tags.json, tests/translator/output/aws-us-gov/state_machine_with_api_combination.json, tests/translator/output/aws-us-gov/state_machine_with_api_single.json, tests/translator/output/basic_state_machine_with_tags.json, tests/translator/output/state_machine_with_api_combination.json, tests/translator/output/state_machine_with_api_single.json
So far the script didn't always generate the correct output as we kept using (from perspective of transform) the default region.
This should now match what the transform tests do, so it should always pass the tests without hacks.
=> feat: make `add_transform_test.py` always match expected output

samtranslator/model/eventsources/push.py, tests/translator/input/function_with_sns_event_source_all_parameters.yaml, tests/translator/output/aws-cn/function_with_sns_event_source_all_parameters.json, tests/translator/output/aws-us-gov/function_with_sns_event_source_all_parameters.json, tests/translator/output/function_with_sns_event_source_all_parameters.json
https://github.com/aws/serverless-application-model/issues/3214
Remove the validation of SNS Event `FilterPolicy` because it's a pass-through prop.
Make `FilterPolicy` nested json in transform test and test passes.
=> fix: Remove validation of SNS Event FilterPolicy

bin/sam-translate.py
Didn't find an easy way to print directly to `stdout`, so here's that.
```
bin/sam-translate.py --template-file template.yaml --stdout
```
=> feat: add `--stdout` to `sam-translate.py`

integration/resources/templates/combination/graphqlapi_lambda_resolver.yaml, integration/resources/templates/combination/graphqlapi_pipeline_resolver.yaml, samtranslator/internal/model/appsync.py, samtranslator/model/sam_resources.py, tests/translator/input/error_graphqlapi.yaml, tests/translator/input/graphqlapi_resolver_function_with_lambda_datasource.yaml, tests/translator/output/aws-cn/graphqlapi_resolver_function_with_lambda_datasource.json, tests/translator/output/aws-us-gov/graphqlapi_resolver_function_with_lambda_datasource.json, tests/translator/output/graphqlapi_resolver_function_with_lambda_datasource.json
Resolvers provide by default generated code to pass request to functions and receive response. There is no need to ask a customer for Runtime when default code is used because we know ourselves which Runtime should be used for the generated code.
=> Set runtime for resolvers which use generated code

samtranslator/model/lambda_.py, samtranslator/model/sam_resources.py, tests/translator/output/aws-cn/function_with_runtime_config.json, tests/translator/output/aws-cn/globals_for_function.json, tests/translator/output/aws-us-gov/function_with_runtime_config.json, tests/translator/output/aws-us-gov/globals_for_function.json, tests/translator/output/function_with_runtime_config.json, tests/translator/output/globals_for_function.json
RuntimeManagementConfig was previous also applied to the AWS::Lambda::Version incorrectly.
-  [x] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
=> fix:RuntimeManagementConfig

integration/resources/templates/combination/graphqlapi_pipeline_resolver.yaml
=> chore: switch to SimpleTable in gql integ tests

samtranslator/plugins/api/implicit_api_plugin.py, tests/plugins/api/test_implicit_api_plugin.py, tests/translator/input/function_with_globals_tags_and_propagate_tags.yaml, tests/translator/output/aws-cn/function_with_globals_tags_and_propagate_tags.json, tests/translator/output/aws-us-gov/function_with_globals_tags_and_propagate_tags.json, tests/translator/output/function_with_globals_tags_and_propagate_tags.json
Propagate Tags doesn't work property when tags is defined in globals section. 
Added new tests and existing tests pass.
=> fix: Fix Propagate Tags when Tags is defined in Globals

integration/resources/templates/combination/api_with_authorizer_apikey.yaml
The value property had underscores in it which caused some integ tests to fail. 
=> chore: change api key resource's value property

pytest.ini
Errors occurred when running `make prepare-companion-stack` (required for running integration tests): 
`pytest.PytestUnknownMarkWarning: Unknown pytest.mark.setup`
`pytest.PytestUnknownMarkWarning: Unknown pytest.mark.teardown`
Adding `setup` and `teardown` markers to `pytest.ini` file resolved the above errors.
Ran `make prepare-companion-stack` command and some integration tests successfully.
=> fix: Add setup and teardown markers to make companion stack

samtranslator/internal/schema_source/aws_serverless_function.py, schema_source/sam.schema.json
Add missing RuleName to EventBridgeRuleEventProperties Schema
- [x ] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
=> [fix]: Add RuleName to EventBridgeRuleEventProperties

samtranslator/validator/validator.py
Leaving the deprecated tag on.
Relates to #3257 and SAM CLI issues with the logic removal.
Add back the validator logic we removed, but without tests (as we kept the deprecated tag on so calls to this code will fail).
`make test` passes, so we don't have any references to this code. SAM CLI verified that this unblocks them.
=> Revert Validator Removal

integration/combination/test_function_with_implicit_api_with_timeout.py, integration/resources/expected/combination/function_with_implicit_api_with_timeout.json, integration/resources/templates/combination/function_with_implicit_api_with_timeout.yaml, samtranslator/internal/schema_source/aws_serverless_function.py, samtranslator/model/eventsources/push.py, samtranslator/open_api/base_editor.py, samtranslator/open_api/open_api.py, schema_source/sam.schema.json, tests/translator/input/implicit_api_with_timeout.yaml, tests/translator/output/aws-cn/implicit_api_with_timeout.json, tests/translator/output/aws-us-gov/implicit_api_with_timeout.json, tests/translator/output/implicit_api_with_timeout.json
Feature request discussion: [https://github.com/aws/serverless-application-model/discussions/3287](https://github.com/aws/serverless-application-model/discussions/3287)
- Both Global level and Function level support are requested, but only Function level support is implemented in this pull request.
Add TimeoutInMillis Property to API Event Source (currently only supported for HTTP API Event Source). 
Example:
```
MyFunction:
Properties:
Handler: src/handlers/code.handler
Events:
MyApiEvent:
Type: Api  # API Event Source
Properties:
Path: /hello
Method: GET
TimeoutInMillis: 5000 # Now supported
```
Validated with transform tests and integration tests. Transformed template with added TimeoutInMillis property, then deployed it successfully. Added integration …
=> feat: Add TimeoutInMillis Property to API Event Source

samtranslator/plugins/api/implicit_api_plugin.py
Dip fix on `PropagateTags` property.
All tests passed. 
=> fix: Fix availability dip in PropagateTags property

.cfnlintrc.yaml, integration/combination/test_function_with_implicit_api_with_timeout.py, integration/combination/test_function_with_intrinsics_resource_attributes.py, integration/resources/expected/combination/function_with_intrinsics_resource_attribute.json, integration/resources/templates/combination/function_with_intrinsics_resource_attribute.yaml, samtranslator/sdk/resource.py, tests/translator/input/function_with_intrinsics_resource_attribute.yaml, tests/translator/output/aws-cn/function_with_intrinsics_resource_attribute.json, tests/translator/output/aws-us-gov/function_with_intrinsics_resource_attribute.json, tests/translator/output/function_with_intrinsics_resource_attribute.json
CloudFormation now supports intrinsics in `DeletionPolicy` and `UpdateReplacePolicy`. SAM transform is enforcing a (now incorrect) validation on all DeletionPolicy fields that's preventing us from using intrinsic functions there. The transform doesn't need to process those values, it just needs to pass them through. CFN has updated their core language to permit this use case
Shouldn't have impact on any existing SAM behaviour. All current tests pass
=> chore: Remove Validation on DeletionPolicy and UpdateReplacePolicy

samtranslator/internal/schema_source/aws_serverless_function.py, schema_source/sam.schema.json
#3322 
Adding `FunctionResponseTypes` for Lambda SQS event sources
Possibly lacking in this department, but
- compared to [other PR](https://github.com/aws/serverless-application-model/pull/3319) implementing schema changes
- ran `make schema`
- ran `make pr` and verified it all passed
=> chore: Update docs (aws#3322)

integration/resources/templates/combination/connector_bucket_to_function_write.yaml, samtranslator/model/sam_resources.py, tests/translator/input/function_with_alias_and_code_sha256.yaml, tests/translator/output/aws-cn/function_with_alias_all_properties_and_code_sha256.json, tests/translator/output/aws-cn/function_with_alias_and_code_sha256.json, tests/translator/output/aws-us-gov/function_with_alias_all_properties_and_code_sha256.json, tests/translator/output/aws-us-gov/function_with_alias_and_code_sha256.json, tests/translator/output/function_with_alias_all_properties_and_code_sha256.json, tests/translator/output/function_with_alias_and_code_sha256.json
Append the value of CodeSha256 to end of Lambda Function description. This would cause an update to the existing users who use codesha256 but since it will always create a new lambda version, it wouldn't cause any downtime for users. 
```
When you deploy a new version of an AWS Lambda function, it does not cause downtime for the existing function. AWS Lambda is designed to allow seamless deployments without affecting the current running version
```
Additionally add `DeletionPolicy` and `UpdateReplacePolicy` to an integ test.
All tests passed.
By submitting this pull request, I confirm that my …
=> fix: Append CodeSha256 Value to Description

samtranslator/internal/schema_source/aws_serverless_statemachine.py, samtranslator/model/stepfunctions/events.py, schema_source/sam.schema.json, tests/translator/input/serverless_statemachine_eventbridgerule_with_input_transformer.yaml, tests/translator/output/aws-cn/serverless_statemachine_eventbridgerule_with_input_transformer.json, tests/translator/output/aws-us-gov/serverless_statemachine_eventbridgerule_with_input_transformer.json, tests/translator/output/serverless_statemachine_eventbridgerule_with_input_transformer.json
[3333](https://github.com/aws/serverless-application-model/issues/3333)
Adding property `InputTransformer` to `AWS::Serverless::StateMachine`
End to end test by deploying the transformed template.
=> Adding InputTransformer Property

samtranslator/model/eventsources/pull.py, tests/translator/input/self_managed_kafka_with_SERVER_ROOT_CA_CERTIFICATE_and_auth_mechanism.yaml, tests/translator/output/aws-cn/self_managed_kafka_with_SERVER_ROOT_CA_CERTIFICATE_and_auth_mechanism.json, tests/translator/output/aws-us-gov/self_managed_kafka_with_SERVER_ROOT_CA_CERTIFICATE_and_auth_mechanism.json, tests/translator/output/self_managed_kafka_with_SERVER_ROOT_CA_CERTIFICATE_and_auth_mechanism.json
[#3339](https://github.com/aws/serverless-application-model/issues/3339)
Removed `"SERVER_ROOT_CA_CERTIFICATE"` from `AUTH_MECHANISM` as unlike the other types in `AUTH_MECHANISM` `"SERVER_ROOT_CA_CERTIFICATE"` can be enabled at the same time.
=> fix: Kafka Auth Mechanism "SERVER_ROOT_CA_CERTIFICATE" and other Auth can't be used together

integration/resources/templates/single/basic_function_with_function_url_config.yaml, integration/resources/templates/single/basic_function_with_function_url_with_autopuplishalias.yaml
Using safe authoriser in function. URL integ tests. 
Motivation: if the integ test resource stack is stuck and not deleted, the function with a function url without authoriser is considered unsafe by AWS AppSec.
=> Safe Auth in function URL tests

integration/resources/expected/single/basic_function_with_function_url_config.json, integration/resources/expected/single/basic_function_with_function_url_with_autopuplishalias.json, integration/single/test_basic_function.py
Fixing tests, removing expectation on Resource policy for Function URL case.
Resource policy is optional for the AWS_IAM auth in Function URL so SAM doesn't create it as it makes sense only with cross-account access.
There are many transform tests for function URL, so the case with NONE auth is handled there.
=> fix integ tests

integration/conftest.py
Catch network interface deletion failure. We should not throw an error when we failed to delete an unused network interface.
N/A
=> fix: Catch network interface deletion failure

samtranslator/model/eventsources/push.py, samtranslator/model/sam_resources.py, samtranslator/model/sqs.py, tests/model/eventsources/test_sns_event_source.py, tests/translator/input/function_with_fifo_topic_event.yaml, tests/translator/output/aws-cn/function_with_fifo_topic_event.json, tests/translator/output/aws-us-gov/function_with_fifo_topic_event.json, tests/translator/output/function_with_fifo_topic_event.json
=> fix: Support creating a FIFO queue if using FIFO SNS event

samtranslator/internal/schema_source/aws_serverless_statemachine.py, samtranslator/model/stepfunctions/events.py, schema_source/sam.schema.json, tests/model/stepfunctions/test_schedule_event.py, tests/translator/input/state_machine_with_schedule_role.yaml, tests/translator/output/aws-cn/state_machine_with_schedule_role.json, tests/translator/output/aws-us-gov/state_machine_with_schedule_role.json, tests/translator/output/state_machine_with_schedule_role.json
feature request discussion [#3290](https://github.com/aws/serverless-application-model/discussions/3290
)
Add new Role property to Schedule for user to pass in their own role to be used with the generated event rule
Example 
```Resources:
MyStateMachine:
Type: AWS::Serverless::StateMachine
Properties:
Definition:
Comment: A Hello World example of the Amazon States Language using Pass states
StartAt: Hello
States:
Hello:
Type: Pass
Result: Hello
Next: World
World:
Type: Pass
Result: World
End: true
Policies:
- Version: '2012-10-17'
Statement:
- Effect: Deny
Action: '*'
Resource: '*'
Events:
CWSchedule:
Type: Schedule
Properties:
Schedule: rate(1 minute)
Description: test schedule
Enabled: false
Role: with-role-MyStateMachineCWScheduleRole-RI4SGRI1ORL9
```
Validated with tests and …
=> feat: allow user to provide role for schedule

tests/plugins/application/test_serverless_app_plugin.py
These SAR tests fail for python 3.10 or above. Couldn't debug why so going to skip it for now and investigate later.
=> fix: skip SAR tests if python version > 3.10

samtranslator/open_api/open_api.py
We had an issue where users explicitly set `components` to None and the setdefault code wouldn't set it to Py27Dict which then caused an error.
All existing tests pass.
=> fix: Set to Py27Dict if components is explicitly set to None

pytest.ini, tests/plugins/application/test_serverless_app_plugin.py
We used `-W` flag to turn warnings into errors. We need to ignore the deprecation warnings.
All tests pass.
=> Fix GitHub Action Issues in Python 3.10 and 3.11

samtranslator/plugins/api/implicit_api_plugin.py, tests/translator/input/valid_update_replace_policy_and_deletion_policy.yaml, tests/translator/output/aws-cn/valid_update_replace_policy_and_deletion_policy.json, tests/translator/output/aws-us-gov/valid_update_replace_policy_and_deletion_policy.json, tests/translator/output/valid_update_replace_policy_and_deletion_policy.json
Raises error when UpdateReplacePolicy is not Retain, Snapshot, Delete or None.
Created a template to test and ran make pr.
=> Fix: Raise Error When UpdateReplacePolicy is not correctly defined.

integration/single/test_basic_state_machine.py
This test should be skipped if statemachine isn't available
=> fix: skip statemachine test

README.md
node 16 is EOL in Sep 2023:
https://nodejs.org/en/blog/announcements/nodejs16-eol
=> doc: Replace EOL nodejs16.x from README

Makefile, bin/git_lfs_download.sh
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cfnspec/README.md
CDK moved where the schema files are stored. And it's now stored as Git LFS. We have to update how we download the file.
`make schema-all` works locally.
=> chore: Update how we download CFN documentation

bin/run_cfn_lint.sh, tests/translator/input/function_with_sns_event_source_all_parameters.yaml, tests/translator/output/aws-cn/function_with_sns_event_source_all_parameters.json, tests/translator/output/aws-us-gov/function_with_sns_event_source_all_parameters.json, tests/translator/output/function_with_sns_event_source_all_parameters.json
To be able to use new fields added to CFN resources, we need to keep CFN schema used by `cfn-lint` up-to-date.
We don't want to update to the latest `cfn-lint` yet because we'll have to change many ARNs and other values in the transform tests to meet `cfn-lint` requirements which are not important for the transforms tests (i.e use looking-like-legit ARNs instead of any string).
=> [chore]: keep cfn schema used by cfn-lint up-to-date

samtranslator/internal/model/appsync.py, samtranslator/internal/schema_source/aws_serverless_graphqlapi.py, samtranslator/model/sam_resources.py, schema_source/sam.schema.json, tests/translator/input/graphqlapi_visibility_owner_contract.yaml, tests/translator/output/aws-cn/graphqlapi_visibility_owner_contract.json, tests/translator/output/aws-us-gov/graphqlapi_visibility_owner_contract.json, tests/translator/output/graphqlapi_visibility_owner_contract.json
#3422
Adding new fields AppSync has added to CFN.
=> adding new appsync props

samtranslator/model/tags/resource_tagging.py, tests/translator/input/simple_function_with_global_tags_false.yaml, tests/translator/input/simple_function_with_tags_false.yaml, tests/translator/input/simple_table_with_tags_false.yaml, tests/translator/output/aws-cn/simple_function_with_global_tags_false.json, tests/translator/output/aws-cn/simple_function_with_tags_false.json, tests/translator/output/aws-cn/simple_table_with_tags_false.json, tests/translator/output/aws-us-gov/simple_function_with_global_tags_false.json, tests/translator/output/aws-us-gov/simple_function_with_tags_false.json, tests/translator/output/aws-us-gov/simple_table_with_tags_false.json, tests/translator/output/simple_function_with_global_tags_false.json, tests/translator/output/simple_function_with_tags_false.json, tests/translator/output/simple_table_with_tags_false.json
https://github.com/aws/serverless-application-model/issues/3426
When the value of a tag was False it would be set to the default "" value as the if statement evaluated the value rather than checking if it was None.
Tested by transforming template and looking at tags
=> fix: Tags with value of False got evaluated to ""

integration/combination/test_function_with_msk.py, integration/resources/templates/combination/function_with_msk_trigger_and_s3_onfailure_events_destinations.yaml
MSK tests failure due to missing ListBucket permission and MSK Cluster did not stablize.
The permission issue needs to be fixed
The second issue is expected and the root cause of flakiness. Added comment to explain it.
All tests pass.
=> fix: Msk Tests Failure due to Missing Permissions

integration/resources/templates/combination/function_with_mq.yaml, integration/resources/templates/combination/function_with_mq_using_autogen_role.yaml
mq tests were using an old version of `EngineVersion:`
=> chore: mq tests using a valid version

integration/combination/test_function_with_cwe_dlq_generated.py, integration/combination/test_function_with_policy_templates.py, integration/combination/test_state_machine_with_api.py, integration/combination/test_state_machine_with_cwe.py, integration/combination/test_state_machine_with_cwe_dlq_generated.py, integration/combination/test_state_machine_with_policy_templates.py, integration/combination/test_state_machine_with_schedule.py, integration/combination/test_state_machine_with_schedule_dlq_and_retry_policy.py, integration/helpers/resource.py, requirements/dev.txt
Ruff has entered 0.1.* and according to their [version policy](https://docs.astral.sh/ruff/versioning/):
> Ruff uses a custom versioning scheme that uses the minor version number for breaking changes and the patch version number for bug fixes. Ruff does not yet have a stable API; once Ruff's API is stable, the major version number and semantic versioning will be used.
`make pr`
=> chore: Upgrade ruff to 0.1.*

integration/resources/templates/combination/function_with_alias_intrinsics.yaml, integration/resources/templates/single/basic_function.yaml, integration/resources/templates/single/basic_function_event_destinations.yaml, integration/resources/templates/single/basic_function_no_envvar.yaml, integration/resources/templates/single/basic_function_openapi.yaml, integration/resources/templates/single/basic_function_with_arm_architecture.yaml, integration/resources/templates/single/basic_function_with_function_url_config.yaml, integration/resources/templates/single/basic_function_with_function_url_with_autopuplishalias.yaml, integration/resources/templates/single/basic_function_with_kmskeyarn.yaml, integration/resources/templates/single/basic_function_with_sns_dlq.yaml, integration/resources/templates/single/basic_function_with_sqs_dlq.yaml, integration/resources/templates/single/basic_function_with_tags.yaml, integration/resources/templates/single/basic_function_with_tracing.yaml, integration/resources/templates/single/basic_function_with_x86_architecture.yaml, integration/resources/templates/single/basic_layer_with_compatible_architecture.yaml, integration/resources/templates/single/basic_layer_with_parameters.yaml, integration/resources/templates/single/function_alias_with_http_api_events.yaml, integration/resources/templates/single/function_with_http_api_events.yaml, integration/resources/templates/single/function_with_http_api_events_and_auth.yaml, tests/schema/test_validate_schema.py
=> Chore:Upgrade integ tests to node to v18.x

samtranslator/model/s3_utils/uri_parser.py, tests/translator/output/error_function_with_dynamic_ref_codeuri.json
Allow dynamic reference as long as it doesn't include `/` in it.
All tests pass
=> fix: Allow Dynamic Reference in CodeUri Property if no / used

.github/workflows/close_issue_message.yml
SAM CLI had similar github action that will auto comment if a user comments on a closed issue. Add the same one for SAM-T. 
=> chore: Add GitHub Action to auto comment if customers comment on a closed issue

samtranslator/sdk/resource.py, samtranslator/sdk/template.py, samtranslator/third_party/py27hash/hash.py
Updated version of ruff requires to remove some now unused `noqa`, see failed build https://github.com/aws/serverless-application-model/pull/3503
=> [chore]: Remove some ruff noqa (new version requirement)

.github/dependabot.yml
None
Adds the `dependabot.yml` to configure dependabot to upgrade other GHAs
Config is mostly stolen from SAM CLI's repo, minus some string changes.
Relevant Dependabot Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> chore: Allow dependabot to upgrade other GHAs

samtranslator/model/eventsources/pull.py, tests/translator/input/function_with_event_dest_basic.yaml, tests/translator/output/aws-cn/function_with_event_dest_basic.json, tests/translator/output/aws-us-gov/function_with_event_dest_basic.json, tests/translator/output/function_with_event_dest_basic.json
If an intrinsic is within the Function.Policies Property, the `d["PolicyDocument"]` will fail because the valid policy is backed within the `FN:If`. Instead, we access `PolicyDocument` through a `.get()` call, which allows us to handle the intrinsic case.
None
See above
Wrote a test to validate the template is transformable.
=> chore: Fix KeyError when accessing PolicyDocument

integration/helpers/deployer/deployer.py, integration/helpers/deployer/utils/time_util.py
finishing what was started in https://github.com/aws/serverless-application-model/pull/3538
changing it in integ tests too
=> [chore] switch to `timezone.utc` instead of `utcnow()` since the last one is deprecated in Python 12

samtranslator/region_configuration.py, samtranslator/translator/arn_generator.py, tests/unit/test_region_configuration.py, tests/unit/translator/test_arn_generator.py
Adding new aws partition to our code
=> chore: add new partition

samtranslator/translator/arn_generator.py, tests/translator/test_arn_generator.py
Need to find a way to maintain this static list for new partitions. Using `{AWS::Partition}` should theoretically work.
=> chore: deal with adding new partitions for arn generation

integration/resources/templates/combination/connector_sfn_to_sns_write.yaml, integration/resources/templates/combination/function_with_alias_and_event_sources.yaml, integration/resources/templates/combination/function_with_all_event_types.yaml, integration/resources/templates/combination/function_with_all_event_types_condition_false.yaml, integration/resources/templates/combination/function_with_kinesis.yaml, integration/resources/templates/combination/function_with_kinesis_intrinsics.yaml, integration/resources/templates/single/basic_function_with_sns_dlq.yaml
N/A
Enable encryption using `KmsMasterKeyId` for SNS topic and `StreamEncryption` for Kinesis stream resources in integration test templates to follow best security practices.
Ran updated integration tests successfully.
=> chore: encrypt SNS and Kinesis resources in integration test templates

integration/resources/templates/single/basic_function.yaml, integration/resources/templates/single/basic_function_no_envvar.yaml, integration/resources/templates/single/basic_function_openapi.yaml, integration/resources/templates/single/basic_function_with_tags.yaml
N/A
We're having some issues with deploying this template in a new region. We suspect the issue is the added the policies. Removing them here and re-deploying in the region to see if that fixes the issue
=> fix: remove unused policies in integ test

samtranslator/region_configuration.py, tests/unit/test_region_configuration.py
Missed adding the aws-iso-f partition to this static list
=> chore: add missing partition to edge config support

Makefile, integration/ruff.toml, requirements/dev.txt, ruff.toml, samtranslator/model/api/http_api_generator.py, samtranslator/model/eventsources/push.py, samtranslator/model/intrinsics.py, samtranslator/model/sam_resources.py, samtranslator/sdk/parameter.py, samtranslator/sdk/resource.py, samtranslator/third_party/py27hash/hash.py, samtranslator/utils/py27hash_fix.py, tests/model/api/test_http_api_generator.py, tests/ruff.toml
- Ruff has changed the toml config schema. Updating the current ones to match the new one.
- Fix violations
=> chore: Upgrade ruff to 0.4.5

integration/conftest.py
None
Removes the code that deletes ENI. This was added because MQ was not deleting the ENIs which is not happening.
`make pr`
=> fix: Remove ENI manual deletion

samtranslator/model/__init__.py
Added exception block to catch 'AttributeError' happening due to missing error_wrapper import in pydantic v1.10.15
This is a workaround till pydantic team solves the issue at their end:
Ticket to pydantic team https://github.com/pydantic/pydantic/issues/9625
Tests ran successfully in python virtual env.
Commands used: 
```
python3 -m venv .venv
source .venv/bin/activate
make init
make test
make pr
black /Users/shikagg/sam_clone/serverless-application-model/samtranslator/model/__init__.py  -> to fix error 
1 file would be reformatted, 364 files would be left unchanged.
make: *** [format-check] Error 1
```
Result
```
Required test coverage of 95% reached. Total coverage: 95.80%
3973 passed in 83.39s (0:01:23) 
```
Please reach out in the comments if you want to add an example. Examples will …
=> fix: AttributeError: module 'pydantic.v1' has no attribute 'error_wrapper'

integration/helpers/base_test.py, integration/resources/templates/single/state_machine_with_api.yaml, integration/single/test_basic_api.py
N/A
We've seen this test fail in a couple of regions with the error `Request to ... failed with status: 403, expected status: 200`. This is also a known flaky test which we've seen fail before and succeed after a simple retry.
After investigation we concluded that the error is likely because the endpoint configuration is automatically set to EDGE which routes requests to a CloudFront Point of Presence. We suspect the test is calling the endpoint right after the stack is deployed but before the routing can take place. To mitigate this we set the endpoint configuration to REGIONAL for now.
Ran the test locally, it deployed and everything passed as before.
added to `sam init` through …
=> fix: change endpoint configuration for state machine integ test

samtranslator/model/apigatewayv2.py, tests/translator/input/http_api_openapi_with_propagate_tags.yaml, tests/translator/output/aws-cn/function_with_events_and_propagate_tags.json, tests/translator/output/aws-cn/http_api_openapi_with_propagate_tags.json, tests/translator/output/aws-cn/httpapi_with_propagate_tags.json, tests/translator/output/aws-us-gov/function_with_events_and_propagate_tags.json, tests/translator/output/aws-us-gov/http_api_openapi_with_propagate_tags.json, tests/translator/output/aws-us-gov/httpapi_with_propagate_tags.json, tests/translator/output/function_with_events_and_propagate_tags.json, tests/translator/output/http_api_openapi_with_propagate_tags.json, tests/translator/output/httpapi_with_propagate_tags.json
Currently if a user sets `PropagateTags` to True in the "AWS::Serverless::HttpApi" resource and specifies the DefinitionBody property with an OpenApi definition, they will encounter the following deploy-time error:
```
Redundant fields [tags={"TagKey":"TagValue","httpapi:createdBy":"SAM"}] provided when either Body or BodyS3Location is not empty
```
CloudFormation does not allow both the `Tags` property being set and [x-amazon-apigateway-tag-value](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-openapi-extensions-x-amazon-apigateway-tag-value.html) being set in the `Body` property.
Update `assign_tags()` method for `ApiGatewayV2HttpApi` class to return (no-op). 
For context, `Tags` can only be defined when `DefinitionBody` is specified or else we raise an …
=> fix: prevent redundant tags being added to AWS::ApiGatewayV2::Api

samtranslator/model/__init__.py
Reverts aws/serverless-application-model#3611 since the pydantic issue persists with this PR.
=> Revert "fix: AttributeError: module 'pydantic.v1' has no attribute 'error_wrapper'"

requirements/base.txt
#3617
Pydantic versions 1.10.15 and 1.10.17 introduced breaking changes. Exclude those versions from being installed.
Ran `make init` with `pydantic>=1.8,!=1.10.15,!=1.10.17,<2` (to insure pydantic V1 got installed). `pydantic 1.10.16` was installed
=> fix: exclude breaking pydantic version

integration/helpers/base_test.py, integration/single/test_basic_api.py
N/A
`test_state_machine_with_api_single_quotes_input` integ test is failing sometimes with status code 403 from APIGW. This test seems flaky test. However, We are adding retry mechanism to this test which can make this test pass.
Error:
```
Request to .... failed with status: 403, expected status: 200
```
=> fix: add retry for statemachine integ test

integration/resources/templates/combination/api_with_authorizers_max.yaml, integration/resources/templates/combination/api_with_authorizers_max_openapi.yaml, integration/resources/templates/combination/function_with_mq.yaml, integration/resources/templates/combination/function_with_msk.yaml, integration/resources/templates/combination/function_with_msk_trigger_and_s3_onfailure_events_destinations.yaml, integration/resources/templates/single/state_machine_with_api.yaml
None
In some of the integ test templates, for managed policies, it is using an ARN with hardcoded AWS partition. This will fail the test in some regions, hence, replacing the partition part with the `AWS::Partition` parameter. [Example](https://github.com/samson-keung/serverless-application-model/blob/725a3121fb401521168661adaf843ccfe3aee8a4/integration/resources/templates/combination/connector_function_to_bucket_read.yaml#L12) of other places where this is already done.
Followed the other places in the code where this is already done
- [n/a] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
added to …
=> chore: Fix Managed Policy ARNs with hardcoded partition in tests

integration/resources/templates/single/basic_api_with_mode.yaml
None
Hardcoded domain does not work in all regions. It caused test failures
Same as https://github.com/aws/serverless-application-model/blob/develop/integration/resources/templates/single/state_machine_with_api.yaml#L41
- [n/a] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
=> chore: Fix hardcoded endpoint domain in test template

tests/translator/input/graphqlapi_function_by_id.yaml, tests/translator/input/graphqlapi_multiple_none_datasource_functions.yaml, tests/translator/input/graphqlapi_resolver_function_with_lambda_datasource.yaml, tests/translator/output/aws-cn/graphqlapi_function_by_id.json, tests/translator/output/aws-cn/graphqlapi_multiple_none_datasource_functions.json, tests/translator/output/aws-cn/graphqlapi_resolver_function_with_lambda_datasource.json, tests/translator/output/aws-us-gov/graphqlapi_function_by_id.json, tests/translator/output/aws-us-gov/graphqlapi_multiple_none_datasource_functions.json, tests/translator/output/aws-us-gov/graphqlapi_resolver_function_with_lambda_datasource.json, tests/translator/output/graphqlapi_function_by_id.json, tests/translator/output/graphqlapi_multiple_none_datasource_functions.json, tests/translator/output/graphqlapi_resolver_function_with_lambda_datasource.json
None
Update appsync function related tests with valid runtime value `APPSYNC_JS` as the cfn-lint failed
by running `make pr`
=> chore: update valid appsync function runtime in tests

tests/translator/input/graphqlapi_cognito_default_auth.yaml, tests/translator/output/aws-cn/graphqlapi_cognito_default_auth.json, tests/translator/output/aws-us-gov/graphqlapi_cognito_default_auth.json, tests/translator/output/graphqlapi_cognito_default_auth.json
`make pr` failed because `something` is not a valid value when using the latest cfn-lint
update the transform test 
=> chore: fix graphql transform test template

integration/resources/templates/combination/function_with_alias_all_properties_and_layer_version.yaml
NA
NodeJs 20.x lambda runtime is not fully available in all regions. Hence downgrading it to nodejs18.x in lambda integ test similar to other integ tests.
Run `make pr`
=> fix:downgrade lambda runtime version to nodejs18.x in integ test

tests/translator/input/basic_application.yaml, tests/translator/input/definition_body_intrinsics_support.yaml, tests/translator/input/function_with_deployment_preference_alarms_intrinsic_if.yaml, tests/translator/input/s3_with_condition.yaml, tests/translator/input/sns_intrinsics.yaml, tests/translator/output/aws-cn/basic_application.json, tests/translator/output/aws-cn/definition_body_intrinsics_support.json, tests/translator/output/aws-cn/function_with_deployment_preference_alarms_intrinsic_if.json, tests/translator/output/aws-cn/s3_with_condition.json, tests/translator/output/aws-cn/sns_intrinsics.json, tests/translator/output/aws-us-gov/basic_application.json, tests/translator/output/aws-us-gov/definition_body_intrinsics_support.json, tests/translator/output/aws-us-gov/function_with_deployment_preference_alarms_intrinsic_if.json, tests/translator/output/aws-us-gov/s3_with_condition.json, tests/translator/output/aws-us-gov/sns_intrinsics.json, tests/translator/output/basic_application.json, tests/translator/output/definition_body_intrinsics_support.json, tests/translator/output/function_with_deployment_preference_alarms_intrinsic_if.json, tests/translator/output/s3_with_condition.json, tests/translator/output/sns_intrinsics.json
Due to a recent update to the cfn_lint, Conditions in some tests files are violating [W8003 cfn_lint rule](https://github.com/aws-cloudformation/cfn-lint/blob/bba21dc4d593989f38fd3477de7233a4bb2833d2/src/cfnlint/rules/conditions/EqualsIsUseful.py#L14), making the linter fail. This PR updates the Condition section of those tests files to make the linter succeed.
make pr
=> update conditions in tests to fix lint failures

samtranslator/compat.py
#3617
https://github.com/pydantic/pydantic/issues/9742
Update compat.py to make sure pydantic v1 should call `import pydantic` correctly
starting from pydantic 1.10.17, `from pydantic import v1 as pydantic` will not fail anymore, adding additional check to make sure pydantic v1 will run `import pydantic` correctly`
`make test` with pydantic 1.10.17-1.10.21
=> fix(dep): compat.py should import right pydantic class for pydantic >= 1.10.17

integration/combination/test_function_with_alias.py
To skip the integration test for times when "Layer" functionality is not available in regions that are not GA yet. 
=> feat: skipping test if Layers is not available

.cfnlintrc.yaml, tests/translator/input/state_machine_with_schedule_role.yaml, tests/translator/output/aws-cn/state_machine_with_schedule_role.json, tests/translator/output/aws-us-gov/state_machine_with_schedule_role.json, tests/translator/output/state_machine_with_schedule_role.json
#3731 
Some of the tests were failing due to issues with the `cfn-lint` check. However, these lint checks were not considered important, and so they were ignored. The failing checks were related to IAM permissions and policies, which were not passing because some of the policies generated by the SAM did not actually exist.
=> fix(lambda): correcting tests

integration/resources/templates/combination/function_with_mq.yaml, integration/resources/templates/combination/function_with_mq_using_autogen_role.yaml
Integration tests were failing because of an old version of ActiveMQ being used. In theory 5.17 is still supported for [two more weeks](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/activemq-version-management.html#activemq-version-management-calendar), but it's still something we have to change anyway.
This required to change the variable `AutoMinorVersionUpgrade` that has to be true for this version of ActiveMQ
I ran integ tests (They were failing before, they succeeded afterwards)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> test: Fix MQ integ tests

samtranslator/model/cognito.py, tests/translator/input/cognito_template_with_new_properties.yaml, tests/translator/output/aws-cn/cognito_template_with_new_properties.json, tests/translator/output/aws-us-gov/cognito_template_with_new_properties.json, tests/translator/output/cognito_template_with_new_properties.json
Update the CognitoUserPool property types based on the [CloudFormation syntax ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html).
The changes were validated by running the sam transformer on the template in the issue and on another template with all of the new properties. There is also a new transform test for validating this.
=> feat: updated the cognito properties based on cloudformation properties

integration/conftest.py, integration/helpers/deployer/deployer.py
N/a
In the integration tests, the companion stack being created is created with a change set. Often times, this change set is empty and ignored; after enough test runs, the stack hits its limit of 1000 changesets, causing create failures in the subsequent runs.
This change will now delete the created change set if it is empty.
In my personal account, I ran the tests a couple time to build up a couple empty change sets. I then made the change, and continued to run `make prepare-companion-stack`, manually verifying that there were no new changesets being kept on each test run.
By submitting this pull …
=> test: delete created change sets in companion stack if empty

integration/combination/test_function_with_msk.py, integration/resources/templates/combination/function_with_msk.yaml, integration/resources/templates/combination/function_with_msk_trigger_and_confluent_schema_registry.yaml, integration/resources/templates/combination/function_with_msk_trigger_and_s3_onfailure_events_destinations.yaml, integration/resources/templates/combination/function_with_msk_using_managed_policy.yaml, samtranslator/internal/schema_source/aws_serverless_function.py, schema_source/sam.schema.json
MSK tests are created more resources when they start polling (and the Topic we're connecting from doesn't even exist), so let's create the events with `Enabled: false`, so the polling doesn't actually start.
Problems seen in our integration testing infrastructure.
- Add `Enabled: false` to MSK templates in integration tests
- Add `Enabled` to the schema for MSK. Even though this property is supported, it wasn't part of the schema.
- Adding `s3:putObject` permissions to the test with an S3 destination for its event (`function_with_msk_trigger_and_s3_onfailure_events_destinations.yaml`).
- `pytest --no-cov integration/combination/test_function_with_msk.py -vv`
added to `sam init` through …
=> fix: add `Enables` to MSK model. Use this property for MSK events in integ tests
